# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgConfig.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlgConfig(object):
  def setupUi(self, dlgConfig):
    dlgConfig.setObjectName("dlgConfig")
    dlgConfig.resize(624, 318)
    dlgConfig.setMinimumSize(QtCore.QSize(624, 318))
    dlgConfig.setMaximumSize(QtCore.QSize(624, 318))
    icon = QtGui.QIcon()
    icon.addPixmap(QtGui.QPixmap(":/cn5X/images/XYZAB.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    dlgConfig.setWindowIcon(icon)
    dlgConfig.setModal(True)
    self.verticalLayout_17 = QtWidgets.QVBoxLayout(dlgConfig)
    self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
    self.verticalLayout_17.setSpacing(0)
    self.verticalLayout_17.setObjectName("verticalLayout_17")
    self.tabWidget = QtWidgets.QTabWidget(dlgConfig)
    self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
    self.tabWidget.setObjectName("tabWidget")
    self.tab_1 = QtWidgets.QWidget()
    self.tab_1.setObjectName("tab_1")
    self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_1)
    self.gridLayout_6.setObjectName("gridLayout_6")
    spacerItem = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.gridLayout_6.addItem(spacerItem, 0, 1, 1, 1)
    spacerItem1 = QtWidgets.QSpacerItem(111, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.gridLayout_6.addItem(spacerItem1, 1, 0, 1, 1)
    self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_15.setObjectName("horizontalLayout_15")
    self.verticalLayout_16 = QtWidgets.QVBoxLayout()
    self.verticalLayout_16.setObjectName("verticalLayout_16")
    self.label = QtWidgets.QLabel(self.tab_1)
    self.label.setObjectName("label")
    self.verticalLayout_16.addWidget(self.label)
    self.label_2 = QtWidgets.QLabel(self.tab_1)
    self.label_2.setObjectName("label_2")
    self.verticalLayout_16.addWidget(self.label_2)
    self.label_13 = QtWidgets.QLabel(self.tab_1)
    self.label_13.setText("")
    self.label_13.setObjectName("label_13")
    self.verticalLayout_16.addWidget(self.label_13)
    self.label_3 = QtWidgets.QLabel(self.tab_1)
    self.label_3.setObjectName("label_3")
    self.verticalLayout_16.addWidget(self.label_3)
    self.label_4 = QtWidgets.QLabel(self.tab_1)
    self.label_4.setObjectName("label_4")
    self.verticalLayout_16.addWidget(self.label_4)
    self.label_5 = QtWidgets.QLabel(self.tab_1)
    self.label_5.setObjectName("label_5")
    self.verticalLayout_16.addWidget(self.label_5)
    self.label_14 = QtWidgets.QLabel(self.tab_1)
    self.label_14.setObjectName("label_14")
    self.verticalLayout_16.addWidget(self.label_14)
    self.label_15 = QtWidgets.QLabel(self.tab_1)
    self.label_15.setObjectName("label_15")
    self.verticalLayout_16.addWidget(self.label_15)
    self.horizontalLayout_15.addLayout(self.verticalLayout_16)
    self.verticalLayout_15 = QtWidgets.QVBoxLayout()
    self.verticalLayout_15.setObjectName("verticalLayout_15")
    self.spinBox = QtWidgets.QSpinBox(self.tab_1)
    self.spinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.spinBox.setMaximum(99999)
    self.spinBox.setObjectName("spinBox")
    self.verticalLayout_15.addWidget(self.spinBox)
    self.spinBox_2 = QtWidgets.QSpinBox(self.tab_1)
    self.spinBox_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.spinBox_2.setMaximum(9999)
    self.spinBox_2.setObjectName("spinBox_2")
    self.verticalLayout_15.addWidget(self.spinBox_2)
    self.horizontalLayout = QtWidgets.QHBoxLayout()
    self.horizontalLayout.setSpacing(3)
    self.horizontalLayout.setObjectName("horizontalLayout")
    self.label_6 = QtWidgets.QLabel(self.tab_1)
    self.label_6.setAlignment(QtCore.Qt.AlignCenter)
    self.label_6.setObjectName("label_6")
    self.horizontalLayout.addWidget(self.label_6)
    self.label_7 = QtWidgets.QLabel(self.tab_1)
    self.label_7.setAlignment(QtCore.Qt.AlignCenter)
    self.label_7.setObjectName("label_7")
    self.horizontalLayout.addWidget(self.label_7)
    self.label_8 = QtWidgets.QLabel(self.tab_1)
    self.label_8.setAlignment(QtCore.Qt.AlignCenter)
    self.label_8.setObjectName("label_8")
    self.horizontalLayout.addWidget(self.label_8)
    self.label_9 = QtWidgets.QLabel(self.tab_1)
    self.label_9.setAlignment(QtCore.Qt.AlignCenter)
    self.label_9.setObjectName("label_9")
    self.horizontalLayout.addWidget(self.label_9)
    self.label_10 = QtWidgets.QLabel(self.tab_1)
    self.label_10.setAlignment(QtCore.Qt.AlignCenter)
    self.label_10.setObjectName("label_10")
    self.horizontalLayout.addWidget(self.label_10)
    self.label_11 = QtWidgets.QLabel(self.tab_1)
    self.label_11.setAlignment(QtCore.Qt.AlignCenter)
    self.label_11.setObjectName("label_11")
    self.horizontalLayout.addWidget(self.label_11)
    self.label_12 = QtWidgets.QLabel(self.tab_1)
    self.label_12.setAlignment(QtCore.Qt.AlignCenter)
    self.label_12.setObjectName("label_12")
    self.horizontalLayout.addWidget(self.label_12)
    self.verticalLayout_15.addLayout(self.horizontalLayout)
    self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_2.setSpacing(3)
    self.horizontalLayout_2.setObjectName("horizontalLayout_2")
    self.chkStepX = QtWidgets.QCheckBox(self.tab_1)
    self.chkStepX.setLayoutDirection(QtCore.Qt.RightToLeft)
    self.chkStepX.setText("")
    self.chkStepX.setObjectName("chkStepX")
    self.horizontalLayout_2.addWidget(self.chkStepX)
    self.chkStepY = QtWidgets.QCheckBox(self.tab_1)
    self.chkStepY.setLayoutDirection(QtCore.Qt.RightToLeft)
    self.chkStepY.setText("")
    self.chkStepY.setObjectName("chkStepY")
    self.horizontalLayout_2.addWidget(self.chkStepY)
    self.chkStepZ = QtWidgets.QCheckBox(self.tab_1)
    self.chkStepZ.setLayoutDirection(QtCore.Qt.RightToLeft)
    self.chkStepZ.setText("")
    self.chkStepZ.setObjectName("chkStepZ")
    self.horizontalLayout_2.addWidget(self.chkStepZ)
    self.chkStepA = QtWidgets.QCheckBox(self.tab_1)
    self.chkStepA.setLayoutDirection(QtCore.Qt.RightToLeft)
    self.chkStepA.setText("")
    self.chkStepA.setObjectName("chkStepA")
    self.horizontalLayout_2.addWidget(self.chkStepA)
    self.chkStepB = QtWidgets.QCheckBox(self.tab_1)
    self.chkStepB.setLayoutDirection(QtCore.Qt.RightToLeft)
    self.chkStepB.setText("")
    self.chkStepB.setObjectName("chkStepB")
    self.horizontalLayout_2.addWidget(self.chkStepB)
    self.chkStepC = QtWidgets.QCheckBox(self.tab_1)
    self.chkStepC.setEnabled(False)
    self.chkStepC.setLayoutDirection(QtCore.Qt.RightToLeft)
    self.chkStepC.setText("")
    self.chkStepC.setObjectName("chkStepC")
    self.horizontalLayout_2.addWidget(self.chkStepC)
    self.lneStepValue = QtWidgets.QLineEdit(self.tab_1)
    self.lneStepValue.setMinimumSize(QtCore.QSize(31, 19))
    self.lneStepValue.setMaximumSize(QtCore.QSize(31, 19))
    self.lneStepValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lneStepValue.setObjectName("lneStepValue")
    self.horizontalLayout_2.addWidget(self.lneStepValue)
    self.verticalLayout_15.addLayout(self.horizontalLayout_2)
    self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_3.setSpacing(3)
    self.horizontalLayout_3.setObjectName("horizontalLayout_3")
    self.chkDirX = QtWidgets.QCheckBox(self.tab_1)
    self.chkDirX.setLayoutDirection(QtCore.Qt.RightToLeft)
    self.chkDirX.setText("")
    self.chkDirX.setObjectName("chkDirX")
    self.horizontalLayout_3.addWidget(self.chkDirX)
    self.chkDirY = QtWidgets.QCheckBox(self.tab_1)
    self.chkDirY.setLayoutDirection(QtCore.Qt.RightToLeft)
    self.chkDirY.setText("")
    self.chkDirY.setObjectName("chkDirY")
    self.horizontalLayout_3.addWidget(self.chkDirY)
    self.chkDirZ = QtWidgets.QCheckBox(self.tab_1)
    self.chkDirZ.setLayoutDirection(QtCore.Qt.RightToLeft)
    self.chkDirZ.setText("")
    self.chkDirZ.setObjectName("chkDirZ")
    self.horizontalLayout_3.addWidget(self.chkDirZ)
    self.chkDirA = QtWidgets.QCheckBox(self.tab_1)
    self.chkDirA.setLayoutDirection(QtCore.Qt.RightToLeft)
    self.chkDirA.setText("")
    self.chkDirA.setObjectName("chkDirA")
    self.horizontalLayout_3.addWidget(self.chkDirA)
    self.chkDirB = QtWidgets.QCheckBox(self.tab_1)
    self.chkDirB.setLayoutDirection(QtCore.Qt.RightToLeft)
    self.chkDirB.setText("")
    self.chkDirB.setObjectName("chkDirB")
    self.horizontalLayout_3.addWidget(self.chkDirB)
    self.chkDirC = QtWidgets.QCheckBox(self.tab_1)
    self.chkDirC.setEnabled(False)
    self.chkDirC.setLayoutDirection(QtCore.Qt.RightToLeft)
    self.chkDirC.setText("")
    self.chkDirC.setObjectName("chkDirC")
    self.horizontalLayout_3.addWidget(self.chkDirC)
    self.lneDirValue = QtWidgets.QLineEdit(self.tab_1)
    self.lneDirValue.setMinimumSize(QtCore.QSize(31, 19))
    self.lneDirValue.setMaximumSize(QtCore.QSize(31, 19))
    self.lneDirValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lneDirValue.setObjectName("lneDirValue")
    self.horizontalLayout_3.addWidget(self.lneDirValue)
    self.verticalLayout_15.addLayout(self.horizontalLayout_3)
    self.checkBox = QtWidgets.QCheckBox(self.tab_1)
    self.checkBox.setObjectName("checkBox")
    self.verticalLayout_15.addWidget(self.checkBox)
    self.checkBox_2 = QtWidgets.QCheckBox(self.tab_1)
    self.checkBox_2.setObjectName("checkBox_2")
    self.verticalLayout_15.addWidget(self.checkBox_2)
    self.checkBox_3 = QtWidgets.QCheckBox(self.tab_1)
    self.checkBox_3.setObjectName("checkBox_3")
    self.verticalLayout_15.addWidget(self.checkBox_3)
    self.horizontalLayout_15.addLayout(self.verticalLayout_15)
    self.gridLayout_6.addLayout(self.horizontalLayout_15, 1, 1, 1, 1)
    spacerItem2 = QtWidgets.QSpacerItem(110, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.gridLayout_6.addItem(spacerItem2, 1, 2, 1, 1)
    spacerItem3 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.gridLayout_6.addItem(spacerItem3, 2, 1, 1, 1)
    self.tabWidget.addTab(self.tab_1, "")
    self.tab_2 = QtWidgets.QWidget()
    self.tab_2.setObjectName("tab_2")
    self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
    self.gridLayout_5.setObjectName("gridLayout_5")
    spacerItem4 = QtWidgets.QSpacerItem(20, 51, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.gridLayout_5.addItem(spacerItem4, 0, 1, 1, 1)
    spacerItem5 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.gridLayout_5.addItem(spacerItem5, 1, 0, 1, 1)
    self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_14.setObjectName("horizontalLayout_14")
    self.verticalLayout_13 = QtWidgets.QVBoxLayout()
    self.verticalLayout_13.setObjectName("verticalLayout_13")
    self.label_16 = QtWidgets.QLabel(self.tab_2)
    self.label_16.setObjectName("label_16")
    self.verticalLayout_13.addWidget(self.label_16)
    self.label_17 = QtWidgets.QLabel(self.tab_2)
    self.label_17.setObjectName("label_17")
    self.verticalLayout_13.addWidget(self.label_17)
    self.label_18 = QtWidgets.QLabel(self.tab_2)
    self.label_18.setObjectName("label_18")
    self.verticalLayout_13.addWidget(self.label_18)
    self.label_19 = QtWidgets.QLabel(self.tab_2)
    self.label_19.setObjectName("label_19")
    self.verticalLayout_13.addWidget(self.label_19)
    self.horizontalLayout_14.addLayout(self.verticalLayout_13)
    self.verticalLayout_14 = QtWidgets.QVBoxLayout()
    self.verticalLayout_14.setObjectName("verticalLayout_14")
    self.lineEdit = QtWidgets.QLineEdit(self.tab_2)
    self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lineEdit.setReadOnly(True)
    self.lineEdit.setObjectName("lineEdit")
    self.verticalLayout_14.addWidget(self.lineEdit)
    self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.tab_2)
    self.doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.doubleSpinBox.setDecimals(3)
    self.doubleSpinBox.setSingleStep(0.01)
    self.doubleSpinBox.setObjectName("doubleSpinBox")
    self.verticalLayout_14.addWidget(self.doubleSpinBox)
    self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.tab_2)
    self.doubleSpinBox_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.doubleSpinBox_2.setDecimals(3)
    self.doubleSpinBox_2.setSingleStep(0.01)
    self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
    self.verticalLayout_14.addWidget(self.doubleSpinBox_2)
    self.checkBox_4 = QtWidgets.QCheckBox(self.tab_2)
    self.checkBox_4.setObjectName("checkBox_4")
    self.verticalLayout_14.addWidget(self.checkBox_4)
    self.horizontalLayout_14.addLayout(self.verticalLayout_14)
    self.gridLayout_5.addLayout(self.horizontalLayout_14, 1, 1, 1, 1)
    spacerItem6 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.gridLayout_5.addItem(spacerItem6, 1, 2, 1, 1)
    spacerItem7 = QtWidgets.QSpacerItem(20, 51, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.gridLayout_5.addItem(spacerItem7, 2, 1, 1, 1)
    self.tabWidget.addTab(self.tab_2, "")
    self.tab = QtWidgets.QWidget()
    self.tab.setObjectName("tab")
    self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
    self.gridLayout_4.setObjectName("gridLayout_4")
    spacerItem8 = QtWidgets.QSpacerItem(95, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.gridLayout_4.addItem(spacerItem8, 0, 0, 1, 1)
    self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_13.setObjectName("horizontalLayout_13")
    self.verticalLayout_12 = QtWidgets.QVBoxLayout()
    self.verticalLayout_12.setObjectName("verticalLayout_12")
    self.label_20 = QtWidgets.QLabel(self.tab)
    self.label_20.setObjectName("label_20")
    self.verticalLayout_12.addWidget(self.label_20)
    self.label_21 = QtWidgets.QLabel(self.tab)
    self.label_21.setObjectName("label_21")
    self.verticalLayout_12.addWidget(self.label_21)
    self.label_22 = QtWidgets.QLabel(self.tab)
    self.label_22.setObjectName("label_22")
    self.verticalLayout_12.addWidget(self.label_22)
    self.label_31 = QtWidgets.QLabel(self.tab)
    self.label_31.setText("")
    self.label_31.setObjectName("label_31")
    self.verticalLayout_12.addWidget(self.label_31)
    self.label_23 = QtWidgets.QLabel(self.tab)
    self.label_23.setObjectName("label_23")
    self.verticalLayout_12.addWidget(self.label_23)
    self.label_32 = QtWidgets.QLabel(self.tab)
    self.label_32.setObjectName("label_32")
    self.verticalLayout_12.addWidget(self.label_32)
    self.label_33 = QtWidgets.QLabel(self.tab)
    self.label_33.setObjectName("label_33")
    self.verticalLayout_12.addWidget(self.label_33)
    self.label_34 = QtWidgets.QLabel(self.tab)
    self.label_34.setObjectName("label_34")
    self.verticalLayout_12.addWidget(self.label_34)
    self.label_35 = QtWidgets.QLabel(self.tab)
    self.label_35.setObjectName("label_35")
    self.verticalLayout_12.addWidget(self.label_35)
    self.horizontalLayout_13.addLayout(self.verticalLayout_12)
    self.verticalLayout_11 = QtWidgets.QVBoxLayout()
    self.verticalLayout_11.setSpacing(2)
    self.verticalLayout_11.setObjectName("verticalLayout_11")
    self.checkBox_5 = QtWidgets.QCheckBox(self.tab)
    self.checkBox_5.setObjectName("checkBox_5")
    self.verticalLayout_11.addWidget(self.checkBox_5)
    self.checkBox_6 = QtWidgets.QCheckBox(self.tab)
    self.checkBox_6.setObjectName("checkBox_6")
    self.verticalLayout_11.addWidget(self.checkBox_6)
    self.checkBox_7 = QtWidgets.QCheckBox(self.tab)
    self.checkBox_7.setObjectName("checkBox_7")
    self.verticalLayout_11.addWidget(self.checkBox_7)
    self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_5.setSpacing(3)
    self.horizontalLayout_5.setObjectName("horizontalLayout_5")
    self.label_24 = QtWidgets.QLabel(self.tab)
    self.label_24.setAlignment(QtCore.Qt.AlignCenter)
    self.label_24.setObjectName("label_24")
    self.horizontalLayout_5.addWidget(self.label_24)
    self.label_25 = QtWidgets.QLabel(self.tab)
    self.label_25.setAlignment(QtCore.Qt.AlignCenter)
    self.label_25.setObjectName("label_25")
    self.horizontalLayout_5.addWidget(self.label_25)
    self.label_26 = QtWidgets.QLabel(self.tab)
    self.label_26.setAlignment(QtCore.Qt.AlignCenter)
    self.label_26.setObjectName("label_26")
    self.horizontalLayout_5.addWidget(self.label_26)
    self.label_27 = QtWidgets.QLabel(self.tab)
    self.label_27.setAlignment(QtCore.Qt.AlignCenter)
    self.label_27.setObjectName("label_27")
    self.horizontalLayout_5.addWidget(self.label_27)
    self.label_28 = QtWidgets.QLabel(self.tab)
    self.label_28.setAlignment(QtCore.Qt.AlignCenter)
    self.label_28.setObjectName("label_28")
    self.horizontalLayout_5.addWidget(self.label_28)
    self.label_29 = QtWidgets.QLabel(self.tab)
    self.label_29.setAlignment(QtCore.Qt.AlignCenter)
    self.label_29.setObjectName("label_29")
    self.horizontalLayout_5.addWidget(self.label_29)
    self.label_30 = QtWidgets.QLabel(self.tab)
    self.label_30.setAlignment(QtCore.Qt.AlignCenter)
    self.label_30.setObjectName("label_30")
    self.horizontalLayout_5.addWidget(self.label_30)
    self.verticalLayout_11.addLayout(self.horizontalLayout_5)
    self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_6.setSpacing(3)
    self.horizontalLayout_6.setObjectName("horizontalLayout_6")
    self.chkStepX_2 = QtWidgets.QCheckBox(self.tab)
    self.chkStepX_2.setLayoutDirection(QtCore.Qt.RightToLeft)
    self.chkStepX_2.setText("")
    self.chkStepX_2.setObjectName("chkStepX_2")
    self.horizontalLayout_6.addWidget(self.chkStepX_2)
    self.chkStepY_2 = QtWidgets.QCheckBox(self.tab)
    self.chkStepY_2.setLayoutDirection(QtCore.Qt.RightToLeft)
    self.chkStepY_2.setText("")
    self.chkStepY_2.setObjectName("chkStepY_2")
    self.horizontalLayout_6.addWidget(self.chkStepY_2)
    self.chkStepZ_2 = QtWidgets.QCheckBox(self.tab)
    self.chkStepZ_2.setLayoutDirection(QtCore.Qt.RightToLeft)
    self.chkStepZ_2.setText("")
    self.chkStepZ_2.setObjectName("chkStepZ_2")
    self.horizontalLayout_6.addWidget(self.chkStepZ_2)
    self.chkStepA_2 = QtWidgets.QCheckBox(self.tab)
    self.chkStepA_2.setLayoutDirection(QtCore.Qt.RightToLeft)
    self.chkStepA_2.setText("")
    self.chkStepA_2.setObjectName("chkStepA_2")
    self.horizontalLayout_6.addWidget(self.chkStepA_2)
    self.chkStepB_2 = QtWidgets.QCheckBox(self.tab)
    self.chkStepB_2.setLayoutDirection(QtCore.Qt.RightToLeft)
    self.chkStepB_2.setText("")
    self.chkStepB_2.setObjectName("chkStepB_2")
    self.horizontalLayout_6.addWidget(self.chkStepB_2)
    self.chkStepC_2 = QtWidgets.QCheckBox(self.tab)
    self.chkStepC_2.setEnabled(False)
    self.chkStepC_2.setLayoutDirection(QtCore.Qt.RightToLeft)
    self.chkStepC_2.setText("")
    self.chkStepC_2.setObjectName("chkStepC_2")
    self.horizontalLayout_6.addWidget(self.chkStepC_2)
    self.lneStepValue_2 = QtWidgets.QLineEdit(self.tab)
    self.lneStepValue_2.setMinimumSize(QtCore.QSize(31, 19))
    self.lneStepValue_2.setMaximumSize(QtCore.QSize(31, 19))
    self.lneStepValue_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lneStepValue_2.setObjectName("lneStepValue_2")
    self.horizontalLayout_6.addWidget(self.lneStepValue_2)
    self.verticalLayout_11.addLayout(self.horizontalLayout_6)
    self.spinBox_3 = QtWidgets.QSpinBox(self.tab)
    self.spinBox_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.spinBox_3.setMaximum(99999)
    self.spinBox_3.setObjectName("spinBox_3")
    self.verticalLayout_11.addWidget(self.spinBox_3)
    self.spinBox_4 = QtWidgets.QSpinBox(self.tab)
    self.spinBox_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.spinBox_4.setMaximum(99999)
    self.spinBox_4.setObjectName("spinBox_4")
    self.verticalLayout_11.addWidget(self.spinBox_4)
    self.spinBox_5 = QtWidgets.QSpinBox(self.tab)
    self.spinBox_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.spinBox_5.setMaximum(99999)
    self.spinBox_5.setObjectName("spinBox_5")
    self.verticalLayout_11.addWidget(self.spinBox_5)
    self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.tab)
    self.doubleSpinBox_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
    self.verticalLayout_11.addWidget(self.doubleSpinBox_3)
    self.horizontalLayout_13.addLayout(self.verticalLayout_11)
    self.gridLayout_4.addLayout(self.horizontalLayout_13, 0, 1, 1, 1)
    spacerItem9 = QtWidgets.QSpacerItem(95, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.gridLayout_4.addItem(spacerItem9, 0, 2, 1, 1)
    self.tabWidget.addTab(self.tab, "")
    self.tab_3 = QtWidgets.QWidget()
    self.tab_3.setObjectName("tab_3")
    self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_3)
    self.gridLayout_3.setObjectName("gridLayout_3")
    spacerItem10 = QtWidgets.QSpacerItem(20, 67, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.gridLayout_3.addItem(spacerItem10, 0, 1, 1, 1)
    spacerItem11 = QtWidgets.QSpacerItem(110, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.gridLayout_3.addItem(spacerItem11, 1, 0, 1, 1)
    self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_12.setObjectName("horizontalLayout_12")
    self.verticalLayout_9 = QtWidgets.QVBoxLayout()
    self.verticalLayout_9.setObjectName("verticalLayout_9")
    self.label_36 = QtWidgets.QLabel(self.tab_3)
    self.label_36.setObjectName("label_36")
    self.verticalLayout_9.addWidget(self.label_36)
    self.label_37 = QtWidgets.QLabel(self.tab_3)
    self.label_37.setObjectName("label_37")
    self.verticalLayout_9.addWidget(self.label_37)
    self.label_38 = QtWidgets.QLabel(self.tab_3)
    self.label_38.setObjectName("label_38")
    self.verticalLayout_9.addWidget(self.label_38)
    self.horizontalLayout_12.addLayout(self.verticalLayout_9)
    self.verticalLayout_10 = QtWidgets.QVBoxLayout()
    self.verticalLayout_10.setObjectName("verticalLayout_10")
    self.spinBox_6 = QtWidgets.QSpinBox(self.tab_3)
    self.spinBox_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.spinBox_6.setMaximum(999999)
    self.spinBox_6.setObjectName("spinBox_6")
    self.verticalLayout_10.addWidget(self.spinBox_6)
    self.spinBox_7 = QtWidgets.QSpinBox(self.tab_3)
    self.spinBox_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.spinBox_7.setMaximum(999999)
    self.spinBox_7.setObjectName("spinBox_7")
    self.verticalLayout_10.addWidget(self.spinBox_7)
    self.checkBox_8 = QtWidgets.QCheckBox(self.tab_3)
    self.checkBox_8.setObjectName("checkBox_8")
    self.verticalLayout_10.addWidget(self.checkBox_8)
    self.horizontalLayout_12.addLayout(self.verticalLayout_10)
    self.gridLayout_3.addLayout(self.horizontalLayout_12, 1, 1, 1, 1)
    spacerItem12 = QtWidgets.QSpacerItem(109, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.gridLayout_3.addItem(spacerItem12, 1, 2, 1, 1)
    spacerItem13 = QtWidgets.QSpacerItem(20, 66, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.gridLayout_3.addItem(spacerItem13, 2, 1, 1, 1)
    self.tabWidget.addTab(self.tab_3, "")
    self.tab_4 = QtWidgets.QWidget()
    self.tab_4.setObjectName("tab_4")
    self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_4)
    self.gridLayout_2.setObjectName("gridLayout_2")
    spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.gridLayout_2.addItem(spacerItem14, 2, 1, 1, 1)
    self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_11.setSpacing(12)
    self.horizontalLayout_11.setObjectName("horizontalLayout_11")
    self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_9.setObjectName("horizontalLayout_9")
    self.verticalLayout_5 = QtWidgets.QVBoxLayout()
    self.verticalLayout_5.setObjectName("verticalLayout_5")
    self.label_39 = QtWidgets.QLabel(self.tab_4)
    self.label_39.setObjectName("label_39")
    self.verticalLayout_5.addWidget(self.label_39)
    self.label_40 = QtWidgets.QLabel(self.tab_4)
    self.label_40.setObjectName("label_40")
    self.verticalLayout_5.addWidget(self.label_40)
    self.label_41 = QtWidgets.QLabel(self.tab_4)
    self.label_41.setObjectName("label_41")
    self.verticalLayout_5.addWidget(self.label_41)
    self.label_42 = QtWidgets.QLabel(self.tab_4)
    self.label_42.setObjectName("label_42")
    self.verticalLayout_5.addWidget(self.label_42)
    self.label_43 = QtWidgets.QLabel(self.tab_4)
    self.label_43.setObjectName("label_43")
    self.verticalLayout_5.addWidget(self.label_43)
    self.label_44 = QtWidgets.QLabel(self.tab_4)
    self.label_44.setEnabled(False)
    self.label_44.setObjectName("label_44")
    self.verticalLayout_5.addWidget(self.label_44)
    self.horizontalLayout_9.addLayout(self.verticalLayout_5)
    self.verticalLayout_6 = QtWidgets.QVBoxLayout()
    self.verticalLayout_6.setObjectName("verticalLayout_6")
    self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.tab_4)
    self.doubleSpinBox_4.setMinimumSize(QtCore.QSize(84, 0))
    self.doubleSpinBox_4.setMaximumSize(QtCore.QSize(84, 16777215))
    self.doubleSpinBox_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.doubleSpinBox_4.setMaximum(99999.0)
    self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
    self.verticalLayout_6.addWidget(self.doubleSpinBox_4)
    self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.tab_4)
    self.doubleSpinBox_5.setMinimumSize(QtCore.QSize(84, 0))
    self.doubleSpinBox_5.setMaximumSize(QtCore.QSize(84, 16777215))
    self.doubleSpinBox_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.doubleSpinBox_5.setMaximum(99999.0)
    self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
    self.verticalLayout_6.addWidget(self.doubleSpinBox_5)
    self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.tab_4)
    self.doubleSpinBox_6.setMinimumSize(QtCore.QSize(84, 0))
    self.doubleSpinBox_6.setMaximumSize(QtCore.QSize(84, 16777215))
    self.doubleSpinBox_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.doubleSpinBox_6.setMaximum(99999.0)
    self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
    self.verticalLayout_6.addWidget(self.doubleSpinBox_6)
    self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.tab_4)
    self.doubleSpinBox_7.setMinimumSize(QtCore.QSize(84, 0))
    self.doubleSpinBox_7.setMaximumSize(QtCore.QSize(84, 16777215))
    self.doubleSpinBox_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.doubleSpinBox_7.setMaximum(99999.0)
    self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
    self.verticalLayout_6.addWidget(self.doubleSpinBox_7)
    self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.tab_4)
    self.doubleSpinBox_8.setMinimumSize(QtCore.QSize(84, 0))
    self.doubleSpinBox_8.setMaximumSize(QtCore.QSize(84, 16777215))
    self.doubleSpinBox_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.doubleSpinBox_8.setMaximum(99999.0)
    self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
    self.verticalLayout_6.addWidget(self.doubleSpinBox_8)
    self.doubleSpinBox_9 = QtWidgets.QDoubleSpinBox(self.tab_4)
    self.doubleSpinBox_9.setEnabled(False)
    self.doubleSpinBox_9.setMinimumSize(QtCore.QSize(84, 0))
    self.doubleSpinBox_9.setMaximumSize(QtCore.QSize(84, 16777215))
    self.doubleSpinBox_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.doubleSpinBox_9.setMaximum(99999.0)
    self.doubleSpinBox_9.setObjectName("doubleSpinBox_9")
    self.verticalLayout_6.addWidget(self.doubleSpinBox_9)
    self.horizontalLayout_9.addLayout(self.verticalLayout_6)
    self.horizontalLayout_11.addLayout(self.horizontalLayout_9)
    self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_10.setObjectName("horizontalLayout_10")
    self.verticalLayout_7 = QtWidgets.QVBoxLayout()
    self.verticalLayout_7.setObjectName("verticalLayout_7")
    self.label_51 = QtWidgets.QLabel(self.tab_4)
    self.label_51.setObjectName("label_51")
    self.verticalLayout_7.addWidget(self.label_51)
    self.label_52 = QtWidgets.QLabel(self.tab_4)
    self.label_52.setObjectName("label_52")
    self.verticalLayout_7.addWidget(self.label_52)
    self.label_53 = QtWidgets.QLabel(self.tab_4)
    self.label_53.setObjectName("label_53")
    self.verticalLayout_7.addWidget(self.label_53)
    self.label_54 = QtWidgets.QLabel(self.tab_4)
    self.label_54.setObjectName("label_54")
    self.verticalLayout_7.addWidget(self.label_54)
    self.label_55 = QtWidgets.QLabel(self.tab_4)
    self.label_55.setObjectName("label_55")
    self.verticalLayout_7.addWidget(self.label_55)
    self.label_56 = QtWidgets.QLabel(self.tab_4)
    self.label_56.setEnabled(False)
    self.label_56.setObjectName("label_56")
    self.verticalLayout_7.addWidget(self.label_56)
    self.horizontalLayout_10.addLayout(self.verticalLayout_7)
    self.verticalLayout_8 = QtWidgets.QVBoxLayout()
    self.verticalLayout_8.setObjectName("verticalLayout_8")
    self.doubleSpinBox_18 = QtWidgets.QDoubleSpinBox(self.tab_4)
    self.doubleSpinBox_18.setMinimumSize(QtCore.QSize(84, 0))
    self.doubleSpinBox_18.setMaximumSize(QtCore.QSize(84, 16777215))
    self.doubleSpinBox_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.doubleSpinBox_18.setMaximum(99999.0)
    self.doubleSpinBox_18.setObjectName("doubleSpinBox_18")
    self.verticalLayout_8.addWidget(self.doubleSpinBox_18)
    self.doubleSpinBox_16 = QtWidgets.QDoubleSpinBox(self.tab_4)
    self.doubleSpinBox_16.setMinimumSize(QtCore.QSize(84, 0))
    self.doubleSpinBox_16.setMaximumSize(QtCore.QSize(84, 16777215))
    self.doubleSpinBox_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.doubleSpinBox_16.setMaximum(99999.0)
    self.doubleSpinBox_16.setObjectName("doubleSpinBox_16")
    self.verticalLayout_8.addWidget(self.doubleSpinBox_16)
    self.doubleSpinBox_21 = QtWidgets.QDoubleSpinBox(self.tab_4)
    self.doubleSpinBox_21.setMinimumSize(QtCore.QSize(84, 0))
    self.doubleSpinBox_21.setMaximumSize(QtCore.QSize(84, 16777215))
    self.doubleSpinBox_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.doubleSpinBox_21.setMaximum(99999.0)
    self.doubleSpinBox_21.setObjectName("doubleSpinBox_21")
    self.verticalLayout_8.addWidget(self.doubleSpinBox_21)
    self.doubleSpinBox_17 = QtWidgets.QDoubleSpinBox(self.tab_4)
    self.doubleSpinBox_17.setMinimumSize(QtCore.QSize(84, 0))
    self.doubleSpinBox_17.setMaximumSize(QtCore.QSize(84, 16777215))
    self.doubleSpinBox_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.doubleSpinBox_17.setMaximum(99999.0)
    self.doubleSpinBox_17.setObjectName("doubleSpinBox_17")
    self.verticalLayout_8.addWidget(self.doubleSpinBox_17)
    self.doubleSpinBox_19 = QtWidgets.QDoubleSpinBox(self.tab_4)
    self.doubleSpinBox_19.setMinimumSize(QtCore.QSize(84, 0))
    self.doubleSpinBox_19.setMaximumSize(QtCore.QSize(84, 16777215))
    self.doubleSpinBox_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.doubleSpinBox_19.setMaximum(99999.0)
    self.doubleSpinBox_19.setObjectName("doubleSpinBox_19")
    self.verticalLayout_8.addWidget(self.doubleSpinBox_19)
    self.doubleSpinBox_20 = QtWidgets.QDoubleSpinBox(self.tab_4)
    self.doubleSpinBox_20.setEnabled(False)
    self.doubleSpinBox_20.setMinimumSize(QtCore.QSize(84, 0))
    self.doubleSpinBox_20.setMaximumSize(QtCore.QSize(84, 16777215))
    self.doubleSpinBox_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.doubleSpinBox_20.setMaximum(99999.0)
    self.doubleSpinBox_20.setObjectName("doubleSpinBox_20")
    self.verticalLayout_8.addWidget(self.doubleSpinBox_20)
    self.horizontalLayout_10.addLayout(self.verticalLayout_8)
    self.horizontalLayout_11.addLayout(self.horizontalLayout_10)
    self.gridLayout_2.addLayout(self.horizontalLayout_11, 1, 1, 1, 1)
    spacerItem15 = QtWidgets.QSpacerItem(45, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.gridLayout_2.addItem(spacerItem15, 1, 0, 1, 1)
    spacerItem16 = QtWidgets.QSpacerItem(45, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.gridLayout_2.addItem(spacerItem16, 1, 2, 1, 1)
    spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.gridLayout_2.addItem(spacerItem17, 0, 1, 1, 1)
    self.tabWidget.addTab(self.tab_4, "")
    self.tab_5 = QtWidgets.QWidget()
    self.tab_5.setObjectName("tab_5")
    self.gridLayout = QtWidgets.QGridLayout(self.tab_5)
    self.gridLayout.setObjectName("gridLayout")
    self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_8.setSpacing(12)
    self.horizontalLayout_8.setObjectName("horizontalLayout_8")
    self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_4.setSpacing(3)
    self.horizontalLayout_4.setObjectName("horizontalLayout_4")
    self.verticalLayout = QtWidgets.QVBoxLayout()
    self.verticalLayout.setObjectName("verticalLayout")
    self.label_45 = QtWidgets.QLabel(self.tab_5)
    self.label_45.setObjectName("label_45")
    self.verticalLayout.addWidget(self.label_45)
    self.label_46 = QtWidgets.QLabel(self.tab_5)
    self.label_46.setObjectName("label_46")
    self.verticalLayout.addWidget(self.label_46)
    self.label_47 = QtWidgets.QLabel(self.tab_5)
    self.label_47.setObjectName("label_47")
    self.verticalLayout.addWidget(self.label_47)
    self.label_48 = QtWidgets.QLabel(self.tab_5)
    self.label_48.setObjectName("label_48")
    self.verticalLayout.addWidget(self.label_48)
    self.label_49 = QtWidgets.QLabel(self.tab_5)
    self.label_49.setObjectName("label_49")
    self.verticalLayout.addWidget(self.label_49)
    self.label_50 = QtWidgets.QLabel(self.tab_5)
    self.label_50.setEnabled(False)
    self.label_50.setObjectName("label_50")
    self.verticalLayout.addWidget(self.label_50)
    self.horizontalLayout_4.addLayout(self.verticalLayout)
    self.verticalLayout_2 = QtWidgets.QVBoxLayout()
    self.verticalLayout_2.setObjectName("verticalLayout_2")
    self.doubleSpinBox_12 = QtWidgets.QDoubleSpinBox(self.tab_5)
    self.doubleSpinBox_12.setMinimumSize(QtCore.QSize(84, 0))
    self.doubleSpinBox_12.setMaximumSize(QtCore.QSize(84, 16777215))
    self.doubleSpinBox_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.doubleSpinBox_12.setMaximum(99999.0)
    self.doubleSpinBox_12.setProperty("value", 5000.0)
    self.doubleSpinBox_12.setObjectName("doubleSpinBox_12")
    self.verticalLayout_2.addWidget(self.doubleSpinBox_12)
    self.doubleSpinBox_10 = QtWidgets.QDoubleSpinBox(self.tab_5)
    self.doubleSpinBox_10.setMinimumSize(QtCore.QSize(84, 0))
    self.doubleSpinBox_10.setMaximumSize(QtCore.QSize(84, 16777215))
    self.doubleSpinBox_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.doubleSpinBox_10.setMaximum(99999.0)
    self.doubleSpinBox_10.setObjectName("doubleSpinBox_10")
    self.verticalLayout_2.addWidget(self.doubleSpinBox_10)
    self.doubleSpinBox_15 = QtWidgets.QDoubleSpinBox(self.tab_5)
    self.doubleSpinBox_15.setMinimumSize(QtCore.QSize(84, 0))
    self.doubleSpinBox_15.setMaximumSize(QtCore.QSize(84, 16777215))
    self.doubleSpinBox_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.doubleSpinBox_15.setMaximum(99999.0)
    self.doubleSpinBox_15.setObjectName("doubleSpinBox_15")
    self.verticalLayout_2.addWidget(self.doubleSpinBox_15)
    self.doubleSpinBox_11 = QtWidgets.QDoubleSpinBox(self.tab_5)
    self.doubleSpinBox_11.setMinimumSize(QtCore.QSize(84, 0))
    self.doubleSpinBox_11.setMaximumSize(QtCore.QSize(84, 16777215))
    self.doubleSpinBox_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.doubleSpinBox_11.setMaximum(99999.0)
    self.doubleSpinBox_11.setObjectName("doubleSpinBox_11")
    self.verticalLayout_2.addWidget(self.doubleSpinBox_11)
    self.doubleSpinBox_13 = QtWidgets.QDoubleSpinBox(self.tab_5)
    self.doubleSpinBox_13.setMinimumSize(QtCore.QSize(84, 0))
    self.doubleSpinBox_13.setMaximumSize(QtCore.QSize(84, 16777215))
    self.doubleSpinBox_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.doubleSpinBox_13.setMaximum(99999.0)
    self.doubleSpinBox_13.setObjectName("doubleSpinBox_13")
    self.verticalLayout_2.addWidget(self.doubleSpinBox_13)
    self.doubleSpinBox_14 = QtWidgets.QDoubleSpinBox(self.tab_5)
    self.doubleSpinBox_14.setEnabled(False)
    self.doubleSpinBox_14.setMinimumSize(QtCore.QSize(84, 0))
    self.doubleSpinBox_14.setMaximumSize(QtCore.QSize(84, 16777215))
    self.doubleSpinBox_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.doubleSpinBox_14.setMaximum(99999.0)
    self.doubleSpinBox_14.setObjectName("doubleSpinBox_14")
    self.verticalLayout_2.addWidget(self.doubleSpinBox_14)
    self.horizontalLayout_4.addLayout(self.verticalLayout_2)
    self.horizontalLayout_8.addLayout(self.horizontalLayout_4)
    self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_7.setSpacing(3)
    self.horizontalLayout_7.setObjectName("horizontalLayout_7")
    self.verticalLayout_3 = QtWidgets.QVBoxLayout()
    self.verticalLayout_3.setObjectName("verticalLayout_3")
    self.label_57 = QtWidgets.QLabel(self.tab_5)
    self.label_57.setObjectName("label_57")
    self.verticalLayout_3.addWidget(self.label_57)
    self.label_58 = QtWidgets.QLabel(self.tab_5)
    self.label_58.setObjectName("label_58")
    self.verticalLayout_3.addWidget(self.label_58)
    self.label_59 = QtWidgets.QLabel(self.tab_5)
    self.label_59.setObjectName("label_59")
    self.verticalLayout_3.addWidget(self.label_59)
    self.label_60 = QtWidgets.QLabel(self.tab_5)
    self.label_60.setObjectName("label_60")
    self.verticalLayout_3.addWidget(self.label_60)
    self.label_61 = QtWidgets.QLabel(self.tab_5)
    self.label_61.setObjectName("label_61")
    self.verticalLayout_3.addWidget(self.label_61)
    self.label_62 = QtWidgets.QLabel(self.tab_5)
    self.label_62.setEnabled(False)
    self.label_62.setObjectName("label_62")
    self.verticalLayout_3.addWidget(self.label_62)
    self.horizontalLayout_7.addLayout(self.verticalLayout_3)
    self.verticalLayout_4 = QtWidgets.QVBoxLayout()
    self.verticalLayout_4.setObjectName("verticalLayout_4")
    self.doubleSpinBox_23 = QtWidgets.QDoubleSpinBox(self.tab_5)
    self.doubleSpinBox_23.setMinimumSize(QtCore.QSize(84, 0))
    self.doubleSpinBox_23.setMaximumSize(QtCore.QSize(84, 16777215))
    self.doubleSpinBox_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.doubleSpinBox_23.setMaximum(99999.0)
    self.doubleSpinBox_23.setObjectName("doubleSpinBox_23")
    self.verticalLayout_4.addWidget(self.doubleSpinBox_23)
    self.doubleSpinBox_26 = QtWidgets.QDoubleSpinBox(self.tab_5)
    self.doubleSpinBox_26.setMinimumSize(QtCore.QSize(84, 0))
    self.doubleSpinBox_26.setMaximumSize(QtCore.QSize(84, 16777215))
    self.doubleSpinBox_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.doubleSpinBox_26.setMaximum(99999.0)
    self.doubleSpinBox_26.setObjectName("doubleSpinBox_26")
    self.verticalLayout_4.addWidget(self.doubleSpinBox_26)
    self.doubleSpinBox_27 = QtWidgets.QDoubleSpinBox(self.tab_5)
    self.doubleSpinBox_27.setMinimumSize(QtCore.QSize(84, 0))
    self.doubleSpinBox_27.setMaximumSize(QtCore.QSize(84, 16777215))
    self.doubleSpinBox_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.doubleSpinBox_27.setMaximum(99999.0)
    self.doubleSpinBox_27.setObjectName("doubleSpinBox_27")
    self.verticalLayout_4.addWidget(self.doubleSpinBox_27)
    self.doubleSpinBox_22 = QtWidgets.QDoubleSpinBox(self.tab_5)
    self.doubleSpinBox_22.setMinimumSize(QtCore.QSize(84, 0))
    self.doubleSpinBox_22.setMaximumSize(QtCore.QSize(84, 16777215))
    self.doubleSpinBox_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.doubleSpinBox_22.setMaximum(99999.0)
    self.doubleSpinBox_22.setObjectName("doubleSpinBox_22")
    self.verticalLayout_4.addWidget(self.doubleSpinBox_22)
    self.doubleSpinBox_24 = QtWidgets.QDoubleSpinBox(self.tab_5)
    self.doubleSpinBox_24.setMinimumSize(QtCore.QSize(84, 0))
    self.doubleSpinBox_24.setMaximumSize(QtCore.QSize(84, 16777215))
    self.doubleSpinBox_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.doubleSpinBox_24.setMaximum(99999.0)
    self.doubleSpinBox_24.setObjectName("doubleSpinBox_24")
    self.verticalLayout_4.addWidget(self.doubleSpinBox_24)
    self.doubleSpinBox_25 = QtWidgets.QDoubleSpinBox(self.tab_5)
    self.doubleSpinBox_25.setEnabled(False)
    self.doubleSpinBox_25.setMinimumSize(QtCore.QSize(84, 0))
    self.doubleSpinBox_25.setMaximumSize(QtCore.QSize(84, 16777215))
    self.doubleSpinBox_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.doubleSpinBox_25.setMaximum(99999.0)
    self.doubleSpinBox_25.setObjectName("doubleSpinBox_25")
    self.verticalLayout_4.addWidget(self.doubleSpinBox_25)
    self.horizontalLayout_7.addLayout(self.verticalLayout_4)
    self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
    self.gridLayout.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
    spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.gridLayout.addItem(spacerItem18, 2, 0, 1, 1)
    spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.gridLayout.addItem(spacerItem19, 0, 0, 1, 1)
    self.tabWidget.addTab(self.tab_5, "")
    self.verticalLayout_17.addWidget(self.tabWidget)
    self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_16.setObjectName("horizontalLayout_16")
    spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.horizontalLayout_16.addItem(spacerItem20)
    self.buttonBox = QtWidgets.QDialogButtonBox(dlgConfig)
    self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
    self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.RestoreDefaults)
    self.buttonBox.setObjectName("buttonBox")
    self.horizontalLayout_16.addWidget(self.buttonBox)
    self.verticalLayout_17.addLayout(self.horizontalLayout_16)

    self.retranslateUi(dlgConfig)
    self.tabWidget.setCurrentIndex(5)
    self.buttonBox.accepted.connect(dlgConfig.accept)
    self.buttonBox.rejected.connect(dlgConfig.reject)
    QtCore.QMetaObject.connectSlotsByName(dlgConfig)

  def retranslateUi(self, dlgConfig):
    _translate = QtCore.QCoreApplication.translate
    dlgConfig.setWindowTitle(_translate("dlgConfig", "Configuration Grbl"))
    self.label.setText(_translate("dlgConfig", "Step pulse, microseconds ($0)"))
    self.label_2.setText(_translate("dlgConfig", "Step idle delay, milliseconds ($1)"))
    self.label_3.setText(_translate("dlgConfig", "Step port invert, mask ($2)"))
    self.label_4.setText(_translate("dlgConfig", "Direction port invert, mask ($3)"))
    self.label_5.setText(_translate("dlgConfig", "Step enable invert, boolean ($4)"))
    self.label_14.setText(_translate("dlgConfig", "Limit pins invert, boolean ($5)"))
    self.label_15.setText(_translate("dlgConfig", "Probe pin invert, boolean ($6)"))
    self.label_6.setText(_translate("dlgConfig", "X"))
    self.label_7.setText(_translate("dlgConfig", "Y"))
    self.label_8.setText(_translate("dlgConfig", "Z"))
    self.label_9.setText(_translate("dlgConfig", "A"))
    self.label_10.setText(_translate("dlgConfig", "B"))
    self.label_11.setText(_translate("dlgConfig", "C"))
    self.label_12.setText(_translate("dlgConfig", "Val"))
    self.lneStepValue.setText(_translate("dlgConfig", "0"))
    self.lneDirValue.setText(_translate("dlgConfig", "0"))
    self.checkBox.setText(_translate("dlgConfig", "False"))
    self.checkBox_2.setText(_translate("dlgConfig", "False"))
    self.checkBox_3.setText(_translate("dlgConfig", "False"))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("dlgConfig", "Matériel"))
    self.label_16.setText(_translate("dlgConfig", "Status report, mask ($10)"))
    self.label_17.setText(_translate("dlgConfig", "Junction deviation, mm ($11)"))
    self.label_18.setText(_translate("dlgConfig", "Arc tolerance, mm ($12)"))
    self.label_19.setText(_translate("dlgConfig", "Report inches, boolean ($13)"))
    self.lineEdit.setText(_translate("dlgConfig", "255"))
    self.checkBox_4.setText(_translate("dlgConfig", "False"))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("dlgConfig", "Unité"))
    self.label_20.setText(_translate("dlgConfig", "Soft limits, boolean ($20)"))
    self.label_21.setText(_translate("dlgConfig", "Hard limits, boolean ($21)"))
    self.label_22.setText(_translate("dlgConfig", "Homing cycle, boolean ($22)"))
    self.label_23.setText(_translate("dlgConfig", "Homing dir invert, mask ($23)"))
    self.label_32.setText(_translate("dlgConfig", "Homing feed, mm/min ($24)"))
    self.label_33.setText(_translate("dlgConfig", "Homing seek, mm/min ($25)"))
    self.label_34.setText(_translate("dlgConfig", "Homing debounce, milliseconds ($26)"))
    self.label_35.setText(_translate("dlgConfig", "Homing pull-off, mm ($27)"))
    self.checkBox_5.setText(_translate("dlgConfig", "False"))
    self.checkBox_6.setText(_translate("dlgConfig", "False"))
    self.checkBox_7.setText(_translate("dlgConfig", "False"))
    self.label_24.setText(_translate("dlgConfig", "X"))
    self.label_25.setText(_translate("dlgConfig", "Y"))
    self.label_26.setText(_translate("dlgConfig", "Z"))
    self.label_27.setText(_translate("dlgConfig", "A"))
    self.label_28.setText(_translate("dlgConfig", "B"))
    self.label_29.setText(_translate("dlgConfig", "C"))
    self.label_30.setText(_translate("dlgConfig", "Val"))
    self.lneStepValue_2.setText(_translate("dlgConfig", "0"))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("dlgConfig", "Limites"))
    self.label_36.setText(_translate("dlgConfig", "Max spindle speed, RPM or laser power ($30)"))
    self.label_37.setText(_translate("dlgConfig", "Min spindle speed, RPM ($31)"))
    self.label_38.setText(_translate("dlgConfig", "Laser mode, boolean (32)"))
    self.checkBox_8.setText(_translate("dlgConfig", "False"))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("dlgConfig", "Broche"))
    self.label_39.setText(_translate("dlgConfig", "X steps/mm ($100)"))
    self.label_40.setText(_translate("dlgConfig", "Y steps/mm ($101)"))
    self.label_41.setText(_translate("dlgConfig", "Z steps/mm ($102)"))
    self.label_42.setText(_translate("dlgConfig", "A steps/unit ($103)"))
    self.label_43.setText(_translate("dlgConfig", "B steps/unit ($104)"))
    self.label_44.setText(_translate("dlgConfig", "C steps/unit ($105)"))
    self.label_51.setText(_translate("dlgConfig", "X Max travel, mm ($130)"))
    self.label_52.setText(_translate("dlgConfig", "Y Max travel, mm ($131)"))
    self.label_53.setText(_translate("dlgConfig", "Z Max travel, mm ($132)"))
    self.label_54.setText(_translate("dlgConfig", "A Max travel, unit ($133)"))
    self.label_55.setText(_translate("dlgConfig", "B Max travel, unit ($134)"))
    self.label_56.setText(_translate("dlgConfig", "C Max travel, unit ($135)"))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("dlgConfig", "Courses"))
    self.label_45.setText(_translate("dlgConfig", "X Max rate, mm/min ($110)"))
    self.label_46.setText(_translate("dlgConfig", "Y Max rate, mm/min ($111)"))
    self.label_47.setText(_translate("dlgConfig", "Z Max rate, mm/min ($112)"))
    self.label_48.setText(_translate("dlgConfig", "A Max rate, unit/min ($113)"))
    self.label_49.setText(_translate("dlgConfig", "B Max rate, unit/min ($114)"))
    self.label_50.setText(_translate("dlgConfig", "C Max rate, unit/min ($115)"))
    self.label_57.setText(_translate("dlgConfig", "X Acceleration, mm/sec^2 ($120)"))
    self.label_58.setText(_translate("dlgConfig", "Y Acceleration, mm/sec^2 ($121)"))
    self.label_59.setText(_translate("dlgConfig", "Z Acceleration, mm/sec^2 ($122)"))
    self.label_60.setText(_translate("dlgConfig", "A Acceleration, unit/sec^2 ($123)"))
    self.label_61.setText(_translate("dlgConfig", "B Acceleration, unit/sec^2 ($124)"))
    self.label_62.setText(_translate("dlgConfig", "C Acceleration, unit/sec^2 ($125)"))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("dlgConfig", "Vitesses"))

import cn5X_rc
