# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgConfig.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlgConfig(object):
  def setupUi(self, dlgConfig):
    dlgConfig.setObjectName("dlgConfig")
    dlgConfig.resize(624, 318)
    dlgConfig.setMinimumSize(QtCore.QSize(624, 318))
    dlgConfig.setMaximumSize(QtCore.QSize(624, 318))
    icon = QtGui.QIcon()
    icon.addPixmap(QtGui.QPixmap(":/cn5X/images/XYZAB.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    dlgConfig.setWindowIcon(icon)
    dlgConfig.setModal(True)
    self.verticalLayout_17 = QtWidgets.QVBoxLayout(dlgConfig)
    self.verticalLayout_17.setContentsMargins(4, 4, 4, 4)
    self.verticalLayout_17.setSpacing(4)
    self.verticalLayout_17.setObjectName("verticalLayout_17")
    self.tabWidget = QtWidgets.QTabWidget(dlgConfig)
    self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
    self.tabWidget.setObjectName("tabWidget")
    self.tab_0 = QtWidgets.QWidget()
    self.tab_0.setObjectName("tab_0")
    self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_0)
    self.gridLayout_7.setObjectName("gridLayout_7")
    spacerItem = QtWidgets.QSpacerItem(20, 41, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.gridLayout_7.addItem(spacerItem, 0, 1, 1, 1)
    spacerItem1 = QtWidgets.QSpacerItem(196, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.gridLayout_7.addItem(spacerItem1, 2, 0, 1, 1)
    self.verticalLayout_25 = QtWidgets.QVBoxLayout()
    self.verticalLayout_25.setObjectName("verticalLayout_25")
    self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_18.setSpacing(4)
    self.horizontalLayout_18.setObjectName("horizontalLayout_18")
    self.verticalLayout_18 = QtWidgets.QVBoxLayout()
    self.verticalLayout_18.setSpacing(4)
    self.verticalLayout_18.setObjectName("verticalLayout_18")
    self.lblInformations = QtWidgets.QLabel(self.tab_0)
    font = QtGui.QFont()
    font.setPointSize(14)
    self.lblInformations.setFont(font)
    self.lblInformations.setObjectName("lblInformations")
    self.verticalLayout_18.addWidget(self.lblInformations)
    self.lblInformations_3 = QtWidgets.QLabel(self.tab_0)
    font = QtGui.QFont()
    font.setPointSize(14)
    self.lblInformations_3.setFont(font)
    self.lblInformations_3.setObjectName("lblInformations_3")
    self.verticalLayout_18.addWidget(self.lblInformations_3)
    self.lblInformations_4 = QtWidgets.QLabel(self.tab_0)
    font = QtGui.QFont()
    font.setPointSize(14)
    self.lblInformations_4.setFont(font)
    self.lblInformations_4.setObjectName("lblInformations_4")
    self.verticalLayout_18.addWidget(self.lblInformations_4)
    self.horizontalLayout_18.addLayout(self.verticalLayout_18)
    self.verticalLayout_19 = QtWidgets.QVBoxLayout()
    self.verticalLayout_19.setSpacing(4)
    self.verticalLayout_19.setObjectName("verticalLayout_19")
    self.lblGrblName = QtWidgets.QLabel(self.tab_0)
    font = QtGui.QFont()
    font.setPointSize(14)
    font.setBold(True)
    font.setWeight(75)
    self.lblGrblName.setFont(font)
    self.lblGrblName.setObjectName("lblGrblName")
    self.verticalLayout_19.addWidget(self.lblGrblName)
    self.lblGrblDate = QtWidgets.QLabel(self.tab_0)
    font = QtGui.QFont()
    font.setPointSize(14)
    font.setBold(True)
    font.setWeight(75)
    self.lblGrblDate.setFont(font)
    self.lblGrblDate.setObjectName("lblGrblDate")
    self.verticalLayout_19.addWidget(self.lblGrblDate)
    self.lblGrblNbAxes = QtWidgets.QLabel(self.tab_0)
    font = QtGui.QFont()
    font.setPointSize(14)
    font.setBold(True)
    font.setWeight(75)
    self.lblGrblNbAxes.setFont(font)
    self.lblGrblNbAxes.setObjectName("lblGrblNbAxes")
    self.verticalLayout_19.addWidget(self.lblGrblNbAxes)
    self.horizontalLayout_18.addLayout(self.verticalLayout_19)
    self.verticalLayout_20 = QtWidgets.QVBoxLayout()
    self.verticalLayout_20.setSpacing(4)
    self.verticalLayout_20.setObjectName("verticalLayout_20")
    self.lblInformations_2 = QtWidgets.QLabel(self.tab_0)
    font = QtGui.QFont()
    font.setPointSize(14)
    self.lblInformations_2.setFont(font)
    self.lblInformations_2.setObjectName("lblInformations_2")
    self.verticalLayout_20.addWidget(self.lblInformations_2)
    self.lblInformations_6 = QtWidgets.QLabel(self.tab_0)
    font = QtGui.QFont()
    font.setPointSize(14)
    self.lblInformations_6.setFont(font)
    self.lblInformations_6.setObjectName("lblInformations_6")
    self.verticalLayout_20.addWidget(self.lblInformations_6)
    self.lblInformations_11 = QtWidgets.QLabel(self.tab_0)
    font = QtGui.QFont()
    font.setPointSize(14)
    self.lblInformations_11.setFont(font)
    self.lblInformations_11.setObjectName("lblInformations_11")
    self.verticalLayout_20.addWidget(self.lblInformations_11)
    self.horizontalLayout_18.addLayout(self.verticalLayout_20)
    self.verticalLayout_21 = QtWidgets.QVBoxLayout()
    self.verticalLayout_21.setSpacing(4)
    self.verticalLayout_21.setObjectName("verticalLayout_21")
    self.lblGrblVersion = QtWidgets.QLabel(self.tab_0)
    font = QtGui.QFont()
    font.setPointSize(14)
    font.setBold(True)
    font.setWeight(75)
    self.lblGrblVersion.setFont(font)
    self.lblGrblVersion.setObjectName("lblGrblVersion")
    self.verticalLayout_21.addWidget(self.lblGrblVersion)
    self.lneEEPROM = QtWidgets.QLineEdit(self.tab_0)
    self.lneEEPROM.setMinimumSize(QtCore.QSize(131, 0))
    self.lneEEPROM.setObjectName("lneEEPROM")
    self.verticalLayout_21.addWidget(self.lneEEPROM)
    self.lblAxisName = QtWidgets.QLabel(self.tab_0)
    font = QtGui.QFont()
    font.setPointSize(14)
    font.setBold(True)
    font.setWeight(75)
    self.lblAxisName.setFont(font)
    self.lblAxisName.setObjectName("lblAxisName")
    self.verticalLayout_21.addWidget(self.lblAxisName)
    self.horizontalLayout_18.addLayout(self.verticalLayout_21)
    self.verticalLayout_25.addLayout(self.horizontalLayout_18)
    self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_20.setObjectName("horizontalLayout_20")
    self.verticalLayout_24 = QtWidgets.QVBoxLayout()
    self.verticalLayout_24.setObjectName("verticalLayout_24")
    self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_17.setObjectName("horizontalLayout_17")
    self.verticalLayout_22 = QtWidgets.QVBoxLayout()
    self.verticalLayout_22.setSpacing(4)
    self.verticalLayout_22.setObjectName("verticalLayout_22")
    self.lblInformations_5 = QtWidgets.QLabel(self.tab_0)
    font = QtGui.QFont()
    font.setPointSize(14)
    self.lblInformations_5.setFont(font)
    self.lblInformations_5.setObjectName("lblInformations_5")
    self.verticalLayout_22.addWidget(self.lblInformations_5)
    self.lblInformations_9 = QtWidgets.QLabel(self.tab_0)
    font = QtGui.QFont()
    font.setPointSize(12)
    self.lblInformations_9.setFont(font)
    self.lblInformations_9.setObjectName("lblInformations_9")
    self.verticalLayout_22.addWidget(self.lblInformations_9)
    self.lblInformations_10 = QtWidgets.QLabel(self.tab_0)
    font = QtGui.QFont()
    font.setPointSize(12)
    self.lblInformations_10.setFont(font)
    self.lblInformations_10.setObjectName("lblInformations_10")
    self.verticalLayout_22.addWidget(self.lblInformations_10)
    self.horizontalLayout_17.addLayout(self.verticalLayout_22)
    self.verticalLayout_23 = QtWidgets.QVBoxLayout()
    self.verticalLayout_23.setSpacing(4)
    self.verticalLayout_23.setObjectName("verticalLayout_23")
    self.lblGrblOptions = QtWidgets.QLabel(self.tab_0)
    font = QtGui.QFont()
    font.setPointSize(14)
    font.setBold(True)
    font.setWeight(75)
    self.lblGrblOptions.setFont(font)
    self.lblGrblOptions.setObjectName("lblGrblOptions")
    self.verticalLayout_23.addWidget(self.lblGrblOptions)
    self.lblGrblBlockBufferSize = QtWidgets.QLabel(self.tab_0)
    font = QtGui.QFont()
    font.setPointSize(14)
    font.setBold(True)
    font.setWeight(75)
    self.lblGrblBlockBufferSize.setFont(font)
    self.lblGrblBlockBufferSize.setObjectName("lblGrblBlockBufferSize")
    self.verticalLayout_23.addWidget(self.lblGrblBlockBufferSize)
    self.lblGrblRxBufferSize = QtWidgets.QLabel(self.tab_0)
    font = QtGui.QFont()
    font.setPointSize(14)
    font.setBold(True)
    font.setWeight(75)
    self.lblGrblRxBufferSize.setFont(font)
    self.lblGrblRxBufferSize.setObjectName("lblGrblRxBufferSize")
    self.verticalLayout_23.addWidget(self.lblGrblRxBufferSize)
    self.horizontalLayout_17.addLayout(self.verticalLayout_23)
    self.verticalLayout_24.addLayout(self.horizontalLayout_17)
    spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.verticalLayout_24.addItem(spacerItem2)
    self.horizontalLayout_20.addLayout(self.verticalLayout_24)
    self.lstOptions = QtWidgets.QListView(self.tab_0)
    self.lstOptions.setMaximumSize(QtCore.QSize(16777215, 16777215))
    self.lstOptions.setObjectName("lstOptions")
    self.horizontalLayout_20.addWidget(self.lstOptions)
    self.verticalLayout_25.addLayout(self.horizontalLayout_20)
    self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_19.setSpacing(4)
    self.horizontalLayout_19.setObjectName("horizontalLayout_19")
    self.lblInformations_7 = QtWidgets.QLabel(self.tab_0)
    font = QtGui.QFont()
    font.setPointSize(14)
    self.lblInformations_7.setFont(font)
    self.lblInformations_7.setObjectName("lblInformations_7")
    self.horizontalLayout_19.addWidget(self.lblInformations_7)
    self.lneN0 = QtWidgets.QLineEdit(self.tab_0)
    self.lneN0.setMinimumSize(QtCore.QSize(131, 0))
    self.lneN0.setObjectName("lneN0")
    self.horizontalLayout_19.addWidget(self.lneN0)
    self.lblInformations_8 = QtWidgets.QLabel(self.tab_0)
    font = QtGui.QFont()
    font.setPointSize(14)
    self.lblInformations_8.setFont(font)
    self.lblInformations_8.setObjectName("lblInformations_8")
    self.horizontalLayout_19.addWidget(self.lblInformations_8)
    self.lneN1 = QtWidgets.QLineEdit(self.tab_0)
    self.lneN1.setMinimumSize(QtCore.QSize(131, 0))
    self.lneN1.setObjectName("lneN1")
    self.horizontalLayout_19.addWidget(self.lneN1)
    self.verticalLayout_25.addLayout(self.horizontalLayout_19)
    self.gridLayout_7.addLayout(self.verticalLayout_25, 2, 1, 1, 1)
    spacerItem3 = QtWidgets.QSpacerItem(195, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.gridLayout_7.addItem(spacerItem3, 2, 2, 1, 1)
    spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.gridLayout_7.addItem(spacerItem4, 3, 1, 1, 1)
    spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.gridLayout_7.addItem(spacerItem5, 1, 1, 1, 1)
    spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.gridLayout_7.addItem(spacerItem6, 4, 1, 1, 1)
    self.tabWidget.addTab(self.tab_0, "")
    self.tab_1 = QtWidgets.QWidget()
    self.tab_1.setObjectName("tab_1")
    self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_1)
    self.gridLayout_6.setObjectName("gridLayout_6")
    spacerItem7 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.gridLayout_6.addItem(spacerItem7, 0, 1, 1, 1)
    spacerItem8 = QtWidgets.QSpacerItem(111, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.gridLayout_6.addItem(spacerItem8, 1, 0, 1, 1)
    self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_15.setObjectName("horizontalLayout_15")
    self.verticalLayout_16 = QtWidgets.QVBoxLayout()
    self.verticalLayout_16.setObjectName("verticalLayout_16")
    self.label = QtWidgets.QLabel(self.tab_1)
    self.label.setObjectName("label")
    self.verticalLayout_16.addWidget(self.label)
    self.label_2 = QtWidgets.QLabel(self.tab_1)
    self.label_2.setObjectName("label_2")
    self.verticalLayout_16.addWidget(self.label_2)
    self.label_13 = QtWidgets.QLabel(self.tab_1)
    self.label_13.setText("")
    self.label_13.setObjectName("label_13")
    self.verticalLayout_16.addWidget(self.label_13)
    self.label_3 = QtWidgets.QLabel(self.tab_1)
    self.label_3.setObjectName("label_3")
    self.verticalLayout_16.addWidget(self.label_3)
    self.label_4 = QtWidgets.QLabel(self.tab_1)
    self.label_4.setObjectName("label_4")
    self.verticalLayout_16.addWidget(self.label_4)
    self.label_5 = QtWidgets.QLabel(self.tab_1)
    self.label_5.setObjectName("label_5")
    self.verticalLayout_16.addWidget(self.label_5)
    self.label_14 = QtWidgets.QLabel(self.tab_1)
    self.label_14.setObjectName("label_14")
    self.verticalLayout_16.addWidget(self.label_14)
    self.label_15 = QtWidgets.QLabel(self.tab_1)
    self.label_15.setObjectName("label_15")
    self.verticalLayout_16.addWidget(self.label_15)
    self.horizontalLayout_15.addLayout(self.verticalLayout_16)
    self.verticalLayout_15 = QtWidgets.QVBoxLayout()
    self.verticalLayout_15.setObjectName("verticalLayout_15")
    self.spinStepPulse = QtWidgets.QSpinBox(self.tab_1)
    self.spinStepPulse.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.spinStepPulse.setMaximum(99999)
    self.spinStepPulse.setObjectName("spinStepPulse")
    self.verticalLayout_15.addWidget(self.spinStepPulse)
    self.spinStepIdleDelay = QtWidgets.QSpinBox(self.tab_1)
    self.spinStepIdleDelay.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.spinStepIdleDelay.setMaximum(99999)
    self.spinStepIdleDelay.setObjectName("spinStepIdleDelay")
    self.verticalLayout_15.addWidget(self.spinStepIdleDelay)
    self.horizontalLayout = QtWidgets.QHBoxLayout()
    self.horizontalLayout.setSpacing(3)
    self.horizontalLayout.setObjectName("horizontalLayout")
    self.lblMaskX = QtWidgets.QLabel(self.tab_1)
    self.lblMaskX.setAlignment(QtCore.Qt.AlignCenter)
    self.lblMaskX.setObjectName("lblMaskX")
    self.horizontalLayout.addWidget(self.lblMaskX)
    self.lblMaskY = QtWidgets.QLabel(self.tab_1)
    self.lblMaskY.setAlignment(QtCore.Qt.AlignCenter)
    self.lblMaskY.setObjectName("lblMaskY")
    self.horizontalLayout.addWidget(self.lblMaskY)
    self.lblMaskZ = QtWidgets.QLabel(self.tab_1)
    self.lblMaskZ.setAlignment(QtCore.Qt.AlignCenter)
    self.lblMaskZ.setObjectName("lblMaskZ")
    self.horizontalLayout.addWidget(self.lblMaskZ)
    self.lblMaskA = QtWidgets.QLabel(self.tab_1)
    self.lblMaskA.setAlignment(QtCore.Qt.AlignCenter)
    self.lblMaskA.setObjectName("lblMaskA")
    self.horizontalLayout.addWidget(self.lblMaskA)
    self.lblMaskB = QtWidgets.QLabel(self.tab_1)
    self.lblMaskB.setAlignment(QtCore.Qt.AlignCenter)
    self.lblMaskB.setObjectName("lblMaskB")
    self.horizontalLayout.addWidget(self.lblMaskB)
    self.lblMaskC = QtWidgets.QLabel(self.tab_1)
    self.lblMaskC.setAlignment(QtCore.Qt.AlignCenter)
    self.lblMaskC.setObjectName("lblMaskC")
    self.horizontalLayout.addWidget(self.lblMaskC)
    self.label_12 = QtWidgets.QLabel(self.tab_1)
    self.label_12.setMinimumSize(QtCore.QSize(31, 0))
    self.label_12.setAlignment(QtCore.Qt.AlignCenter)
    self.label_12.setObjectName("label_12")
    self.horizontalLayout.addWidget(self.label_12)
    self.verticalLayout_15.addLayout(self.horizontalLayout)
    self.emStepPortInvert = qwEditMask(self.tab_1)
    self.emStepPortInvert.setObjectName("emStepPortInvert")
    self.verticalLayout_15.addWidget(self.emStepPortInvert)
    self.emDirectionPortInvert = qwEditMask(self.tab_1)
    self.emDirectionPortInvert.setObjectName("emDirectionPortInvert")
    self.verticalLayout_15.addWidget(self.emDirectionPortInvert)
    self.chkStepEnableInvert = QtWidgets.QCheckBox(self.tab_1)
    self.chkStepEnableInvert.setObjectName("chkStepEnableInvert")
    self.verticalLayout_15.addWidget(self.chkStepEnableInvert)
    self.chkLimitPinsInvert = QtWidgets.QCheckBox(self.tab_1)
    self.chkLimitPinsInvert.setObjectName("chkLimitPinsInvert")
    self.verticalLayout_15.addWidget(self.chkLimitPinsInvert)
    self.chkProbePinInvert = QtWidgets.QCheckBox(self.tab_1)
    self.chkProbePinInvert.setObjectName("chkProbePinInvert")
    self.verticalLayout_15.addWidget(self.chkProbePinInvert)
    self.horizontalLayout_15.addLayout(self.verticalLayout_15)
    self.gridLayout_6.addLayout(self.horizontalLayout_15, 1, 1, 1, 1)
    spacerItem9 = QtWidgets.QSpacerItem(110, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.gridLayout_6.addItem(spacerItem9, 1, 2, 1, 1)
    spacerItem10 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.gridLayout_6.addItem(spacerItem10, 2, 1, 1, 1)
    self.tabWidget.addTab(self.tab_1, "")
    self.tab_2 = QtWidgets.QWidget()
    self.tab_2.setObjectName("tab_2")
    self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
    self.gridLayout_5.setObjectName("gridLayout_5")
    spacerItem11 = QtWidgets.QSpacerItem(20, 51, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.gridLayout_5.addItem(spacerItem11, 0, 1, 1, 1)
    spacerItem12 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.gridLayout_5.addItem(spacerItem12, 1, 0, 1, 1)
    self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_14.setObjectName("horizontalLayout_14")
    self.verticalLayout_13 = QtWidgets.QVBoxLayout()
    self.verticalLayout_13.setObjectName("verticalLayout_13")
    self.label_16 = QtWidgets.QLabel(self.tab_2)
    self.label_16.setObjectName("label_16")
    self.verticalLayout_13.addWidget(self.label_16)
    self.label_17 = QtWidgets.QLabel(self.tab_2)
    self.label_17.setObjectName("label_17")
    self.verticalLayout_13.addWidget(self.label_17)
    self.label_18 = QtWidgets.QLabel(self.tab_2)
    self.label_18.setObjectName("label_18")
    self.verticalLayout_13.addWidget(self.label_18)
    self.label_19 = QtWidgets.QLabel(self.tab_2)
    self.label_19.setObjectName("label_19")
    self.verticalLayout_13.addWidget(self.label_19)
    self.horizontalLayout_14.addLayout(self.verticalLayout_13)
    self.verticalLayout_14 = QtWidgets.QVBoxLayout()
    self.verticalLayout_14.setObjectName("verticalLayout_14")
    self.lneStatusReport = QtWidgets.QLineEdit(self.tab_2)
    self.lneStatusReport.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lneStatusReport.setReadOnly(True)
    self.lneStatusReport.setObjectName("lneStatusReport")
    self.verticalLayout_14.addWidget(self.lneStatusReport)
    self.dsbJunctionDeviation = QtWidgets.QDoubleSpinBox(self.tab_2)
    self.dsbJunctionDeviation.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.dsbJunctionDeviation.setDecimals(3)
    self.dsbJunctionDeviation.setMaximum(100000.0)
    self.dsbJunctionDeviation.setSingleStep(0.01)
    self.dsbJunctionDeviation.setObjectName("dsbJunctionDeviation")
    self.verticalLayout_14.addWidget(self.dsbJunctionDeviation)
    self.dsbArcTolerance = QtWidgets.QDoubleSpinBox(self.tab_2)
    self.dsbArcTolerance.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.dsbArcTolerance.setDecimals(3)
    self.dsbArcTolerance.setMaximum(100000.0)
    self.dsbArcTolerance.setSingleStep(0.01)
    self.dsbArcTolerance.setObjectName("dsbArcTolerance")
    self.verticalLayout_14.addWidget(self.dsbArcTolerance)
    self.chkReportInches = QtWidgets.QCheckBox(self.tab_2)
    self.chkReportInches.setObjectName("chkReportInches")
    self.verticalLayout_14.addWidget(self.chkReportInches)
    self.horizontalLayout_14.addLayout(self.verticalLayout_14)
    self.gridLayout_5.addLayout(self.horizontalLayout_14, 1, 1, 1, 1)
    spacerItem13 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.gridLayout_5.addItem(spacerItem13, 1, 2, 1, 1)
    spacerItem14 = QtWidgets.QSpacerItem(20, 51, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.gridLayout_5.addItem(spacerItem14, 2, 1, 1, 1)
    self.tabWidget.addTab(self.tab_2, "")
    self.tab_3 = QtWidgets.QWidget()
    self.tab_3.setObjectName("tab_3")
    self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3)
    self.gridLayout_4.setObjectName("gridLayout_4")
    spacerItem15 = QtWidgets.QSpacerItem(95, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.gridLayout_4.addItem(spacerItem15, 1, 0, 1, 1)
    self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_13.setObjectName("horizontalLayout_13")
    self.verticalLayout_12 = QtWidgets.QVBoxLayout()
    self.verticalLayout_12.setObjectName("verticalLayout_12")
    self.label_20 = QtWidgets.QLabel(self.tab_3)
    self.label_20.setObjectName("label_20")
    self.verticalLayout_12.addWidget(self.label_20)
    self.label_21 = QtWidgets.QLabel(self.tab_3)
    self.label_21.setObjectName("label_21")
    self.verticalLayout_12.addWidget(self.label_21)
    self.label_22 = QtWidgets.QLabel(self.tab_3)
    self.label_22.setObjectName("label_22")
    self.verticalLayout_12.addWidget(self.label_22)
    self.label_31 = QtWidgets.QLabel(self.tab_3)
    self.label_31.setText("")
    self.label_31.setObjectName("label_31")
    self.verticalLayout_12.addWidget(self.label_31)
    self.label_23 = QtWidgets.QLabel(self.tab_3)
    self.label_23.setObjectName("label_23")
    self.verticalLayout_12.addWidget(self.label_23)
    self.label_32 = QtWidgets.QLabel(self.tab_3)
    self.label_32.setObjectName("label_32")
    self.verticalLayout_12.addWidget(self.label_32)
    self.label_33 = QtWidgets.QLabel(self.tab_3)
    self.label_33.setObjectName("label_33")
    self.verticalLayout_12.addWidget(self.label_33)
    self.label_34 = QtWidgets.QLabel(self.tab_3)
    self.label_34.setObjectName("label_34")
    self.verticalLayout_12.addWidget(self.label_34)
    self.label_35 = QtWidgets.QLabel(self.tab_3)
    self.label_35.setObjectName("label_35")
    self.verticalLayout_12.addWidget(self.label_35)
    self.horizontalLayout_13.addLayout(self.verticalLayout_12)
    self.verticalLayout_11 = QtWidgets.QVBoxLayout()
    self.verticalLayout_11.setSpacing(2)
    self.verticalLayout_11.setObjectName("verticalLayout_11")
    self.chkSoftLimits = QtWidgets.QCheckBox(self.tab_3)
    self.chkSoftLimits.setObjectName("chkSoftLimits")
    self.verticalLayout_11.addWidget(self.chkSoftLimits)
    self.chkHardLimits = QtWidgets.QCheckBox(self.tab_3)
    self.chkHardLimits.setObjectName("chkHardLimits")
    self.verticalLayout_11.addWidget(self.chkHardLimits)
    self.chkHomingCycle = QtWidgets.QCheckBox(self.tab_3)
    self.chkHomingCycle.setObjectName("chkHomingCycle")
    self.verticalLayout_11.addWidget(self.chkHomingCycle)
    self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_5.setSpacing(3)
    self.horizontalLayout_5.setObjectName("horizontalLayout_5")
    self.lblMaskX_2 = QtWidgets.QLabel(self.tab_3)
    self.lblMaskX_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
    self.lblMaskX_2.setAlignment(QtCore.Qt.AlignCenter)
    self.lblMaskX_2.setObjectName("lblMaskX_2")
    self.horizontalLayout_5.addWidget(self.lblMaskX_2)
    self.lblMaskY_2 = QtWidgets.QLabel(self.tab_3)
    self.lblMaskY_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
    self.lblMaskY_2.setAlignment(QtCore.Qt.AlignCenter)
    self.lblMaskY_2.setObjectName("lblMaskY_2")
    self.horizontalLayout_5.addWidget(self.lblMaskY_2)
    self.lblMaskZ_2 = QtWidgets.QLabel(self.tab_3)
    self.lblMaskZ_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
    self.lblMaskZ_2.setAlignment(QtCore.Qt.AlignCenter)
    self.lblMaskZ_2.setObjectName("lblMaskZ_2")
    self.horizontalLayout_5.addWidget(self.lblMaskZ_2)
    self.lblMaskA_2 = QtWidgets.QLabel(self.tab_3)
    self.lblMaskA_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
    self.lblMaskA_2.setAlignment(QtCore.Qt.AlignCenter)
    self.lblMaskA_2.setObjectName("lblMaskA_2")
    self.horizontalLayout_5.addWidget(self.lblMaskA_2)
    self.lblMaskB_2 = QtWidgets.QLabel(self.tab_3)
    self.lblMaskB_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
    self.lblMaskB_2.setAlignment(QtCore.Qt.AlignCenter)
    self.lblMaskB_2.setObjectName("lblMaskB_2")
    self.horizontalLayout_5.addWidget(self.lblMaskB_2)
    self.lblMaskC_2 = QtWidgets.QLabel(self.tab_3)
    self.lblMaskC_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
    self.lblMaskC_2.setAlignment(QtCore.Qt.AlignCenter)
    self.lblMaskC_2.setObjectName("lblMaskC_2")
    self.horizontalLayout_5.addWidget(self.lblMaskC_2)
    self.label_30 = QtWidgets.QLabel(self.tab_3)
    self.label_30.setMinimumSize(QtCore.QSize(31, 0))
    self.label_30.setMaximumSize(QtCore.QSize(16777215, 16777215))
    self.label_30.setAlignment(QtCore.Qt.AlignCenter)
    self.label_30.setObjectName("label_30")
    self.horizontalLayout_5.addWidget(self.label_30)
    self.verticalLayout_11.addLayout(self.horizontalLayout_5)
    self.emHomeDirInvert = qwEditMask(self.tab_3)
    self.emHomeDirInvert.setObjectName("emHomeDirInvert")
    self.verticalLayout_11.addWidget(self.emHomeDirInvert)
    self.dsbHomingFeed = QtWidgets.QDoubleSpinBox(self.tab_3)
    self.dsbHomingFeed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.dsbHomingFeed.setDecimals(3)
    self.dsbHomingFeed.setMaximum(100000.0)
    self.dsbHomingFeed.setObjectName("dsbHomingFeed")
    self.verticalLayout_11.addWidget(self.dsbHomingFeed)
    self.dsbHomingSeek = QtWidgets.QDoubleSpinBox(self.tab_3)
    self.dsbHomingSeek.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.dsbHomingSeek.setDecimals(3)
    self.dsbHomingSeek.setMaximum(100000.0)
    self.dsbHomingSeek.setObjectName("dsbHomingSeek")
    self.verticalLayout_11.addWidget(self.dsbHomingSeek)
    self.spinHomingDebounce = QtWidgets.QSpinBox(self.tab_3)
    self.spinHomingDebounce.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.spinHomingDebounce.setMaximum(99999)
    self.spinHomingDebounce.setObjectName("spinHomingDebounce")
    self.verticalLayout_11.addWidget(self.spinHomingDebounce)
    self.dsbHomingPullOff = QtWidgets.QDoubleSpinBox(self.tab_3)
    self.dsbHomingPullOff.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.dsbHomingPullOff.setMaximum(100000.0)
    self.dsbHomingPullOff.setObjectName("dsbHomingPullOff")
    self.verticalLayout_11.addWidget(self.dsbHomingPullOff)
    self.horizontalLayout_13.addLayout(self.verticalLayout_11)
    self.gridLayout_4.addLayout(self.horizontalLayout_13, 1, 1, 1, 1)
    spacerItem16 = QtWidgets.QSpacerItem(95, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.gridLayout_4.addItem(spacerItem16, 1, 2, 1, 1)
    spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.gridLayout_4.addItem(spacerItem17, 2, 1, 1, 1)
    spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.gridLayout_4.addItem(spacerItem18, 0, 1, 1, 1)
    self.tabWidget.addTab(self.tab_3, "")
    self.tab_4 = QtWidgets.QWidget()
    self.tab_4.setObjectName("tab_4")
    self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_4)
    self.gridLayout_3.setObjectName("gridLayout_3")
    spacerItem19 = QtWidgets.QSpacerItem(20, 67, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.gridLayout_3.addItem(spacerItem19, 0, 1, 1, 1)
    spacerItem20 = QtWidgets.QSpacerItem(110, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.gridLayout_3.addItem(spacerItem20, 1, 0, 1, 1)
    self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_12.setObjectName("horizontalLayout_12")
    self.verticalLayout_9 = QtWidgets.QVBoxLayout()
    self.verticalLayout_9.setObjectName("verticalLayout_9")
    self.label_36 = QtWidgets.QLabel(self.tab_4)
    self.label_36.setObjectName("label_36")
    self.verticalLayout_9.addWidget(self.label_36)
    self.label_37 = QtWidgets.QLabel(self.tab_4)
    self.label_37.setObjectName("label_37")
    self.verticalLayout_9.addWidget(self.label_37)
    self.label_38 = QtWidgets.QLabel(self.tab_4)
    self.label_38.setObjectName("label_38")
    self.verticalLayout_9.addWidget(self.label_38)
    self.horizontalLayout_12.addLayout(self.verticalLayout_9)
    self.verticalLayout_10 = QtWidgets.QVBoxLayout()
    self.verticalLayout_10.setObjectName("verticalLayout_10")
    self.spinMaxSpindle = QtWidgets.QSpinBox(self.tab_4)
    self.spinMaxSpindle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.spinMaxSpindle.setMaximum(999999)
    self.spinMaxSpindle.setObjectName("spinMaxSpindle")
    self.verticalLayout_10.addWidget(self.spinMaxSpindle)
    self.spinMinSpindle = QtWidgets.QSpinBox(self.tab_4)
    self.spinMinSpindle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.spinMinSpindle.setMaximum(999999)
    self.spinMinSpindle.setObjectName("spinMinSpindle")
    self.verticalLayout_10.addWidget(self.spinMinSpindle)
    self.chkLaserMode = QtWidgets.QCheckBox(self.tab_4)
    self.chkLaserMode.setObjectName("chkLaserMode")
    self.verticalLayout_10.addWidget(self.chkLaserMode)
    self.horizontalLayout_12.addLayout(self.verticalLayout_10)
    self.gridLayout_3.addLayout(self.horizontalLayout_12, 1, 1, 1, 1)
    spacerItem21 = QtWidgets.QSpacerItem(109, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.gridLayout_3.addItem(spacerItem21, 1, 2, 1, 1)
    spacerItem22 = QtWidgets.QSpacerItem(20, 66, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.gridLayout_3.addItem(spacerItem22, 2, 1, 1, 1)
    self.tabWidget.addTab(self.tab_4, "")
    self.tab_5 = QtWidgets.QWidget()
    self.tab_5.setObjectName("tab_5")
    self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_5)
    self.gridLayout_2.setObjectName("gridLayout_2")
    spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.gridLayout_2.addItem(spacerItem23, 2, 1, 1, 1)
    self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_11.setSpacing(12)
    self.horizontalLayout_11.setObjectName("horizontalLayout_11")
    self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_9.setObjectName("horizontalLayout_9")
    self.verticalLayout_5 = QtWidgets.QVBoxLayout()
    self.verticalLayout_5.setObjectName("verticalLayout_5")
    self.lblStepsX = QtWidgets.QLabel(self.tab_5)
    self.lblStepsX.setObjectName("lblStepsX")
    self.verticalLayout_5.addWidget(self.lblStepsX)
    self.lblStepsY = QtWidgets.QLabel(self.tab_5)
    self.lblStepsY.setObjectName("lblStepsY")
    self.verticalLayout_5.addWidget(self.lblStepsY)
    self.lblStepsZ = QtWidgets.QLabel(self.tab_5)
    self.lblStepsZ.setObjectName("lblStepsZ")
    self.verticalLayout_5.addWidget(self.lblStepsZ)
    self.lblStepsA = QtWidgets.QLabel(self.tab_5)
    self.lblStepsA.setObjectName("lblStepsA")
    self.verticalLayout_5.addWidget(self.lblStepsA)
    self.lblStepsB = QtWidgets.QLabel(self.tab_5)
    self.lblStepsB.setObjectName("lblStepsB")
    self.verticalLayout_5.addWidget(self.lblStepsB)
    self.lblStepsC = QtWidgets.QLabel(self.tab_5)
    self.lblStepsC.setEnabled(True)
    self.lblStepsC.setObjectName("lblStepsC")
    self.verticalLayout_5.addWidget(self.lblStepsC)
    self.horizontalLayout_9.addLayout(self.verticalLayout_5)
    self.verticalLayout_6 = QtWidgets.QVBoxLayout()
    self.verticalLayout_6.setObjectName("verticalLayout_6")
    self.dsbStepsX = QtWidgets.QDoubleSpinBox(self.tab_5)
    self.dsbStepsX.setMinimumSize(QtCore.QSize(84, 0))
    self.dsbStepsX.setMaximumSize(QtCore.QSize(84, 16777215))
    self.dsbStepsX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.dsbStepsX.setDecimals(3)
    self.dsbStepsX.setMaximum(100000.0)
    self.dsbStepsX.setObjectName("dsbStepsX")
    self.verticalLayout_6.addWidget(self.dsbStepsX)
    self.dsbStepsY = QtWidgets.QDoubleSpinBox(self.tab_5)
    self.dsbStepsY.setMinimumSize(QtCore.QSize(84, 0))
    self.dsbStepsY.setMaximumSize(QtCore.QSize(84, 16777215))
    self.dsbStepsY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.dsbStepsY.setDecimals(3)
    self.dsbStepsY.setMaximum(100000.0)
    self.dsbStepsY.setObjectName("dsbStepsY")
    self.verticalLayout_6.addWidget(self.dsbStepsY)
    self.dsbStepsZ = QtWidgets.QDoubleSpinBox(self.tab_5)
    self.dsbStepsZ.setMinimumSize(QtCore.QSize(84, 0))
    self.dsbStepsZ.setMaximumSize(QtCore.QSize(84, 16777215))
    self.dsbStepsZ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.dsbStepsZ.setDecimals(3)
    self.dsbStepsZ.setMaximum(100000.0)
    self.dsbStepsZ.setObjectName("dsbStepsZ")
    self.verticalLayout_6.addWidget(self.dsbStepsZ)
    self.dsbStepsA = QtWidgets.QDoubleSpinBox(self.tab_5)
    self.dsbStepsA.setMinimumSize(QtCore.QSize(84, 0))
    self.dsbStepsA.setMaximumSize(QtCore.QSize(84, 16777215))
    self.dsbStepsA.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.dsbStepsA.setDecimals(3)
    self.dsbStepsA.setMaximum(100000.0)
    self.dsbStepsA.setObjectName("dsbStepsA")
    self.verticalLayout_6.addWidget(self.dsbStepsA)
    self.dsbStepsB = QtWidgets.QDoubleSpinBox(self.tab_5)
    self.dsbStepsB.setMinimumSize(QtCore.QSize(84, 0))
    self.dsbStepsB.setMaximumSize(QtCore.QSize(84, 16777215))
    self.dsbStepsB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.dsbStepsB.setDecimals(3)
    self.dsbStepsB.setMaximum(100000.0)
    self.dsbStepsB.setObjectName("dsbStepsB")
    self.verticalLayout_6.addWidget(self.dsbStepsB)
    self.dsbStepsC = QtWidgets.QDoubleSpinBox(self.tab_5)
    self.dsbStepsC.setEnabled(True)
    self.dsbStepsC.setMinimumSize(QtCore.QSize(84, 0))
    self.dsbStepsC.setMaximumSize(QtCore.QSize(84, 16777215))
    self.dsbStepsC.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.dsbStepsC.setDecimals(3)
    self.dsbStepsC.setMaximum(100000.0)
    self.dsbStepsC.setObjectName("dsbStepsC")
    self.verticalLayout_6.addWidget(self.dsbStepsC)
    self.horizontalLayout_9.addLayout(self.verticalLayout_6)
    self.horizontalLayout_11.addLayout(self.horizontalLayout_9)
    self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_10.setObjectName("horizontalLayout_10")
    self.verticalLayout_7 = QtWidgets.QVBoxLayout()
    self.verticalLayout_7.setObjectName("verticalLayout_7")
    self.lblTravelX = QtWidgets.QLabel(self.tab_5)
    self.lblTravelX.setObjectName("lblTravelX")
    self.verticalLayout_7.addWidget(self.lblTravelX)
    self.lblTravelY = QtWidgets.QLabel(self.tab_5)
    self.lblTravelY.setObjectName("lblTravelY")
    self.verticalLayout_7.addWidget(self.lblTravelY)
    self.lblTravelZ = QtWidgets.QLabel(self.tab_5)
    self.lblTravelZ.setObjectName("lblTravelZ")
    self.verticalLayout_7.addWidget(self.lblTravelZ)
    self.lblTravelA = QtWidgets.QLabel(self.tab_5)
    self.lblTravelA.setObjectName("lblTravelA")
    self.verticalLayout_7.addWidget(self.lblTravelA)
    self.lblTravelB = QtWidgets.QLabel(self.tab_5)
    self.lblTravelB.setObjectName("lblTravelB")
    self.verticalLayout_7.addWidget(self.lblTravelB)
    self.lblTravelC = QtWidgets.QLabel(self.tab_5)
    self.lblTravelC.setEnabled(True)
    self.lblTravelC.setObjectName("lblTravelC")
    self.verticalLayout_7.addWidget(self.lblTravelC)
    self.horizontalLayout_10.addLayout(self.verticalLayout_7)
    self.verticalLayout_8 = QtWidgets.QVBoxLayout()
    self.verticalLayout_8.setObjectName("verticalLayout_8")
    self.dsbTravelX = QtWidgets.QDoubleSpinBox(self.tab_5)
    self.dsbTravelX.setMinimumSize(QtCore.QSize(84, 0))
    self.dsbTravelX.setMaximumSize(QtCore.QSize(84, 16777215))
    self.dsbTravelX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.dsbTravelX.setDecimals(3)
    self.dsbTravelX.setMaximum(100000.0)
    self.dsbTravelX.setObjectName("dsbTravelX")
    self.verticalLayout_8.addWidget(self.dsbTravelX)
    self.dsbTravelY = QtWidgets.QDoubleSpinBox(self.tab_5)
    self.dsbTravelY.setMinimumSize(QtCore.QSize(84, 0))
    self.dsbTravelY.setMaximumSize(QtCore.QSize(84, 16777215))
    self.dsbTravelY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.dsbTravelY.setDecimals(3)
    self.dsbTravelY.setMaximum(100000.0)
    self.dsbTravelY.setObjectName("dsbTravelY")
    self.verticalLayout_8.addWidget(self.dsbTravelY)
    self.dsbTravelZ = QtWidgets.QDoubleSpinBox(self.tab_5)
    self.dsbTravelZ.setMinimumSize(QtCore.QSize(84, 0))
    self.dsbTravelZ.setMaximumSize(QtCore.QSize(84, 16777215))
    self.dsbTravelZ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.dsbTravelZ.setDecimals(3)
    self.dsbTravelZ.setMaximum(100000.0)
    self.dsbTravelZ.setObjectName("dsbTravelZ")
    self.verticalLayout_8.addWidget(self.dsbTravelZ)
    self.dsbTravelA = QtWidgets.QDoubleSpinBox(self.tab_5)
    self.dsbTravelA.setMinimumSize(QtCore.QSize(84, 0))
    self.dsbTravelA.setMaximumSize(QtCore.QSize(84, 16777215))
    self.dsbTravelA.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.dsbTravelA.setDecimals(3)
    self.dsbTravelA.setMaximum(100000.0)
    self.dsbTravelA.setObjectName("dsbTravelA")
    self.verticalLayout_8.addWidget(self.dsbTravelA)
    self.dsbTravelB = QtWidgets.QDoubleSpinBox(self.tab_5)
    self.dsbTravelB.setMinimumSize(QtCore.QSize(84, 0))
    self.dsbTravelB.setMaximumSize(QtCore.QSize(84, 16777215))
    self.dsbTravelB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.dsbTravelB.setDecimals(3)
    self.dsbTravelB.setMaximum(100000.0)
    self.dsbTravelB.setObjectName("dsbTravelB")
    self.verticalLayout_8.addWidget(self.dsbTravelB)
    self.dsbTravelC = QtWidgets.QDoubleSpinBox(self.tab_5)
    self.dsbTravelC.setEnabled(True)
    self.dsbTravelC.setMinimumSize(QtCore.QSize(84, 0))
    self.dsbTravelC.setMaximumSize(QtCore.QSize(84, 16777215))
    self.dsbTravelC.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.dsbTravelC.setDecimals(3)
    self.dsbTravelC.setMaximum(100000.0)
    self.dsbTravelC.setObjectName("dsbTravelC")
    self.verticalLayout_8.addWidget(self.dsbTravelC)
    self.horizontalLayout_10.addLayout(self.verticalLayout_8)
    self.horizontalLayout_11.addLayout(self.horizontalLayout_10)
    self.gridLayout_2.addLayout(self.horizontalLayout_11, 1, 1, 1, 1)
    spacerItem24 = QtWidgets.QSpacerItem(45, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.gridLayout_2.addItem(spacerItem24, 1, 0, 1, 1)
    spacerItem25 = QtWidgets.QSpacerItem(45, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.gridLayout_2.addItem(spacerItem25, 1, 2, 1, 1)
    spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.gridLayout_2.addItem(spacerItem26, 0, 1, 1, 1)
    self.tabWidget.addTab(self.tab_5, "")
    self.tab_6 = QtWidgets.QWidget()
    self.tab_6.setObjectName("tab_6")
    self.gridLayout = QtWidgets.QGridLayout(self.tab_6)
    self.gridLayout.setObjectName("gridLayout")
    self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_8.setSpacing(12)
    self.horizontalLayout_8.setObjectName("horizontalLayout_8")
    self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_4.setSpacing(3)
    self.horizontalLayout_4.setObjectName("horizontalLayout_4")
    self.verticalLayout = QtWidgets.QVBoxLayout()
    self.verticalLayout.setObjectName("verticalLayout")
    self.lblRateX = QtWidgets.QLabel(self.tab_6)
    self.lblRateX.setObjectName("lblRateX")
    self.verticalLayout.addWidget(self.lblRateX)
    self.lblRateY = QtWidgets.QLabel(self.tab_6)
    self.lblRateY.setObjectName("lblRateY")
    self.verticalLayout.addWidget(self.lblRateY)
    self.lblRateZ = QtWidgets.QLabel(self.tab_6)
    self.lblRateZ.setObjectName("lblRateZ")
    self.verticalLayout.addWidget(self.lblRateZ)
    self.lblRateA = QtWidgets.QLabel(self.tab_6)
    self.lblRateA.setObjectName("lblRateA")
    self.verticalLayout.addWidget(self.lblRateA)
    self.lblRateB = QtWidgets.QLabel(self.tab_6)
    self.lblRateB.setObjectName("lblRateB")
    self.verticalLayout.addWidget(self.lblRateB)
    self.lblRateC = QtWidgets.QLabel(self.tab_6)
    self.lblRateC.setEnabled(True)
    self.lblRateC.setObjectName("lblRateC")
    self.verticalLayout.addWidget(self.lblRateC)
    self.horizontalLayout_4.addLayout(self.verticalLayout)
    self.verticalLayout_2 = QtWidgets.QVBoxLayout()
    self.verticalLayout_2.setObjectName("verticalLayout_2")
    self.dsbMaxRateX = QtWidgets.QDoubleSpinBox(self.tab_6)
    self.dsbMaxRateX.setMinimumSize(QtCore.QSize(84, 0))
    self.dsbMaxRateX.setMaximumSize(QtCore.QSize(84, 16777215))
    self.dsbMaxRateX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.dsbMaxRateX.setDecimals(3)
    self.dsbMaxRateX.setMaximum(100000.0)
    self.dsbMaxRateX.setProperty("value", 0.0)
    self.dsbMaxRateX.setObjectName("dsbMaxRateX")
    self.verticalLayout_2.addWidget(self.dsbMaxRateX)
    self.dsbMaxRateY = QtWidgets.QDoubleSpinBox(self.tab_6)
    self.dsbMaxRateY.setMinimumSize(QtCore.QSize(84, 0))
    self.dsbMaxRateY.setMaximumSize(QtCore.QSize(84, 16777215))
    self.dsbMaxRateY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.dsbMaxRateY.setDecimals(3)
    self.dsbMaxRateY.setMaximum(100000.0)
    self.dsbMaxRateY.setObjectName("dsbMaxRateY")
    self.verticalLayout_2.addWidget(self.dsbMaxRateY)
    self.dsbMaxRateZ = QtWidgets.QDoubleSpinBox(self.tab_6)
    self.dsbMaxRateZ.setMinimumSize(QtCore.QSize(84, 0))
    self.dsbMaxRateZ.setMaximumSize(QtCore.QSize(84, 16777215))
    self.dsbMaxRateZ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.dsbMaxRateZ.setDecimals(3)
    self.dsbMaxRateZ.setMaximum(100000.0)
    self.dsbMaxRateZ.setObjectName("dsbMaxRateZ")
    self.verticalLayout_2.addWidget(self.dsbMaxRateZ)
    self.dsbMaxRateA = QtWidgets.QDoubleSpinBox(self.tab_6)
    self.dsbMaxRateA.setMinimumSize(QtCore.QSize(84, 0))
    self.dsbMaxRateA.setMaximumSize(QtCore.QSize(84, 16777215))
    self.dsbMaxRateA.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.dsbMaxRateA.setDecimals(3)
    self.dsbMaxRateA.setMaximum(100000.0)
    self.dsbMaxRateA.setObjectName("dsbMaxRateA")
    self.verticalLayout_2.addWidget(self.dsbMaxRateA)
    self.dsbMaxRateB = QtWidgets.QDoubleSpinBox(self.tab_6)
    self.dsbMaxRateB.setMinimumSize(QtCore.QSize(84, 0))
    self.dsbMaxRateB.setMaximumSize(QtCore.QSize(84, 16777215))
    self.dsbMaxRateB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.dsbMaxRateB.setDecimals(3)
    self.dsbMaxRateB.setMaximum(100000.0)
    self.dsbMaxRateB.setObjectName("dsbMaxRateB")
    self.verticalLayout_2.addWidget(self.dsbMaxRateB)
    self.dsbMaxRateC = QtWidgets.QDoubleSpinBox(self.tab_6)
    self.dsbMaxRateC.setEnabled(True)
    self.dsbMaxRateC.setMinimumSize(QtCore.QSize(84, 0))
    self.dsbMaxRateC.setMaximumSize(QtCore.QSize(84, 16777215))
    self.dsbMaxRateC.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.dsbMaxRateC.setDecimals(3)
    self.dsbMaxRateC.setMaximum(100000.0)
    self.dsbMaxRateC.setObjectName("dsbMaxRateC")
    self.verticalLayout_2.addWidget(self.dsbMaxRateC)
    self.horizontalLayout_4.addLayout(self.verticalLayout_2)
    self.horizontalLayout_8.addLayout(self.horizontalLayout_4)
    self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_7.setSpacing(3)
    self.horizontalLayout_7.setObjectName("horizontalLayout_7")
    self.verticalLayout_3 = QtWidgets.QVBoxLayout()
    self.verticalLayout_3.setObjectName("verticalLayout_3")
    self.lblAccelX = QtWidgets.QLabel(self.tab_6)
    self.lblAccelX.setObjectName("lblAccelX")
    self.verticalLayout_3.addWidget(self.lblAccelX)
    self.lblAccelY = QtWidgets.QLabel(self.tab_6)
    self.lblAccelY.setObjectName("lblAccelY")
    self.verticalLayout_3.addWidget(self.lblAccelY)
    self.lblAccelZ = QtWidgets.QLabel(self.tab_6)
    self.lblAccelZ.setObjectName("lblAccelZ")
    self.verticalLayout_3.addWidget(self.lblAccelZ)
    self.lblAccelA = QtWidgets.QLabel(self.tab_6)
    self.lblAccelA.setObjectName("lblAccelA")
    self.verticalLayout_3.addWidget(self.lblAccelA)
    self.lblAccelB = QtWidgets.QLabel(self.tab_6)
    self.lblAccelB.setObjectName("lblAccelB")
    self.verticalLayout_3.addWidget(self.lblAccelB)
    self.lblAccelC = QtWidgets.QLabel(self.tab_6)
    self.lblAccelC.setEnabled(True)
    self.lblAccelC.setObjectName("lblAccelC")
    self.verticalLayout_3.addWidget(self.lblAccelC)
    self.horizontalLayout_7.addLayout(self.verticalLayout_3)
    self.verticalLayout_4 = QtWidgets.QVBoxLayout()
    self.verticalLayout_4.setObjectName("verticalLayout_4")
    self.dsbAccelX = QtWidgets.QDoubleSpinBox(self.tab_6)
    self.dsbAccelX.setMinimumSize(QtCore.QSize(84, 0))
    self.dsbAccelX.setMaximumSize(QtCore.QSize(84, 16777215))
    self.dsbAccelX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.dsbAccelX.setDecimals(3)
    self.dsbAccelX.setMaximum(100000.0)
    self.dsbAccelX.setObjectName("dsbAccelX")
    self.verticalLayout_4.addWidget(self.dsbAccelX)
    self.dsbAccelY = QtWidgets.QDoubleSpinBox(self.tab_6)
    self.dsbAccelY.setMinimumSize(QtCore.QSize(84, 0))
    self.dsbAccelY.setMaximumSize(QtCore.QSize(84, 16777215))
    self.dsbAccelY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.dsbAccelY.setDecimals(3)
    self.dsbAccelY.setMaximum(100000.0)
    self.dsbAccelY.setObjectName("dsbAccelY")
    self.verticalLayout_4.addWidget(self.dsbAccelY)
    self.dsbAccelZ = QtWidgets.QDoubleSpinBox(self.tab_6)
    self.dsbAccelZ.setMinimumSize(QtCore.QSize(84, 0))
    self.dsbAccelZ.setMaximumSize(QtCore.QSize(84, 16777215))
    self.dsbAccelZ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.dsbAccelZ.setDecimals(3)
    self.dsbAccelZ.setMaximum(100000.0)
    self.dsbAccelZ.setObjectName("dsbAccelZ")
    self.verticalLayout_4.addWidget(self.dsbAccelZ)
    self.dsbAccelA = QtWidgets.QDoubleSpinBox(self.tab_6)
    self.dsbAccelA.setMinimumSize(QtCore.QSize(84, 0))
    self.dsbAccelA.setMaximumSize(QtCore.QSize(84, 16777215))
    self.dsbAccelA.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.dsbAccelA.setDecimals(3)
    self.dsbAccelA.setMaximum(100000.0)
    self.dsbAccelA.setObjectName("dsbAccelA")
    self.verticalLayout_4.addWidget(self.dsbAccelA)
    self.dsbAccelB = QtWidgets.QDoubleSpinBox(self.tab_6)
    self.dsbAccelB.setMinimumSize(QtCore.QSize(84, 0))
    self.dsbAccelB.setMaximumSize(QtCore.QSize(84, 16777215))
    self.dsbAccelB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.dsbAccelB.setDecimals(3)
    self.dsbAccelB.setMaximum(100000.0)
    self.dsbAccelB.setObjectName("dsbAccelB")
    self.verticalLayout_4.addWidget(self.dsbAccelB)
    self.dsbAccelC = QtWidgets.QDoubleSpinBox(self.tab_6)
    self.dsbAccelC.setEnabled(True)
    self.dsbAccelC.setMinimumSize(QtCore.QSize(84, 0))
    self.dsbAccelC.setMaximumSize(QtCore.QSize(84, 16777215))
    self.dsbAccelC.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.dsbAccelC.setDecimals(3)
    self.dsbAccelC.setMaximum(100000.0)
    self.dsbAccelC.setObjectName("dsbAccelC")
    self.verticalLayout_4.addWidget(self.dsbAccelC)
    self.horizontalLayout_7.addLayout(self.verticalLayout_4)
    self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
    self.gridLayout.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
    spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.gridLayout.addItem(spacerItem27, 2, 0, 1, 1)
    spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.gridLayout.addItem(spacerItem28, 0, 0, 1, 1)
    self.tabWidget.addTab(self.tab_6, "")
    self.verticalLayout_17.addWidget(self.tabWidget)
    self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_16.setObjectName("horizontalLayout_16")
    spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.horizontalLayout_16.addItem(spacerItem29)
    self.buttonBox = QtWidgets.QDialogButtonBox(dlgConfig)
    self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
    self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.NoButton)
    self.buttonBox.setCenterButtons(False)
    self.buttonBox.setObjectName("buttonBox")
    self.horizontalLayout_16.addWidget(self.buttonBox)
    self.verticalLayout_17.addLayout(self.horizontalLayout_16)

    self.retranslateUi(dlgConfig)
    self.tabWidget.setCurrentIndex(0)
    self.buttonBox.accepted.connect(dlgConfig.accept)
    self.buttonBox.rejected.connect(dlgConfig.reject)
    QtCore.QMetaObject.connectSlotsByName(dlgConfig)

  def retranslateUi(self, dlgConfig):
    _translate = QtCore.QCoreApplication.translate
    dlgConfig.setWindowTitle(_translate("dlgConfig", "cn5X++ - Configuration de Grbl"))
    self.lblInformations.setText(_translate("dlgConfig", "Microcode :"))
    self.lblInformations_3.setText(_translate("dlgConfig", "Date version :"))
    self.lblInformations_4.setText(_translate("dlgConfig", "Nombre d\'axes :"))
    self.lblGrblName.setText(_translate("dlgConfig", "---"))
    self.lblGrblDate.setText(_translate("dlgConfig", "---"))
    self.lblGrblNbAxes.setText(_translate("dlgConfig", "---"))
    self.lblInformations_2.setText(_translate("dlgConfig", "Version :"))
    self.lblInformations_6.setText(_translate("dlgConfig", "EEPROM string :"))
    self.lblInformations_11.setText(_translate("dlgConfig", "Nom des axes :"))
    self.lblGrblVersion.setText(_translate("dlgConfig", "---"))
    self.lblAxisName.setText(_translate("dlgConfig", "---"))
    self.lblInformations_5.setText(_translate("dlgConfig", "Options :"))
    self.lblInformations_9.setText(_translate("dlgConfig", "BLOCK_BUFFER_SIZE"))
    self.lblInformations_10.setText(_translate("dlgConfig", "RX_BUFFER_SIZE"))
    self.lblGrblOptions.setText(_translate("dlgConfig", "---"))
    self.lblGrblBlockBufferSize.setText(_translate("dlgConfig", "---"))
    self.lblGrblRxBufferSize.setText(_translate("dlgConfig", "---"))
    self.lblInformations_7.setText(_translate("dlgConfig", "$N0 :"))
    self.lblInformations_8.setText(_translate("dlgConfig", "$N1 :"))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_0), _translate("dlgConfig", "Initialisation"))
    self.label.setText(_translate("dlgConfig", "Step pulse, microseconds ($0)"))
    self.label_2.setText(_translate("dlgConfig", "Step idle delay, milliseconds ($1)"))
    self.label_3.setText(_translate("dlgConfig", "Step port invert, mask ($2)"))
    self.label_4.setText(_translate("dlgConfig", "Direction port invert, mask ($3)"))
    self.label_5.setText(_translate("dlgConfig", "Step enable invert, boolean ($4)"))
    self.label_14.setText(_translate("dlgConfig", "Limit pins invert, boolean ($5)"))
    self.label_15.setText(_translate("dlgConfig", "Probe pin invert, boolean ($6)"))
    self.lblMaskX.setText(_translate("dlgConfig", "X"))
    self.lblMaskY.setText(_translate("dlgConfig", "Y"))
    self.lblMaskZ.setText(_translate("dlgConfig", "Z"))
    self.lblMaskA.setText(_translate("dlgConfig", "A"))
    self.lblMaskB.setText(_translate("dlgConfig", "B"))
    self.lblMaskC.setText(_translate("dlgConfig", "C"))
    self.label_12.setText(_translate("dlgConfig", "Val"))
    self.emStepPortInvert.setToolTip(_translate("dlgConfig", "Editeur de masque 6 axes"))
    self.emStepPortInvert.setWhatsThis(_translate("dlgConfig", "Editeur de masque 6 axes"))
    self.emDirectionPortInvert.setToolTip(_translate("dlgConfig", "Editeur de masque 6 axes"))
    self.emDirectionPortInvert.setWhatsThis(_translate("dlgConfig", "Editeur de masque 6 axes"))
    self.chkStepEnableInvert.setText(_translate("dlgConfig", "False"))
    self.chkLimitPinsInvert.setText(_translate("dlgConfig", "False"))
    self.chkProbePinInvert.setText(_translate("dlgConfig", "False"))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("dlgConfig", "Matériel"))
    self.label_16.setText(_translate("dlgConfig", "Status report, mask ($10)"))
    self.label_17.setText(_translate("dlgConfig", "Junction deviation, mm ($11)"))
    self.label_18.setText(_translate("dlgConfig", "Arc tolerance, mm ($12)"))
    self.label_19.setText(_translate("dlgConfig", "Report inches, boolean ($13)"))
    self.lneStatusReport.setText(_translate("dlgConfig", "0"))
    self.chkReportInches.setText(_translate("dlgConfig", "False"))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("dlgConfig", "Unités"))
    self.label_20.setText(_translate("dlgConfig", "Soft limits, boolean ($20)"))
    self.label_21.setText(_translate("dlgConfig", "Hard limits, boolean ($21)"))
    self.label_22.setText(_translate("dlgConfig", "Homing cycle, boolean ($22)"))
    self.label_23.setText(_translate("dlgConfig", "Homing dir invert, mask ($23)"))
    self.label_32.setText(_translate("dlgConfig", "Homing feed, mm/min ($24)"))
    self.label_33.setText(_translate("dlgConfig", "Homing seek, mm/min ($25)"))
    self.label_34.setText(_translate("dlgConfig", "Homing debounce, milliseconds ($26)"))
    self.label_35.setText(_translate("dlgConfig", "Homing pull-off, mm ($27)"))
    self.chkSoftLimits.setText(_translate("dlgConfig", "False"))
    self.chkHardLimits.setText(_translate("dlgConfig", "False"))
    self.chkHomingCycle.setText(_translate("dlgConfig", "False"))
    self.lblMaskX_2.setText(_translate("dlgConfig", "X"))
    self.lblMaskY_2.setText(_translate("dlgConfig", "Y"))
    self.lblMaskZ_2.setText(_translate("dlgConfig", "Z"))
    self.lblMaskA_2.setText(_translate("dlgConfig", "A"))
    self.lblMaskB_2.setText(_translate("dlgConfig", "B"))
    self.lblMaskC_2.setText(_translate("dlgConfig", "C"))
    self.label_30.setText(_translate("dlgConfig", "Val"))
    self.emHomeDirInvert.setToolTip(_translate("dlgConfig", "Editeur de masque 6 axes"))
    self.emHomeDirInvert.setWhatsThis(_translate("dlgConfig", "Editeur de masque 6 axes"))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("dlgConfig", "Limites"))
    self.label_36.setText(_translate("dlgConfig", "Max spindle speed, RPM or laser power ($30)"))
    self.label_37.setText(_translate("dlgConfig", "Min spindle speed, RPM ($31)"))
    self.label_38.setText(_translate("dlgConfig", "Laser mode, boolean (32)"))
    self.chkLaserMode.setText(_translate("dlgConfig", "False"))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("dlgConfig", "Broche"))
    self.lblStepsX.setText(_translate("dlgConfig", "X steps/mm ($100)"))
    self.lblStepsY.setText(_translate("dlgConfig", "Y steps/mm ($101)"))
    self.lblStepsZ.setText(_translate("dlgConfig", "Z steps/mm ($102)"))
    self.lblStepsA.setText(_translate("dlgConfig", "A steps/unit ($103)"))
    self.lblStepsB.setText(_translate("dlgConfig", "B steps/unit ($104)"))
    self.lblStepsC.setText(_translate("dlgConfig", "C steps/unit ($105)"))
    self.lblTravelX.setText(_translate("dlgConfig", "X Max travel, mm ($130)"))
    self.lblTravelY.setText(_translate("dlgConfig", "Y Max travel, mm ($131)"))
    self.lblTravelZ.setText(_translate("dlgConfig", "Z Max travel, mm ($132)"))
    self.lblTravelA.setText(_translate("dlgConfig", "A Max travel, unit ($133)"))
    self.lblTravelB.setText(_translate("dlgConfig", "B Max travel, unit ($134)"))
    self.lblTravelC.setText(_translate("dlgConfig", "C Max travel, unit ($135)"))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("dlgConfig", "Courses"))
    self.lblRateX.setText(_translate("dlgConfig", "X Max rate, mm/min ($110)"))
    self.lblRateY.setText(_translate("dlgConfig", "Y Max rate, mm/min ($111)"))
    self.lblRateZ.setText(_translate("dlgConfig", "Z Max rate, mm/min ($112)"))
    self.lblRateA.setText(_translate("dlgConfig", "A Max rate, unit/min ($113)"))
    self.lblRateB.setText(_translate("dlgConfig", "B Max rate, unit/min ($114)"))
    self.lblRateC.setText(_translate("dlgConfig", "C Max rate, unit/min ($115)"))
    self.lblAccelX.setText(_translate("dlgConfig", "X Acceleration, mm/sec^2 ($120)"))
    self.lblAccelY.setText(_translate("dlgConfig", "Y Acceleration, mm/sec^2 ($121)"))
    self.lblAccelZ.setText(_translate("dlgConfig", "Z Acceleration, mm/sec^2 ($122)"))
    self.lblAccelA.setText(_translate("dlgConfig", "A Acceleration, unit/sec^2 ($123)"))
    self.lblAccelB.setText(_translate("dlgConfig", "B Acceleration, unit/sec^2 ($124)"))
    self.lblAccelC.setText(_translate("dlgConfig", "C Acceleration, unit/sec^2 ($125)"))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("dlgConfig", "Vitesses"))

from qweditmask import qwEditMask
import cn5X_rc
