# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgToolChange.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgToolChange(object):
  def setupUi(self, dlgToolChange):
    dlgToolChange.setObjectName("dlgToolChange")
    dlgToolChange.setWindowModality(QtCore.Qt.ApplicationModal)
    dlgToolChange.resize(425, 196)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(dlgToolChange.sizePolicy().hasHeightForWidth())
    dlgToolChange.setSizePolicy(sizePolicy)
    icon = QtGui.QIcon()
    icon.addPixmap(QtGui.QPixmap(":/cn5X/images/XYZAB.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    dlgToolChange.setWindowIcon(icon)
    dlgToolChange.setModal(True)
    self.horizontalLayout_2 = QtWidgets.QHBoxLayout(dlgToolChange)
    self.horizontalLayout_2.setObjectName("horizontalLayout_2")
    self.verticalLayout_2 = QtWidgets.QVBoxLayout()
    self.verticalLayout_2.setSpacing(0)
    self.verticalLayout_2.setObjectName("verticalLayout_2")
    spacerItem = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.verticalLayout_2.addItem(spacerItem)
    self.label_2 = QtWidgets.QLabel(dlgToolChange)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
    self.label_2.setSizePolicy(sizePolicy)
    self.label_2.setMinimumSize(QtCore.QSize(75, 150))
    self.label_2.setText("")
    self.label_2.setPixmap(QtGui.QPixmap(":/cn5X/images/fraise.svg"))
    self.label_2.setScaledContents(True)
    self.label_2.setObjectName("label_2")
    self.verticalLayout_2.addWidget(self.label_2)
    spacerItem1 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.verticalLayout_2.addItem(spacerItem1)
    self.horizontalLayout_2.addLayout(self.verticalLayout_2)
    self.verticalLayout = QtWidgets.QVBoxLayout()
    self.verticalLayout.setObjectName("verticalLayout")
    self.lblMessage = QtWidgets.QLabel(dlgToolChange)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.lblMessage.sizePolicy().hasHeightForWidth())
    self.lblMessage.setSizePolicy(sizePolicy)
    font = QtGui.QFont()
    font.setPointSize(14)
    self.lblMessage.setFont(font)
    self.lblMessage.setAlignment(QtCore.Qt.AlignCenter)
    self.lblMessage.setObjectName("lblMessage")
    self.verticalLayout.addWidget(self.lblMessage)
    self.horizontalLayout = QtWidgets.QHBoxLayout()
    self.horizontalLayout.setObjectName("horizontalLayout")
    spacerItem2 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
    self.horizontalLayout.addItem(spacerItem2)
    self.btnGo = cnQPushButton(dlgToolChange)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.btnGo.sizePolicy().hasHeightForWidth())
    self.btnGo.setSizePolicy(sizePolicy)
    self.btnGo.setMinimumSize(QtCore.QSize(50, 50))
    self.btnGo.setMaximumSize(QtCore.QSize(16777215, 16777215))
    self.btnGo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.btnGo.setStyleSheet("border-radius: 25;")
    self.btnGo.setText("")
    icon1 = QtGui.QIcon()
    icon1.addPixmap(QtGui.QPixmap(":/cn5X/images/btnGo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.btnGo.setIcon(icon1)
    self.btnGo.setIconSize(QtCore.QSize(50, 50))
    self.btnGo.setObjectName("btnGo")
    self.horizontalLayout.addWidget(self.btnGo)
    self.btnStop = cnQPushButton(dlgToolChange)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.btnStop.sizePolicy().hasHeightForWidth())
    self.btnStop.setSizePolicy(sizePolicy)
    self.btnStop.setMinimumSize(QtCore.QSize(50, 50))
    self.btnStop.setMaximumSize(QtCore.QSize(16777215, 16777215))
    self.btnStop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.btnStop.setStyleSheet("border-radius: 25;")
    self.btnStop.setText("")
    icon2 = QtGui.QIcon()
    icon2.addPixmap(QtGui.QPixmap(":/cn5X/images/btnStop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.btnStop.setIcon(icon2)
    self.btnStop.setIconSize(QtCore.QSize(50, 50))
    self.btnStop.setObjectName("btnStop")
    self.horizontalLayout.addWidget(self.btnStop)
    self.verticalLayout.addLayout(self.horizontalLayout)
    self.horizontalLayout_2.addLayout(self.verticalLayout)

    self.retranslateUi(dlgToolChange)
    QtCore.QMetaObject.connectSlotsByName(dlgToolChange)

  def retranslateUi(self, dlgToolChange):
    _translate = QtCore.QCoreApplication.translate
    dlgToolChange.setWindowTitle(_translate("dlgToolChange", "Tool change"))
    self.lblMessage.setText(_translate("dlgToolChange", "Insert tool number 0\n"
"and click the \'Go\' button\n"
"to continue when ready."))
    self.btnGo.setToolTip(_translate("dlgToolChange", "Continue with new tool"))
    self.btnStop.setToolTip(_translate("dlgToolChange", "Stop current job"))
from cnQPushButton import cnQPushButton
import cn5X_rc
