# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
  def setupUi(self, mainWindow):
    mainWindow.setObjectName("mainWindow")
    mainWindow.setEnabled(True)
    mainWindow.resize(1040, 600)
    mainWindow.setMinimumSize(QtCore.QSize(0, 0))
    icon = QtGui.QIcon()
    icon.addPixmap(QtGui.QPixmap("images/XYZAB-48.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    mainWindow.setWindowIcon(icon)
    self.centralwidget = QtWidgets.QWidget(mainWindow)
    self.centralwidget.setObjectName("centralwidget")
    self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.centralwidget)
    self.horizontalLayout_17.setContentsMargins(4, 4, 4, 0)
    self.horizontalLayout_17.setSpacing(2)
    self.horizontalLayout_17.setObjectName("horizontalLayout_17")
    self.grpCommandes = QtWidgets.QFrame(self.centralwidget)
    self.grpCommandes.setEnabled(True)
    self.grpCommandes.setFrameShape(QtWidgets.QFrame.Box)
    self.grpCommandes.setObjectName("grpCommandes")
    self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.grpCommandes)
    self.verticalLayout_9.setContentsMargins(2, 0, 0, 0)
    self.verticalLayout_9.setSpacing(0)
    self.verticalLayout_9.setObjectName("verticalLayout_9")
    self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_15.setSpacing(0)
    self.horizontalLayout_15.setObjectName("horizontalLayout_15")
    self.frmArretUrgence = QtWidgets.QFrame(self.grpCommandes)
    self.frmArretUrgence.setEnabled(False)
    self.frmArretUrgence.setObjectName("frmArretUrgence")
    self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frmArretUrgence)
    self.verticalLayout_2.setObjectName("verticalLayout_2")
    self.btnUrgence = QtWidgets.QPushButton(self.frmArretUrgence)
    self.btnUrgence.setMinimumSize(QtCore.QSize(100, 100))
    self.btnUrgence.setMaximumSize(QtCore.QSize(16777215, 16777215))
    self.btnUrgence.setStyleSheet("border-radius: 25;")
    self.btnUrgence.setText("")
    icon1 = QtGui.QIcon()
    icon1.addPixmap(QtGui.QPixmap("images/btnUrgenceOff.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.btnUrgence.setIcon(icon1)
    self.btnUrgence.setIconSize(QtCore.QSize(100, 100))
    self.btnUrgence.setCheckable(False)
    self.btnUrgence.setChecked(False)
    self.btnUrgence.setObjectName("btnUrgence")
    self.verticalLayout_2.addWidget(self.btnUrgence)
    spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.verticalLayout_2.addItem(spacerItem)
    self.horizontalLayout_15.addWidget(self.frmArretUrgence)
    spacerItem1 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.horizontalLayout_15.addItem(spacerItem1)
    self.frmControleVitesse = QtWidgets.QFrame(self.grpCommandes)
    self.frmControleVitesse.setEnabled(False)
    self.frmControleVitesse.setFrameShape(QtWidgets.QFrame.Box)
    self.frmControleVitesse.setFrameShadow(QtWidgets.QFrame.Plain)
    self.frmControleVitesse.setObjectName("frmControleVitesse")
    self.verticalLayout = QtWidgets.QVBoxLayout(self.frmControleVitesse)
    self.verticalLayout.setContentsMargins(0, 0, 0, 0)
    self.verticalLayout.setSpacing(0)
    self.verticalLayout.setObjectName("verticalLayout")
    self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_9.setSpacing(4)
    self.horizontalLayout_9.setObjectName("horizontalLayout_9")
    self.verticalLayout_7 = QtWidgets.QVBoxLayout()
    self.verticalLayout_7.setSpacing(0)
    self.verticalLayout_7.setObjectName("verticalLayout_7")
    self.label_22 = QtWidgets.QLabel(self.frmControleVitesse)
    self.label_22.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
    self.label_22.setObjectName("label_22")
    self.verticalLayout_7.addWidget(self.label_22)
    self.dialAvance = QtWidgets.QDial(self.frmControleVitesse)
    self.dialAvance.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.dialAvance.setMinimum(10)
    self.dialAvance.setMaximum(200)
    self.dialAvance.setProperty("value", 100)
    self.dialAvance.setWrapping(False)
    self.dialAvance.setNotchTarget(10.0)
    self.dialAvance.setNotchesVisible(True)
    self.dialAvance.setObjectName("dialAvance")
    self.verticalLayout_7.addWidget(self.dialAvance)
    self.lblAvancePourcent = QtWidgets.QLabel(self.frmControleVitesse)
    self.lblAvancePourcent.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
    self.lblAvancePourcent.setObjectName("lblAvancePourcent")
    self.verticalLayout_7.addWidget(self.lblAvancePourcent)
    self.horizontalLayout_9.addLayout(self.verticalLayout_7)
    self.verticalLayout_8 = QtWidgets.QVBoxLayout()
    self.verticalLayout_8.setSpacing(0)
    self.verticalLayout_8.setObjectName("verticalLayout_8")
    self.label_23 = QtWidgets.QLabel(self.frmControleVitesse)
    self.label_23.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
    self.label_23.setObjectName("label_23")
    self.verticalLayout_8.addWidget(self.label_23)
    self.dialBroche = QtWidgets.QDial(self.frmControleVitesse)
    self.dialBroche.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.dialBroche.setMinimum(10)
    self.dialBroche.setMaximum(200)
    self.dialBroche.setProperty("value", 100)
    self.dialBroche.setWrapping(False)
    self.dialBroche.setNotchTarget(10.0)
    self.dialBroche.setNotchesVisible(True)
    self.dialBroche.setObjectName("dialBroche")
    self.verticalLayout_8.addWidget(self.dialBroche)
    self.lblBrochePourcent = QtWidgets.QLabel(self.frmControleVitesse)
    self.lblBrochePourcent.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
    self.lblBrochePourcent.setObjectName("lblBrochePourcent")
    self.verticalLayout_8.addWidget(self.lblBrochePourcent)
    self.horizontalLayout_9.addLayout(self.verticalLayout_8)
    self.verticalLayout.addLayout(self.horizontalLayout_9)
    self.groupBox_4 = QtWidgets.QGroupBox(self.frmControleVitesse)
    self.groupBox_4.setObjectName("groupBox_4")
    self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_4)
    self.horizontalLayout_8.setObjectName("horizontalLayout_8")
    self.radioButton_10 = QtWidgets.QRadioButton(self.groupBox_4)
    self.radioButton_10.setObjectName("radioButton_10")
    self.horizontalLayout_8.addWidget(self.radioButton_10)
    self.radioButton_11 = QtWidgets.QRadioButton(self.groupBox_4)
    self.radioButton_11.setObjectName("radioButton_11")
    self.horizontalLayout_8.addWidget(self.radioButton_11)
    self.radioButton_12 = QtWidgets.QRadioButton(self.groupBox_4)
    self.radioButton_12.setChecked(True)
    self.radioButton_12.setObjectName("radioButton_12")
    self.horizontalLayout_8.addWidget(self.radioButton_12)
    self.verticalLayout.addWidget(self.groupBox_4)
    self.horizontalLayout_15.addWidget(self.frmControleVitesse)
    self.verticalLayout_9.addLayout(self.horizontalLayout_15)
    self.grpJog = QtWidgets.QGroupBox(self.grpCommandes)
    self.grpJog.setEnabled(False)
    self.grpJog.setMaximumSize(QtCore.QSize(16777215, 16777215))
    self.grpJog.setObjectName("grpJog")
    self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.grpJog)
    self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
    self.horizontalLayout_16.setSpacing(2)
    self.horizontalLayout_16.setObjectName("horizontalLayout_16")
    self.gridLayout_3 = QtWidgets.QGridLayout()
    self.gridLayout_3.setContentsMargins(-1, -1, -1, 0)
    self.gridLayout_3.setSpacing(4)
    self.gridLayout_3.setObjectName("gridLayout_3")
    self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_13.setSpacing(0)
    self.horizontalLayout_13.setObjectName("horizontalLayout_13")
    self.pushButton_4 = QtWidgets.QPushButton(self.grpJog)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
    self.pushButton_4.setSizePolicy(sizePolicy)
    self.pushButton_4.setMaximumSize(QtCore.QSize(32, 16777215))
    self.pushButton_4.setObjectName("pushButton_4")
    self.horizontalLayout_13.addWidget(self.pushButton_4)
    self.pushButton_5 = QtWidgets.QPushButton(self.grpJog)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
    self.pushButton_5.setSizePolicy(sizePolicy)
    self.pushButton_5.setMaximumSize(QtCore.QSize(32, 16777215))
    self.pushButton_5.setObjectName("pushButton_5")
    self.horizontalLayout_13.addWidget(self.pushButton_5)
    self.gridLayout_3.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)
    self.pushButton_6 = QtWidgets.QPushButton(self.grpJog)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
    self.pushButton_6.setSizePolicy(sizePolicy)
    self.pushButton_6.setMaximumSize(QtCore.QSize(63, 16777215))
    self.pushButton_6.setObjectName("pushButton_6")
    self.gridLayout_3.addWidget(self.pushButton_6, 0, 1, 1, 1)
    self.pushButton_7 = QtWidgets.QPushButton(self.grpJog)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
    self.pushButton_7.setSizePolicy(sizePolicy)
    self.pushButton_7.setMaximumSize(QtCore.QSize(63, 16777215))
    self.pushButton_7.setObjectName("pushButton_7")
    self.gridLayout_3.addWidget(self.pushButton_7, 0, 2, 1, 1)
    self.pushButton_8 = QtWidgets.QPushButton(self.grpJog)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
    self.pushButton_8.setSizePolicy(sizePolicy)
    self.pushButton_8.setMaximumSize(QtCore.QSize(63, 16777215))
    self.pushButton_8.setObjectName("pushButton_8")
    self.gridLayout_3.addWidget(self.pushButton_8, 1, 0, 1, 1)
    self.btnStopJog = QtWidgets.QPushButton(self.grpJog)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.btnStopJog.sizePolicy().hasHeightForWidth())
    self.btnStopJog.setSizePolicy(sizePolicy)
    self.btnStopJog.setMaximumSize(QtCore.QSize(63, 16777215))
    self.btnStopJog.setText("")
    icon2 = QtGui.QIcon()
    icon2.addPixmap(QtGui.QPixmap(":/cn5X/images/btnStopJog.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.btnStopJog.setIcon(icon2)
    self.btnStopJog.setIconSize(QtCore.QSize(55, 55))
    self.btnStopJog.setObjectName("btnStopJog")
    self.gridLayout_3.addWidget(self.btnStopJog, 1, 1, 1, 1)
    self.pushButton_10 = QtWidgets.QPushButton(self.grpJog)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
    self.pushButton_10.setSizePolicy(sizePolicy)
    self.pushButton_10.setMaximumSize(QtCore.QSize(63, 16777215))
    self.pushButton_10.setObjectName("pushButton_10")
    self.gridLayout_3.addWidget(self.pushButton_10, 1, 2, 1, 1)
    self.pushButton_11 = QtWidgets.QPushButton(self.grpJog)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
    self.pushButton_11.setSizePolicy(sizePolicy)
    self.pushButton_11.setMaximumSize(QtCore.QSize(63, 16777215))
    self.pushButton_11.setObjectName("pushButton_11")
    self.gridLayout_3.addWidget(self.pushButton_11, 2, 0, 1, 1)
    self.pushButton_12 = QtWidgets.QPushButton(self.grpJog)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
    self.pushButton_12.setSizePolicy(sizePolicy)
    self.pushButton_12.setMaximumSize(QtCore.QSize(63, 16777215))
    self.pushButton_12.setObjectName("pushButton_12")
    self.gridLayout_3.addWidget(self.pushButton_12, 2, 1, 1, 1)
    self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_14.setSpacing(0)
    self.horizontalLayout_14.setObjectName("horizontalLayout_14")
    self.pushButton_13 = QtWidgets.QPushButton(self.grpJog)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
    self.pushButton_13.setSizePolicy(sizePolicy)
    self.pushButton_13.setMaximumSize(QtCore.QSize(32, 16777215))
    self.pushButton_13.setObjectName("pushButton_13")
    self.horizontalLayout_14.addWidget(self.pushButton_13)
    self.pushButton_14 = QtWidgets.QPushButton(self.grpJog)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
    self.pushButton_14.setSizePolicy(sizePolicy)
    self.pushButton_14.setMaximumSize(QtCore.QSize(32, 16777215))
    self.pushButton_14.setObjectName("pushButton_14")
    self.horizontalLayout_14.addWidget(self.pushButton_14)
    self.gridLayout_3.addLayout(self.horizontalLayout_14, 2, 2, 1, 1)
    self.horizontalLayout_16.addLayout(self.gridLayout_3)
    self.verticalLayout_10 = QtWidgets.QVBoxLayout()
    self.verticalLayout_10.setSpacing(0)
    self.verticalLayout_10.setObjectName("verticalLayout_10")
    self.radioButton = QtWidgets.QRadioButton(self.grpJog)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.radioButton.sizePolicy().hasHeightForWidth())
    self.radioButton.setSizePolicy(sizePolicy)
    self.radioButton.setObjectName("radioButton")
    self.verticalLayout_10.addWidget(self.radioButton)
    self.radioButton_2 = QtWidgets.QRadioButton(self.grpJog)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.radioButton_2.sizePolicy().hasHeightForWidth())
    self.radioButton_2.setSizePolicy(sizePolicy)
    self.radioButton_2.setObjectName("radioButton_2")
    self.verticalLayout_10.addWidget(self.radioButton_2)
    self.radioButton_3 = QtWidgets.QRadioButton(self.grpJog)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.radioButton_3.sizePolicy().hasHeightForWidth())
    self.radioButton_3.setSizePolicy(sizePolicy)
    self.radioButton_3.setObjectName("radioButton_3")
    self.verticalLayout_10.addWidget(self.radioButton_3)
    self.radioButton_4 = QtWidgets.QRadioButton(self.grpJog)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.radioButton_4.sizePolicy().hasHeightForWidth())
    self.radioButton_4.setSizePolicy(sizePolicy)
    self.radioButton_4.setObjectName("radioButton_4")
    self.verticalLayout_10.addWidget(self.radioButton_4)
    self.radioButton_5 = QtWidgets.QRadioButton(self.grpJog)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.radioButton_5.sizePolicy().hasHeightForWidth())
    self.radioButton_5.setSizePolicy(sizePolicy)
    self.radioButton_5.setChecked(True)
    self.radioButton_5.setObjectName("radioButton_5")
    self.verticalLayout_10.addWidget(self.radioButton_5)
    self.radioButton_6 = QtWidgets.QRadioButton(self.grpJog)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.radioButton_6.sizePolicy().hasHeightForWidth())
    self.radioButton_6.setSizePolicy(sizePolicy)
    self.radioButton_6.setObjectName("radioButton_6")
    self.verticalLayout_10.addWidget(self.radioButton_6)
    self.radioButton_7 = QtWidgets.QRadioButton(self.grpJog)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.radioButton_7.sizePolicy().hasHeightForWidth())
    self.radioButton_7.setSizePolicy(sizePolicy)
    self.radioButton_7.setObjectName("radioButton_7")
    self.verticalLayout_10.addWidget(self.radioButton_7)
    self.radioButton_8 = QtWidgets.QRadioButton(self.grpJog)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.radioButton_8.sizePolicy().hasHeightForWidth())
    self.radioButton_8.setSizePolicy(sizePolicy)
    self.radioButton_8.setObjectName("radioButton_8")
    self.verticalLayout_10.addWidget(self.radioButton_8)
    self.radioButton_9 = QtWidgets.QRadioButton(self.grpJog)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.radioButton_9.sizePolicy().hasHeightForWidth())
    self.radioButton_9.setSizePolicy(sizePolicy)
    self.radioButton_9.setObjectName("radioButton_9")
    self.verticalLayout_10.addWidget(self.radioButton_9)
    self.horizontalLayout_16.addLayout(self.verticalLayout_10)
    self.progressBufferState = QtWidgets.QProgressBar(self.grpJog)
    self.progressBufferState.setMaximum(128)
    self.progressBufferState.setProperty("value", 0)
    self.progressBufferState.setOrientation(QtCore.Qt.Vertical)
    self.progressBufferState.setFormat("")
    self.progressBufferState.setObjectName("progressBufferState")
    self.horizontalLayout_16.addWidget(self.progressBufferState)
    self.verticalLayout_9.addWidget(self.grpJog)
    self.grpConnexion = QtWidgets.QGroupBox(self.grpCommandes)
    self.grpConnexion.setObjectName("grpConnexion")
    self.gridLayout = QtWidgets.QGridLayout(self.grpConnexion)
    self.gridLayout.setContentsMargins(4, 0, 4, 0)
    self.gridLayout.setHorizontalSpacing(0)
    self.gridLayout.setVerticalSpacing(2)
    self.gridLayout.setObjectName("gridLayout")
    self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_12.setSpacing(0)
    self.horizontalLayout_12.setObjectName("horizontalLayout_12")
    self.label = QtWidgets.QLabel(self.grpConnexion)
    self.label.setMinimumSize(QtCore.QSize(0, 0))
    self.label.setObjectName("label")
    self.horizontalLayout_12.addWidget(self.label)
    self.cmbPort = QtWidgets.QComboBox(self.grpConnexion)
    self.cmbPort.setMinimumSize(QtCore.QSize(158, 23))
    self.cmbPort.setEditable(True)
    self.cmbPort.setObjectName("cmbPort")
    self.horizontalLayout_12.addWidget(self.cmbPort)
    self.btnRefresh = QtWidgets.QPushButton(self.grpConnexion)
    self.btnRefresh.setMaximumSize(QtCore.QSize(25, 16777215))
    self.btnRefresh.setText("")
    icon3 = QtGui.QIcon()
    icon3.addPixmap(QtGui.QPixmap("images/btnRefresh.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.btnRefresh.setIcon(icon3)
    self.btnRefresh.setObjectName("btnRefresh")
    self.horizontalLayout_12.addWidget(self.btnRefresh)
    self.gridLayout.addLayout(self.horizontalLayout_12, 0, 0, 1, 1)
    self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_22.setObjectName("horizontalLayout_22")
    self.label_2 = QtWidgets.QLabel(self.grpConnexion)
    self.label_2.setMinimumSize(QtCore.QSize(0, 0))
    self.label_2.setObjectName("label_2")
    self.horizontalLayout_22.addWidget(self.label_2)
    self.cmbBauds = QtWidgets.QComboBox(self.grpConnexion)
    self.cmbBauds.setMinimumSize(QtCore.QSize(158, 23))
    self.cmbBauds.setObjectName("cmbBauds")
    self.horizontalLayout_22.addWidget(self.cmbBauds)
    self.gridLayout.addLayout(self.horizontalLayout_22, 1, 0, 1, 1)
    self.horizontalLayout = QtWidgets.QHBoxLayout()
    self.horizontalLayout.setObjectName("horizontalLayout")
    self.lblConnectStatus = QtWidgets.QLabel(self.grpConnexion)
    self.lblConnectStatus.setMinimumSize(QtCore.QSize(180, 0))
    self.lblConnectStatus.setObjectName("lblConnectStatus")
    self.horizontalLayout.addWidget(self.lblConnectStatus)
    self.btnConnect = QtWidgets.QPushButton(self.grpConnexion)
    self.btnConnect.setMinimumSize(QtCore.QSize(0, 23))
    self.btnConnect.setObjectName("btnConnect")
    self.horizontalLayout.addWidget(self.btnConnect)
    self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
    self.verticalLayout_9.addWidget(self.grpConnexion)
    spacerItem2 = QtWidgets.QSpacerItem(18, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.verticalLayout_9.addItem(spacerItem2)
    self.horizontalLayout_17.addWidget(self.grpCommandes)
    self.frmStatus = QtWidgets.QFrame(self.centralwidget)
    self.frmStatus.setFrameShape(QtWidgets.QFrame.Box)
    self.frmStatus.setLineWidth(1)
    self.frmStatus.setObjectName("frmStatus")
    self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frmStatus)
    self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
    self.verticalLayout_11.setSpacing(0)
    self.verticalLayout_11.setObjectName("verticalLayout_11")
    self.grpStatus = QtWidgets.QFrame(self.frmStatus)
    self.grpStatus.setMinimumSize(QtCore.QSize(695, 0))
    self.grpStatus.setMaximumSize(QtCore.QSize(16777215, 16777215))
    self.grpStatus.setFrameShape(QtWidgets.QFrame.Box)
    self.grpStatus.setObjectName("grpStatus")
    self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.grpStatus)
    self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
    self.verticalLayout_5.setSpacing(0)
    self.verticalLayout_5.setObjectName("verticalLayout_5")
    self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_2.setSpacing(0)
    self.horizontalLayout_2.setObjectName("horizontalLayout_2")
    self.frmMPos = QtWidgets.QFrame(self.grpStatus)
    self.frmMPos.setMinimumSize(QtCore.QSize(0, 220))
    self.frmMPos.setStyleSheet("background-color: rgb(248, 255, 192);\n"
"color: rgb(0, 0, 63);")
    self.frmMPos.setFrameShape(QtWidgets.QFrame.Box)
    self.frmMPos.setFrameShadow(QtWidgets.QFrame.Plain)
    self.frmMPos.setObjectName("frmMPos")
    self.gridLayout_2 = QtWidgets.QGridLayout(self.frmMPos)
    self.gridLayout_2.setContentsMargins(6, 0, 6, 0)
    self.gridLayout_2.setSpacing(0)
    self.gridLayout_2.setObjectName("gridLayout_2")
    self.label_3 = QtWidgets.QLabel(self.frmMPos)
    self.label_3.setMaximumSize(QtCore.QSize(25, 16777215))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(20)
    self.label_3.setFont(font)
    self.label_3.setObjectName("label_3")
    self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
    self.lblPosX = QtWidgets.QLabel(self.frmMPos)
    self.lblPosX.setMinimumSize(QtCore.QSize(170, 0))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(20)
    self.lblPosX.setFont(font)
    self.lblPosX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lblPosX.setObjectName("lblPosX")
    self.gridLayout_2.addWidget(self.lblPosX, 0, 1, 1, 1)
    self.label_4 = QtWidgets.QLabel(self.frmMPos)
    self.label_4.setMaximumSize(QtCore.QSize(25, 16777215))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(20)
    self.label_4.setFont(font)
    self.label_4.setObjectName("label_4")
    self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
    self.lblPosY = QtWidgets.QLabel(self.frmMPos)
    self.lblPosY.setMinimumSize(QtCore.QSize(170, 0))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(20)
    self.lblPosY.setFont(font)
    self.lblPosY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lblPosY.setObjectName("lblPosY")
    self.gridLayout_2.addWidget(self.lblPosY, 1, 1, 1, 1)
    self.label_5 = QtWidgets.QLabel(self.frmMPos)
    self.label_5.setMaximumSize(QtCore.QSize(25, 16777215))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(20)
    self.label_5.setFont(font)
    self.label_5.setObjectName("label_5")
    self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
    self.lblPosZ = QtWidgets.QLabel(self.frmMPos)
    self.lblPosZ.setMinimumSize(QtCore.QSize(170, 0))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(20)
    self.lblPosZ.setFont(font)
    self.lblPosZ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lblPosZ.setObjectName("lblPosZ")
    self.gridLayout_2.addWidget(self.lblPosZ, 2, 1, 1, 1)
    self.label_6 = QtWidgets.QLabel(self.frmMPos)
    self.label_6.setMaximumSize(QtCore.QSize(25, 16777215))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(20)
    self.label_6.setFont(font)
    self.label_6.setObjectName("label_6")
    self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
    self.lblPosA = QtWidgets.QLabel(self.frmMPos)
    self.lblPosA.setMinimumSize(QtCore.QSize(170, 0))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(20)
    self.lblPosA.setFont(font)
    self.lblPosA.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lblPosA.setObjectName("lblPosA")
    self.gridLayout_2.addWidget(self.lblPosA, 3, 1, 1, 1)
    self.label_7 = QtWidgets.QLabel(self.frmMPos)
    self.label_7.setMaximumSize(QtCore.QSize(25, 16777215))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(20)
    self.label_7.setFont(font)
    self.label_7.setObjectName("label_7")
    self.gridLayout_2.addWidget(self.label_7, 4, 0, 1, 1)
    self.lblPosB = QtWidgets.QLabel(self.frmMPos)
    self.lblPosB.setMinimumSize(QtCore.QSize(170, 0))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(20)
    self.lblPosB.setFont(font)
    self.lblPosB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lblPosB.setObjectName("lblPosB")
    self.gridLayout_2.addWidget(self.lblPosB, 4, 1, 1, 1)
    self.label_26 = QtWidgets.QLabel(self.frmMPos)
    self.label_26.setMaximumSize(QtCore.QSize(25, 16777215))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(20)
    self.label_26.setFont(font)
    self.label_26.setStyleSheet("color: rgb(224, 224, 230);")
    self.label_26.setObjectName("label_26")
    self.gridLayout_2.addWidget(self.label_26, 5, 0, 1, 1)
    self.lblPosC = QtWidgets.QLabel(self.frmMPos)
    self.lblPosC.setMinimumSize(QtCore.QSize(170, 0))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(20)
    self.lblPosC.setFont(font)
    self.lblPosC.setStyleSheet("color: rgb(224, 224, 230);")
    self.lblPosC.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lblPosC.setObjectName("lblPosC")
    self.gridLayout_2.addWidget(self.lblPosC, 5, 1, 1, 1)
    self.horizontalLayout_2.addWidget(self.frmMPos)
    self.frmMStatus = QtWidgets.QFrame(self.grpStatus)
    self.frmMStatus.setStyleSheet("background-color: rgb(248, 255, 192);\n"
"color: rgb(0, 0, 63);")
    self.frmMStatus.setFrameShape(QtWidgets.QFrame.Box)
    self.frmMStatus.setFrameShadow(QtWidgets.QFrame.Plain)
    self.frmMStatus.setObjectName("frmMStatus")
    self.gridLayout_4 = QtWidgets.QGridLayout(self.frmMStatus)
    self.gridLayout_4.setContentsMargins(6, 4, 6, 4)
    self.gridLayout_4.setVerticalSpacing(2)
    self.gridLayout_4.setObjectName("gridLayout_4")
    self.label_27 = QtWidgets.QLabel(self.frmMStatus)
    self.label_27.setObjectName("label_27")
    self.gridLayout_4.addWidget(self.label_27, 0, 0, 1, 1)
    self.lblEtat = QtWidgets.QLabel(self.frmMStatus)
    self.lblEtat.setMinimumSize(QtCore.QSize(87, 0))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(16)
    font.setBold(True)
    font.setWeight(75)
    self.lblEtat.setFont(font)
    self.lblEtat.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.lblEtat.setStyleSheet("background-color: rgb(0, 0, 63);\n"
"color: rgb(248, 255, 192);")
    self.lblEtat.setFrameShape(QtWidgets.QFrame.Box)
    self.lblEtat.setFrameShadow(QtWidgets.QFrame.Plain)
    self.lblEtat.setAlignment(QtCore.Qt.AlignCenter)
    self.lblEtat.setObjectName("lblEtat")
    self.gridLayout_4.addWidget(self.lblEtat, 0, 1, 1, 1)
    self.label_12 = QtWidgets.QLabel(self.frmMStatus)
    self.label_12.setObjectName("label_12")
    self.gridLayout_4.addWidget(self.label_12, 1, 0, 1, 1)
    self.lblPlan = QtWidgets.QLabel(self.frmMStatus)
    self.lblPlan.setMinimumSize(QtCore.QSize(87, 27))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(16)
    font.setBold(True)
    font.setWeight(75)
    self.lblPlan.setFont(font)
    self.lblPlan.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.lblPlan.setStyleSheet("background-color: rgb(0, 0, 63);\n"
"color: rgb(248, 255, 192);\n"
"QToolType {\n"
"  background-color: rgb(248, 255, 192);\n"
"  color: rgb(0, 0, 63);\n"
"}")
    self.lblPlan.setFrameShape(QtWidgets.QFrame.Box)
    self.lblPlan.setFrameShadow(QtWidgets.QFrame.Plain)
    self.lblPlan.setAlignment(QtCore.Qt.AlignCenter)
    self.lblPlan.setObjectName("lblPlan")
    self.gridLayout_4.addWidget(self.lblPlan, 1, 1, 1, 1)
    self.label_17 = QtWidgets.QLabel(self.frmMStatus)
    self.label_17.setObjectName("label_17")
    self.gridLayout_4.addWidget(self.label_17, 1, 2, 1, 1)
    self.lblBroche = QtWidgets.QLabel(self.frmMStatus)
    self.lblBroche.setMinimumSize(QtCore.QSize(87, 27))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(16)
    font.setBold(True)
    font.setWeight(75)
    self.lblBroche.setFont(font)
    self.lblBroche.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.lblBroche.setStyleSheet("background-color: rgb(0, 0, 63);\n"
"color: rgb(248, 255, 192);")
    self.lblBroche.setFrameShape(QtWidgets.QFrame.Box)
    self.lblBroche.setFrameShadow(QtWidgets.QFrame.Plain)
    self.lblBroche.setAlignment(QtCore.Qt.AlignCenter)
    self.lblBroche.setObjectName("lblBroche")
    self.gridLayout_4.addWidget(self.lblBroche, 1, 3, 1, 1)
    self.label_14 = QtWidgets.QLabel(self.frmMStatus)
    self.label_14.setObjectName("label_14")
    self.gridLayout_4.addWidget(self.label_14, 2, 0, 1, 1)
    self.lblUnites = QtWidgets.QLabel(self.frmMStatus)
    self.lblUnites.setMinimumSize(QtCore.QSize(87, 27))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(16)
    font.setBold(True)
    font.setWeight(75)
    self.lblUnites.setFont(font)
    self.lblUnites.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.lblUnites.setStyleSheet("background-color: rgb(0, 0, 63);\n"
"color: rgb(248, 255, 192);")
    self.lblUnites.setFrameShape(QtWidgets.QFrame.Box)
    self.lblUnites.setFrameShadow(QtWidgets.QFrame.Plain)
    self.lblUnites.setAlignment(QtCore.Qt.AlignCenter)
    self.lblUnites.setObjectName("lblUnites")
    self.gridLayout_4.addWidget(self.lblUnites, 2, 1, 1, 1)
    self.label_18 = QtWidgets.QLabel(self.frmMStatus)
    self.label_18.setObjectName("label_18")
    self.gridLayout_4.addWidget(self.label_18, 2, 2, 1, 1)
    self.lblArrosage = QtWidgets.QLabel(self.frmMStatus)
    self.lblArrosage.setMinimumSize(QtCore.QSize(87, 27))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(16)
    font.setBold(True)
    font.setWeight(75)
    self.lblArrosage.setFont(font)
    self.lblArrosage.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.lblArrosage.setStyleSheet("background-color: rgb(0, 0, 63);\n"
"color: rgb(248, 255, 192);")
    self.lblArrosage.setFrameShape(QtWidgets.QFrame.Box)
    self.lblArrosage.setFrameShadow(QtWidgets.QFrame.Plain)
    self.lblArrosage.setAlignment(QtCore.Qt.AlignCenter)
    self.lblArrosage.setObjectName("lblArrosage")
    self.gridLayout_4.addWidget(self.lblArrosage, 2, 3, 1, 1)
    self.label_15 = QtWidgets.QLabel(self.frmMStatus)
    self.label_15.setObjectName("label_15")
    self.gridLayout_4.addWidget(self.label_15, 3, 0, 1, 1)
    self.lblCoord = QtWidgets.QLabel(self.frmMStatus)
    self.lblCoord.setMinimumSize(QtCore.QSize(87, 27))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(16)
    font.setBold(True)
    font.setWeight(75)
    self.lblCoord.setFont(font)
    self.lblCoord.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.lblCoord.setStyleSheet("background-color: rgb(0, 0, 63);\n"
"color: rgb(248, 255, 192);")
    self.lblCoord.setFrameShape(QtWidgets.QFrame.Box)
    self.lblCoord.setFrameShadow(QtWidgets.QFrame.Plain)
    self.lblCoord.setAlignment(QtCore.Qt.AlignCenter)
    self.lblCoord.setObjectName("lblCoord")
    self.gridLayout_4.addWidget(self.lblCoord, 3, 1, 1, 1)
    self.label_19 = QtWidgets.QLabel(self.frmMStatus)
    self.label_19.setObjectName("label_19")
    self.gridLayout_4.addWidget(self.label_19, 3, 2, 1, 1)
    self.lblOutil = QtWidgets.QLabel(self.frmMStatus)
    self.lblOutil.setMinimumSize(QtCore.QSize(87, 27))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(16)
    font.setBold(True)
    font.setWeight(75)
    self.lblOutil.setFont(font)
    self.lblOutil.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.lblOutil.setStyleSheet("background-color: rgb(0, 0, 63);\n"
"color: rgb(248, 255, 192);")
    self.lblOutil.setFrameShape(QtWidgets.QFrame.Box)
    self.lblOutil.setFrameShadow(QtWidgets.QFrame.Plain)
    self.lblOutil.setAlignment(QtCore.Qt.AlignCenter)
    self.lblOutil.setObjectName("lblOutil")
    self.gridLayout_4.addWidget(self.lblOutil, 3, 3, 1, 1)
    self.label_13 = QtWidgets.QLabel(self.frmMStatus)
    self.label_13.setObjectName("label_13")
    self.gridLayout_4.addWidget(self.label_13, 4, 0, 1, 1)
    self.lblDeplacements = QtWidgets.QLabel(self.frmMStatus)
    self.lblDeplacements.setMinimumSize(QtCore.QSize(87, 27))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(16)
    font.setBold(True)
    font.setWeight(75)
    self.lblDeplacements.setFont(font)
    self.lblDeplacements.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.lblDeplacements.setStyleSheet("background-color: rgb(0, 0, 63);\n"
"color: rgb(248, 255, 192);")
    self.lblDeplacements.setFrameShape(QtWidgets.QFrame.Box)
    self.lblDeplacements.setFrameShadow(QtWidgets.QFrame.Plain)
    self.lblDeplacements.setAlignment(QtCore.Qt.AlignCenter)
    self.lblDeplacements.setObjectName("lblDeplacements")
    self.gridLayout_4.addWidget(self.lblDeplacements, 4, 1, 1, 1)
    self.label_21 = QtWidgets.QLabel(self.frmMStatus)
    self.label_21.setObjectName("label_21")
    self.gridLayout_4.addWidget(self.label_21, 4, 2, 1, 1)
    self.lblRotation = QtWidgets.QLabel(self.frmMStatus)
    self.lblRotation.setMinimumSize(QtCore.QSize(87, 27))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(16)
    font.setBold(True)
    font.setWeight(75)
    self.lblRotation.setFont(font)
    self.lblRotation.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.lblRotation.setStyleSheet("background-color: rgb(0, 0, 63);\n"
"color: rgb(248, 255, 192);")
    self.lblRotation.setFrameShape(QtWidgets.QFrame.Box)
    self.lblRotation.setFrameShadow(QtWidgets.QFrame.Plain)
    self.lblRotation.setAlignment(QtCore.Qt.AlignCenter)
    self.lblRotation.setObjectName("lblRotation")
    self.gridLayout_4.addWidget(self.lblRotation, 4, 3, 1, 1)
    self.label_16 = QtWidgets.QLabel(self.frmMStatus)
    self.label_16.setObjectName("label_16")
    self.gridLayout_4.addWidget(self.label_16, 5, 0, 1, 1)
    self.lblVitesse = QtWidgets.QLabel(self.frmMStatus)
    self.lblVitesse.setMinimumSize(QtCore.QSize(87, 27))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(16)
    font.setBold(True)
    font.setWeight(75)
    self.lblVitesse.setFont(font)
    self.lblVitesse.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.lblVitesse.setStyleSheet("background-color: rgb(0, 0, 63);\n"
"color: rgb(248, 255, 192);")
    self.lblVitesse.setFrameShape(QtWidgets.QFrame.Box)
    self.lblVitesse.setFrameShadow(QtWidgets.QFrame.Plain)
    self.lblVitesse.setAlignment(QtCore.Qt.AlignCenter)
    self.lblVitesse.setObjectName("lblVitesse")
    self.gridLayout_4.addWidget(self.lblVitesse, 5, 1, 1, 1)
    self.label_20 = QtWidgets.QLabel(self.frmMStatus)
    self.label_20.setObjectName("label_20")
    self.gridLayout_4.addWidget(self.label_20, 5, 2, 1, 1)
    self.lblAvance = QtWidgets.QLabel(self.frmMStatus)
    self.lblAvance.setMinimumSize(QtCore.QSize(87, 27))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(16)
    font.setBold(True)
    font.setWeight(75)
    self.lblAvance.setFont(font)
    self.lblAvance.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.lblAvance.setStyleSheet("background-color: rgb(0, 0, 63);\n"
"color: rgb(248, 255, 192);")
    self.lblAvance.setFrameShape(QtWidgets.QFrame.Box)
    self.lblAvance.setFrameShadow(QtWidgets.QFrame.Plain)
    self.lblAvance.setAlignment(QtCore.Qt.AlignCenter)
    self.lblAvance.setObjectName("lblAvance")
    self.gridLayout_4.addWidget(self.lblAvance, 5, 3, 1, 1)
    self.horizontalLayout_2.addWidget(self.frmMStatus)
    self.verticalLayout_5.addLayout(self.horizontalLayout_2)
    self.frmCoordOffsets = QtWidgets.QFrame(self.grpStatus)
    self.frmCoordOffsets.setStyleSheet("background-color: rgb(248, 255, 192);\n"
"color: rgb(0, 0, 63);")
    self.frmCoordOffsets.setFrameShape(QtWidgets.QFrame.Box)
    self.frmCoordOffsets.setFrameShadow(QtWidgets.QFrame.Plain)
    self.frmCoordOffsets.setObjectName("frmCoordOffsets")
    self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frmCoordOffsets)
    self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
    self.horizontalLayout_3.setSpacing(4)
    self.horizontalLayout_3.setObjectName("horizontalLayout_3")
    self.frame_8 = QtWidgets.QFrame(self.frmCoordOffsets)
    self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
    self.frame_8.setObjectName("frame_8")
    self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_8)
    self.verticalLayout_4.setContentsMargins(2, 0, 0, 0)
    self.verticalLayout_4.setSpacing(0)
    self.verticalLayout_4.setObjectName("verticalLayout_4")
    self.lblG5xMode = QtWidgets.QLabel(self.frame_8)
    self.lblG5xMode.setMinimumSize(QtCore.QSize(0, 27))
    self.lblG5xMode.setObjectName("lblG5xMode")
    self.verticalLayout_4.addWidget(self.lblG5xMode)
    self.lblOffsetActif = QtWidgets.QLabel(self.frame_8)
    self.lblOffsetActif.setObjectName("lblOffsetActif")
    self.verticalLayout_4.addWidget(self.lblOffsetActif)
    self.lblOffsetG92 = QtWidgets.QLabel(self.frame_8)
    self.lblOffsetG92.setObjectName("lblOffsetG92")
    self.verticalLayout_4.addWidget(self.lblOffsetG92)
    self.lblOffsetWco = QtWidgets.QLabel(self.frame_8)
    self.lblOffsetWco.setObjectName("lblOffsetWco")
    self.verticalLayout_4.addWidget(self.lblOffsetWco)
    self.horizontalLayout_3.addWidget(self.frame_8)
    self.verticalLayout_3 = QtWidgets.QVBoxLayout()
    self.verticalLayout_3.setSpacing(0)
    self.verticalLayout_3.setObjectName("verticalLayout_3")
    self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_6.setContentsMargins(-1, -1, 2, -1)
    self.horizontalLayout_6.setSpacing(2)
    self.horizontalLayout_6.setObjectName("horizontalLayout_6")
    self.lblG54 = QtWidgets.QLabel(self.frmCoordOffsets)
    self.lblG54.setMinimumSize(QtCore.QSize(87, 27))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(16)
    font.setBold(True)
    font.setWeight(75)
    self.lblG54.setFont(font)
    self.lblG54.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.lblG54.setStyleSheet("background-color: rgb(0, 0, 63);\n"
"color: rgb(248, 255, 192);")
    self.lblG54.setFrameShape(QtWidgets.QFrame.Box)
    self.lblG54.setFrameShadow(QtWidgets.QFrame.Plain)
    self.lblG54.setAlignment(QtCore.Qt.AlignCenter)
    self.lblG54.setObjectName("lblG54")
    self.horizontalLayout_6.addWidget(self.lblG54)
    self.lblG55 = QtWidgets.QLabel(self.frmCoordOffsets)
    self.lblG55.setMinimumSize(QtCore.QSize(87, 27))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(16)
    self.lblG55.setFont(font)
    self.lblG55.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.lblG55.setStyleSheet("background-color: rgb(248, 255, 192);\n"
"color: rgb(0, 0, 63);\n"
"")
    self.lblG55.setFrameShape(QtWidgets.QFrame.Box)
    self.lblG55.setFrameShadow(QtWidgets.QFrame.Plain)
    self.lblG55.setAlignment(QtCore.Qt.AlignCenter)
    self.lblG55.setObjectName("lblG55")
    self.horizontalLayout_6.addWidget(self.lblG55)
    self.lblG56 = QtWidgets.QLabel(self.frmCoordOffsets)
    self.lblG56.setMinimumSize(QtCore.QSize(87, 27))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(16)
    self.lblG56.setFont(font)
    self.lblG56.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.lblG56.setStyleSheet("background-color: rgb(248, 255, 192);\n"
"color: rgb(0, 0, 63);\n"
"")
    self.lblG56.setFrameShape(QtWidgets.QFrame.Box)
    self.lblG56.setFrameShadow(QtWidgets.QFrame.Plain)
    self.lblG56.setAlignment(QtCore.Qt.AlignCenter)
    self.lblG56.setObjectName("lblG56")
    self.horizontalLayout_6.addWidget(self.lblG56)
    self.lblG57 = QtWidgets.QLabel(self.frmCoordOffsets)
    self.lblG57.setMinimumSize(QtCore.QSize(87, 27))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(16)
    self.lblG57.setFont(font)
    self.lblG57.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.lblG57.setStyleSheet("background-color: rgb(248, 255, 192);\n"
"color: rgb(0, 0, 63);\n"
"")
    self.lblG57.setFrameShape(QtWidgets.QFrame.Box)
    self.lblG57.setFrameShadow(QtWidgets.QFrame.Plain)
    self.lblG57.setAlignment(QtCore.Qt.AlignCenter)
    self.lblG57.setObjectName("lblG57")
    self.horizontalLayout_6.addWidget(self.lblG57)
    self.lblG58 = QtWidgets.QLabel(self.frmCoordOffsets)
    self.lblG58.setMinimumSize(QtCore.QSize(87, 27))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(16)
    self.lblG58.setFont(font)
    self.lblG58.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.lblG58.setStyleSheet("background-color: rgb(248, 255, 192);\n"
"color: rgb(0, 0, 63);\n"
"")
    self.lblG58.setFrameShape(QtWidgets.QFrame.Box)
    self.lblG58.setFrameShadow(QtWidgets.QFrame.Plain)
    self.lblG58.setLineWidth(1)
    self.lblG58.setAlignment(QtCore.Qt.AlignCenter)
    self.lblG58.setObjectName("lblG58")
    self.horizontalLayout_6.addWidget(self.lblG58)
    self.lblG59 = QtWidgets.QLabel(self.frmCoordOffsets)
    self.lblG59.setMinimumSize(QtCore.QSize(87, 27))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(16)
    self.lblG59.setFont(font)
    self.lblG59.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.lblG59.setStyleSheet("background-color: rgb(248, 255, 192);\n"
"color: rgb(0, 0, 63);\n"
"")
    self.lblG59.setFrameShape(QtWidgets.QFrame.Box)
    self.lblG59.setFrameShadow(QtWidgets.QFrame.Plain)
    self.lblG59.setAlignment(QtCore.Qt.AlignCenter)
    self.lblG59.setObjectName("lblG59")
    self.horizontalLayout_6.addWidget(self.lblG59)
    self.verticalLayout_3.addLayout(self.horizontalLayout_6)
    self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_5.setContentsMargins(-1, -1, 2, -1)
    self.horizontalLayout_5.setSpacing(2)
    self.horizontalLayout_5.setObjectName("horizontalLayout_5")
    self.lblG5xX = QtWidgets.QLabel(self.frmCoordOffsets)
    self.lblG5xX.setMinimumSize(QtCore.QSize(99, 0))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(12)
    self.lblG5xX.setFont(font)
    self.lblG5xX.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.lblG5xX.setFrameShadow(QtWidgets.QFrame.Sunken)
    self.lblG5xX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lblG5xX.setObjectName("lblG5xX")
    self.horizontalLayout_5.addWidget(self.lblG5xX)
    self.lblG5xY = QtWidgets.QLabel(self.frmCoordOffsets)
    self.lblG5xY.setMinimumSize(QtCore.QSize(99, 0))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(12)
    self.lblG5xY.setFont(font)
    self.lblG5xY.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.lblG5xY.setFrameShadow(QtWidgets.QFrame.Sunken)
    self.lblG5xY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lblG5xY.setObjectName("lblG5xY")
    self.horizontalLayout_5.addWidget(self.lblG5xY)
    self.lblG5xZ = QtWidgets.QLabel(self.frmCoordOffsets)
    self.lblG5xZ.setMinimumSize(QtCore.QSize(99, 0))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(12)
    self.lblG5xZ.setFont(font)
    self.lblG5xZ.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.lblG5xZ.setFrameShadow(QtWidgets.QFrame.Sunken)
    self.lblG5xZ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lblG5xZ.setObjectName("lblG5xZ")
    self.horizontalLayout_5.addWidget(self.lblG5xZ)
    self.lblG5xA = QtWidgets.QLabel(self.frmCoordOffsets)
    self.lblG5xA.setMinimumSize(QtCore.QSize(99, 0))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(12)
    self.lblG5xA.setFont(font)
    self.lblG5xA.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.lblG5xA.setFrameShadow(QtWidgets.QFrame.Sunken)
    self.lblG5xA.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lblG5xA.setObjectName("lblG5xA")
    self.horizontalLayout_5.addWidget(self.lblG5xA)
    self.lblG5xB = QtWidgets.QLabel(self.frmCoordOffsets)
    self.lblG5xB.setMinimumSize(QtCore.QSize(99, 0))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(12)
    self.lblG5xB.setFont(font)
    self.lblG5xB.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.lblG5xB.setFrameShadow(QtWidgets.QFrame.Sunken)
    self.lblG5xB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lblG5xB.setObjectName("lblG5xB")
    self.horizontalLayout_5.addWidget(self.lblG5xB)
    self.lblG5xC = QtWidgets.QLabel(self.frmCoordOffsets)
    self.lblG5xC.setMinimumSize(QtCore.QSize(99, 0))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(12)
    self.lblG5xC.setFont(font)
    self.lblG5xC.setStyleSheet("color: rgb(224, 224, 230);")
    self.lblG5xC.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.lblG5xC.setFrameShadow(QtWidgets.QFrame.Sunken)
    self.lblG5xC.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lblG5xC.setObjectName("lblG5xC")
    self.horizontalLayout_5.addWidget(self.lblG5xC)
    self.verticalLayout_3.addLayout(self.horizontalLayout_5)
    self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_4.setContentsMargins(-1, -1, 2, -1)
    self.horizontalLayout_4.setSpacing(2)
    self.horizontalLayout_4.setObjectName("horizontalLayout_4")
    self.lblG92X = QtWidgets.QLabel(self.frmCoordOffsets)
    self.lblG92X.setMinimumSize(QtCore.QSize(99, 0))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(12)
    self.lblG92X.setFont(font)
    self.lblG92X.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.lblG92X.setFrameShadow(QtWidgets.QFrame.Sunken)
    self.lblG92X.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lblG92X.setObjectName("lblG92X")
    self.horizontalLayout_4.addWidget(self.lblG92X)
    self.lblG92Y = QtWidgets.QLabel(self.frmCoordOffsets)
    self.lblG92Y.setMinimumSize(QtCore.QSize(99, 0))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(12)
    self.lblG92Y.setFont(font)
    self.lblG92Y.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.lblG92Y.setFrameShadow(QtWidgets.QFrame.Sunken)
    self.lblG92Y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lblG92Y.setObjectName("lblG92Y")
    self.horizontalLayout_4.addWidget(self.lblG92Y)
    self.lblG92Z = QtWidgets.QLabel(self.frmCoordOffsets)
    self.lblG92Z.setMinimumSize(QtCore.QSize(99, 0))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(12)
    self.lblG92Z.setFont(font)
    self.lblG92Z.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.lblG92Z.setFrameShadow(QtWidgets.QFrame.Sunken)
    self.lblG92Z.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lblG92Z.setObjectName("lblG92Z")
    self.horizontalLayout_4.addWidget(self.lblG92Z)
    self.lblG92A = QtWidgets.QLabel(self.frmCoordOffsets)
    self.lblG92A.setMinimumSize(QtCore.QSize(99, 0))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(12)
    self.lblG92A.setFont(font)
    self.lblG92A.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.lblG92A.setFrameShadow(QtWidgets.QFrame.Sunken)
    self.lblG92A.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lblG92A.setObjectName("lblG92A")
    self.horizontalLayout_4.addWidget(self.lblG92A)
    self.lblG92B = QtWidgets.QLabel(self.frmCoordOffsets)
    self.lblG92B.setMinimumSize(QtCore.QSize(99, 0))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(12)
    self.lblG92B.setFont(font)
    self.lblG92B.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.lblG92B.setFrameShadow(QtWidgets.QFrame.Sunken)
    self.lblG92B.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lblG92B.setObjectName("lblG92B")
    self.horizontalLayout_4.addWidget(self.lblG92B)
    self.lblG92C = QtWidgets.QLabel(self.frmCoordOffsets)
    self.lblG92C.setMinimumSize(QtCore.QSize(99, 0))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(12)
    self.lblG92C.setFont(font)
    self.lblG92C.setStyleSheet("color: rgb(224, 224, 230);")
    self.lblG92C.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.lblG92C.setFrameShadow(QtWidgets.QFrame.Sunken)
    self.lblG92C.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lblG92C.setObjectName("lblG92C")
    self.horizontalLayout_4.addWidget(self.lblG92C)
    self.verticalLayout_3.addLayout(self.horizontalLayout_4)
    self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
    self.horizontalLayout_23.setContentsMargins(-1, -1, 2, -1)
    self.horizontalLayout_23.setSpacing(2)
    self.horizontalLayout_23.setObjectName("horizontalLayout_23")
    self.lblWcoX = QtWidgets.QLabel(self.frmCoordOffsets)
    self.lblWcoX.setMinimumSize(QtCore.QSize(99, 0))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(12)
    self.lblWcoX.setFont(font)
    self.lblWcoX.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.lblWcoX.setFrameShadow(QtWidgets.QFrame.Sunken)
    self.lblWcoX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lblWcoX.setObjectName("lblWcoX")
    self.horizontalLayout_23.addWidget(self.lblWcoX)
    self.lblWcoY = QtWidgets.QLabel(self.frmCoordOffsets)
    self.lblWcoY.setMinimumSize(QtCore.QSize(99, 0))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(12)
    self.lblWcoY.setFont(font)
    self.lblWcoY.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.lblWcoY.setFrameShadow(QtWidgets.QFrame.Sunken)
    self.lblWcoY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lblWcoY.setObjectName("lblWcoY")
    self.horizontalLayout_23.addWidget(self.lblWcoY)
    self.lblWcoZ = QtWidgets.QLabel(self.frmCoordOffsets)
    self.lblWcoZ.setMinimumSize(QtCore.QSize(99, 0))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(12)
    self.lblWcoZ.setFont(font)
    self.lblWcoZ.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.lblWcoZ.setFrameShadow(QtWidgets.QFrame.Sunken)
    self.lblWcoZ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lblWcoZ.setObjectName("lblWcoZ")
    self.horizontalLayout_23.addWidget(self.lblWcoZ)
    self.lblWcoA = QtWidgets.QLabel(self.frmCoordOffsets)
    self.lblWcoA.setMinimumSize(QtCore.QSize(99, 0))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(12)
    self.lblWcoA.setFont(font)
    self.lblWcoA.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.lblWcoA.setFrameShadow(QtWidgets.QFrame.Sunken)
    self.lblWcoA.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lblWcoA.setObjectName("lblWcoA")
    self.horizontalLayout_23.addWidget(self.lblWcoA)
    self.lblWcoB = QtWidgets.QLabel(self.frmCoordOffsets)
    self.lblWcoB.setMinimumSize(QtCore.QSize(99, 0))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(12)
    self.lblWcoB.setFont(font)
    self.lblWcoB.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.lblWcoB.setFrameShadow(QtWidgets.QFrame.Sunken)
    self.lblWcoB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lblWcoB.setObjectName("lblWcoB")
    self.horizontalLayout_23.addWidget(self.lblWcoB)
    self.lblWcoC = QtWidgets.QLabel(self.frmCoordOffsets)
    self.lblWcoC.setMinimumSize(QtCore.QSize(99, 0))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(12)
    self.lblWcoC.setFont(font)
    self.lblWcoC.setStyleSheet("color: rgb(224, 224, 230);")
    self.lblWcoC.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.lblWcoC.setFrameShadow(QtWidgets.QFrame.Sunken)
    self.lblWcoC.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lblWcoC.setObjectName("lblWcoC")
    self.horizontalLayout_23.addWidget(self.lblWcoC)
    self.verticalLayout_3.addLayout(self.horizontalLayout_23)
    self.horizontalLayout_3.addLayout(self.verticalLayout_3)
    self.verticalLayout_5.addWidget(self.frmCoordOffsets)
    self.verticalLayout_11.addWidget(self.grpStatus)
    self.frmBoutons = QtWidgets.QFrame(self.frmStatus)
    self.frmBoutons.setEnabled(True)
    self.frmBoutons.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.frmBoutons.setFrameShadow(QtWidgets.QFrame.Plain)
    self.frmBoutons.setLineWidth(0)
    self.frmBoutons.setObjectName("frmBoutons")
    self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frmBoutons)
    self.horizontalLayout_10.setContentsMargins(0, 4, 0, 4)
    self.horizontalLayout_10.setSpacing(4)
    self.horizontalLayout_10.setObjectName("horizontalLayout_10")
    spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.horizontalLayout_10.addItem(spacerItem3)
    self.btnFloodM7 = cnQPushButton(self.frmBoutons)
    self.btnFloodM7.setEnabled(True)
    self.btnFloodM7.setMinimumSize(QtCore.QSize(50, 50))
    self.btnFloodM7.setStyleSheet("border-radius: 25;")
    self.btnFloodM7.setText("")
    icon4 = QtGui.QIcon()
    icon4.addPixmap(QtGui.QPixmap("images/btnFloodM7.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.btnFloodM7.setIcon(icon4)
    self.btnFloodM7.setIconSize(QtCore.QSize(50, 50))
    self.btnFloodM7.setObjectName("btnFloodM7")
    self.horizontalLayout_10.addWidget(self.btnFloodM7)
    self.btnFloodM8 = cnQPushButton(self.frmBoutons)
    self.btnFloodM8.setEnabled(True)
    self.btnFloodM8.setMinimumSize(QtCore.QSize(50, 50))
    self.btnFloodM8.setStyleSheet("border-radius: 25;")
    self.btnFloodM8.setText("")
    icon5 = QtGui.QIcon()
    icon5.addPixmap(QtGui.QPixmap("images/btnFloodM8.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.btnFloodM8.setIcon(icon5)
    self.btnFloodM8.setIconSize(QtCore.QSize(50, 50))
    self.btnFloodM8.setObjectName("btnFloodM8")
    self.horizontalLayout_10.addWidget(self.btnFloodM8)
    self.btnFloodM9 = cnQPushButton(self.frmBoutons)
    self.btnFloodM9.setEnabled(True)
    self.btnFloodM9.setMinimumSize(QtCore.QSize(50, 50))
    self.btnFloodM9.setStyleSheet("border-radius: 25;")
    self.btnFloodM9.setText("")
    icon6 = QtGui.QIcon()
    icon6.addPixmap(QtGui.QPixmap("images/btnFloodM9.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.btnFloodM9.setIcon(icon6)
    self.btnFloodM9.setIconSize(QtCore.QSize(50, 50))
    self.btnFloodM9.setObjectName("btnFloodM9")
    self.horizontalLayout_10.addWidget(self.btnFloodM9)
    spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.horizontalLayout_10.addItem(spacerItem4)
    self.btnSpinM3 = cnQPushButton(self.frmBoutons)
    self.btnSpinM3.setEnabled(True)
    self.btnSpinM3.setMinimumSize(QtCore.QSize(50, 50))
    self.btnSpinM3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.btnSpinM3.setStyleSheet("border-radius: 25;")
    self.btnSpinM3.setText("")
    icon7 = QtGui.QIcon()
    icon7.addPixmap(QtGui.QPixmap("images/btnSpinM3.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.btnSpinM3.setIcon(icon7)
    self.btnSpinM3.setIconSize(QtCore.QSize(50, 50))
    self.btnSpinM3.setObjectName("btnSpinM3")
    self.horizontalLayout_10.addWidget(self.btnSpinM3)
    self.btnSpinM4 = cnQPushButton(self.frmBoutons)
    self.btnSpinM4.setEnabled(True)
    self.btnSpinM4.setMinimumSize(QtCore.QSize(50, 50))
    self.btnSpinM4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.btnSpinM4.setStyleSheet("border-radius: 25;")
    self.btnSpinM4.setText("")
    icon8 = QtGui.QIcon()
    icon8.addPixmap(QtGui.QPixmap("images/btnSpinM4.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.btnSpinM4.setIcon(icon8)
    self.btnSpinM4.setIconSize(QtCore.QSize(50, 50))
    self.btnSpinM4.setObjectName("btnSpinM4")
    self.horizontalLayout_10.addWidget(self.btnSpinM4)
    self.btnSpinM5 = cnQPushButton(self.frmBoutons)
    self.btnSpinM5.setEnabled(True)
    self.btnSpinM5.setMinimumSize(QtCore.QSize(50, 50))
    self.btnSpinM5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.btnSpinM5.setStyleSheet("border-radius: 25;")
    self.btnSpinM5.setText("")
    icon9 = QtGui.QIcon()
    icon9.addPixmap(QtGui.QPixmap("images/btnSpinM5.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.btnSpinM5.setIcon(icon9)
    self.btnSpinM5.setIconSize(QtCore.QSize(50, 50))
    self.btnSpinM5.setObjectName("btnSpinM5")
    self.horizontalLayout_10.addWidget(self.btnSpinM5)
    spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.horizontalLayout_10.addItem(spacerItem5)
    self.btnStart = cnQPushButton(self.frmBoutons)
    self.btnStart.setEnabled(True)
    self.btnStart.setMinimumSize(QtCore.QSize(50, 50))
    self.btnStart.setMaximumSize(QtCore.QSize(16777215, 16777215))
    self.btnStart.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.btnStart.setStyleSheet("border-radius: 25;")
    self.btnStart.setText("")
    icon10 = QtGui.QIcon()
    icon10.addPixmap(QtGui.QPixmap("images/btnStart.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.btnStart.setIcon(icon10)
    self.btnStart.setIconSize(QtCore.QSize(50, 50))
    self.btnStart.setObjectName("btnStart")
    self.horizontalLayout_10.addWidget(self.btnStart)
    self.btnStop = cnQPushButton(self.frmBoutons)
    self.btnStop.setEnabled(True)
    self.btnStop.setMinimumSize(QtCore.QSize(50, 50))
    self.btnStop.setMaximumSize(QtCore.QSize(16777215, 16777215))
    self.btnStop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.btnStop.setStyleSheet("border-radius: 25;")
    self.btnStop.setText("")
    icon11 = QtGui.QIcon()
    icon11.addPixmap(QtGui.QPixmap("images/btnStop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.btnStop.setIcon(icon11)
    self.btnStop.setIconSize(QtCore.QSize(50, 50))
    self.btnStop.setObjectName("btnStop")
    self.horizontalLayout_10.addWidget(self.btnStop)
    spacerItem6 = QtWidgets.QSpacerItem(67, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    self.horizontalLayout_10.addItem(spacerItem6)
    self.verticalLayout_11.addWidget(self.frmBoutons)
    self.grpConsole = QtWidgets.QTabWidget(self.frmStatus)
    self.grpConsole.setObjectName("grpConsole")
    self.tabConsole1 = QtWidgets.QWidget()
    self.tabConsole1.setObjectName("tabConsole1")
    self.gridLayout_5 = QtWidgets.QGridLayout(self.tabConsole1)
    self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
    self.gridLayout_5.setSpacing(0)
    self.gridLayout_5.setObjectName("gridLayout_5")
    self.verticalLayout_6 = QtWidgets.QVBoxLayout()
    self.verticalLayout_6.setSpacing(0)
    self.verticalLayout_6.setObjectName("verticalLayout_6")
    self.txtGrblOutput = QtWidgets.QTextEdit(self.tabConsole1)
    self.txtGrblOutput.setMinimumSize(QtCore.QSize(0, 91))
    self.txtGrblOutput.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
    self.txtGrblOutput.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
    self.txtGrblOutput.setObjectName("txtGrblOutput")
    self.verticalLayout_6.addWidget(self.txtGrblOutput)
    self.gridLayout_5.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
    self.grpConsole.addTab(self.tabConsole1, "")
    self.tabConsole2 = QtWidgets.QWidget()
    self.tabConsole2.setObjectName("tabConsole2")
    self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tabConsole2)
    self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
    self.verticalLayout_12.setSpacing(0)
    self.verticalLayout_12.setObjectName("verticalLayout_12")
    self.txtConsoleOutput = QtWidgets.QTextEdit(self.tabConsole2)
    self.txtConsoleOutput.setMinimumSize(QtCore.QSize(0, 91))
    self.txtConsoleOutput.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
    self.txtConsoleOutput.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
    self.txtConsoleOutput.setObjectName("txtConsoleOutput")
    self.verticalLayout_12.addWidget(self.txtConsoleOutput)
    self.grpConsole.addTab(self.tabConsole2, "")
    self.tabConsole3 = QtWidgets.QWidget()
    self.tabConsole3.setObjectName("tabConsole3")
    self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.tabConsole3)
    self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
    self.horizontalLayout_18.setSpacing(4)
    self.horizontalLayout_18.setObjectName("horizontalLayout_18")
    self.txtDebugOutput = QtWidgets.QTextEdit(self.tabConsole3)
    self.txtDebugOutput.setMinimumSize(QtCore.QSize(0, 91))
    self.txtDebugOutput.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
    self.txtDebugOutput.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
    self.txtDebugOutput.setObjectName("txtDebugOutput")
    self.horizontalLayout_18.addWidget(self.txtDebugOutput)
    self.verticalLayout_13 = QtWidgets.QVBoxLayout()
    self.verticalLayout_13.setSpacing(4)
    self.verticalLayout_13.setObjectName("verticalLayout_13")
    spacerItem7 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    self.verticalLayout_13.addItem(spacerItem7)
    self.btnStartTimer = QtWidgets.QPushButton(self.tabConsole3)
    self.btnStartTimer.setObjectName("btnStartTimer")
    self.verticalLayout_13.addWidget(self.btnStartTimer)
    self.btnStopTimer = QtWidgets.QPushButton(self.tabConsole3)
    self.btnStopTimer.setObjectName("btnStopTimer")
    self.verticalLayout_13.addWidget(self.btnStopTimer)
    self.btnClearDebug = QtWidgets.QPushButton(self.tabConsole3)
    self.btnClearDebug.setObjectName("btnClearDebug")
    self.verticalLayout_13.addWidget(self.btnClearDebug)
    self.horizontalLayout_18.addLayout(self.verticalLayout_13)
    self.grpConsole.addTab(self.tabConsole3, "")
    self.verticalLayout_11.addWidget(self.grpConsole)
    self.frmGcodeInput = QtWidgets.QFrame(self.frmStatus)
    self.frmGcodeInput.setEnabled(False)
    self.frmGcodeInput.setObjectName("frmGcodeInput")
    self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frmGcodeInput)
    self.horizontalLayout_7.setObjectName("horizontalLayout_7")
    self.label_8 = QtWidgets.QLabel(self.frmGcodeInput)
    self.label_8.setObjectName("label_8")
    self.horizontalLayout_7.addWidget(self.label_8)
    self.txtGCode = gcodeQLineEdit(self.frmGcodeInput)
    self.txtGCode.setMinimumSize(QtCore.QSize(0, 25))
    self.txtGCode.setFocusPolicy(QtCore.Qt.StrongFocus)
    self.txtGCode.setClearButtonEnabled(True)
    self.txtGCode.setObjectName("txtGCode")
    self.horizontalLayout_7.addWidget(self.txtGCode)
    self.btnSend = QtWidgets.QPushButton(self.frmGcodeInput)
    self.btnSend.setMinimumSize(QtCore.QSize(0, 23))
    self.btnSend.setObjectName("btnSend")
    self.horizontalLayout_7.addWidget(self.btnSend)
    self.verticalLayout_11.addWidget(self.frmGcodeInput)
    self.horizontalLayout_17.addWidget(self.frmStatus)
    mainWindow.setCentralWidget(self.centralwidget)
    self.mnuBar = QtWidgets.QMenuBar(mainWindow)
    self.mnuBar.setGeometry(QtCore.QRect(0, 0, 1040, 20))
    self.mnuBar.setObjectName("mnuBar")
    self.mnuApplication = QtWidgets.QMenu(self.mnuBar)
    self.mnuApplication.setObjectName("mnuApplication")
    self.menuOptions = QtWidgets.QMenu(self.mnuBar)
    self.menuOptions.setObjectName("menuOptions")
    mainWindow.setMenuBar(self.mnuBar)
    self.statusBar = QtWidgets.QStatusBar(mainWindow)
    self.statusBar.setObjectName("statusBar")
    mainWindow.setStatusBar(self.statusBar)
    self.mnuAppOuvrir = QtWidgets.QAction(mainWindow)
    self.mnuAppOuvrir.setObjectName("mnuAppOuvrir")
    self.mnuAppQuitter = QtWidgets.QAction(mainWindow)
    self.mnuAppQuitter.setObjectName("mnuAppQuitter")
    self.mnuDebug_mode = QtWidgets.QAction(mainWindow)
    self.mnuDebug_mode.setCheckable(True)
    self.mnuDebug_mode.setObjectName("mnuDebug_mode")
    self.mnu_MPos = QtWidgets.QAction(mainWindow)
    self.mnu_MPos.setCheckable(True)
    self.mnu_MPos.setChecked(True)
    self.mnu_MPos.setObjectName("mnu_MPos")
    self.mnu_WPos = QtWidgets.QAction(mainWindow)
    self.mnu_WPos.setCheckable(True)
    self.mnu_WPos.setObjectName("mnu_WPos")
    self.mnuApplication.addAction(self.mnuAppOuvrir)
    self.mnuApplication.addSeparator()
    self.mnuApplication.addAction(self.mnuAppQuitter)
    self.menuOptions.addSeparator()
    self.menuOptions.addAction(self.mnu_MPos)
    self.menuOptions.addAction(self.mnu_WPos)
    self.menuOptions.addSeparator()
    self.menuOptions.addAction(self.mnuDebug_mode)
    self.mnuBar.addAction(self.mnuApplication.menuAction())
    self.mnuBar.addAction(self.menuOptions.menuAction())

    self.retranslateUi(mainWindow)
    self.grpConsole.setCurrentIndex(0)
    QtCore.QMetaObject.connectSlotsByName(mainWindow)

  def retranslateUi(self, mainWindow):
    _translate = QtCore.QCoreApplication.translate
    mainWindow.setWindowTitle(_translate("mainWindow", "cn5X"))
    self.btnUrgence.setToolTip(_translate("mainWindow", "Double clic pour\n"
"dévérouiller l\'arrêt d\'urgence"))
    self.label_22.setText(_translate("mainWindow", "Avance"))
    self.lblAvancePourcent.setText(_translate("mainWindow", "100%"))
    self.label_23.setText(_translate("mainWindow", "Broche"))
    self.lblBrochePourcent.setText(_translate("mainWindow", "100%"))
    self.groupBox_4.setTitle(_translate("mainWindow", "Avance Rapide"))
    self.radioButton_10.setText(_translate("mainWindow", "25%"))
    self.radioButton_11.setText(_translate("mainWindow", "50%"))
    self.radioButton_12.setText(_translate("mainWindow", "100%"))
    self.grpJog.setTitle(_translate("mainWindow", "Jogging"))
    self.pushButton_4.setText(_translate("mainWindow", "+B"))
    self.pushButton_5.setText(_translate("mainWindow", "+A"))
    self.pushButton_6.setText(_translate("mainWindow", "Z+"))
    self.pushButton_7.setText(_translate("mainWindow", "+Y"))
    self.pushButton_8.setText(_translate("mainWindow", "-X"))
    self.pushButton_10.setText(_translate("mainWindow", "+X"))
    self.pushButton_11.setText(_translate("mainWindow", "-Y"))
    self.pushButton_12.setText(_translate("mainWindow", "-Z"))
    self.pushButton_13.setText(_translate("mainWindow", "-A"))
    self.pushButton_14.setText(_translate("mainWindow", "-B"))
    self.radioButton.setText(_translate("mainWindow", "+10.00"))
    self.radioButton_2.setText(_translate("mainWindow", "+ 1.00"))
    self.radioButton_3.setText(_translate("mainWindow", "+ 0.10"))
    self.radioButton_4.setText(_translate("mainWindow", "+ 0.01"))
    self.radioButton_5.setText(_translate("mainWindow", "+ 0.00"))
    self.radioButton_6.setText(_translate("mainWindow", "- 0.01"))
    self.radioButton_7.setText(_translate("mainWindow", "- 0.10"))
    self.radioButton_8.setText(_translate("mainWindow", "- 1.00"))
    self.radioButton_9.setText(_translate("mainWindow", "-10.00"))
    self.grpConnexion.setTitle(_translate("mainWindow", "Connexion"))
    self.label.setText(_translate("mainWindow", "Port :"))
    self.cmbPort.setToolTip(_translate("mainWindow", "Selectionnez le port de la machine grbl."))
    self.btnRefresh.setToolTip(_translate("mainWindow", "Refresh list"))
    self.label_2.setText(_translate("mainWindow", "Bauds :"))
    self.lblConnectStatus.setText(_translate("mainWindow", "<Non Connecté>"))
    self.btnConnect.setText(_translate("mainWindow", "(Dé)Connecter"))
    self.label_3.setText(_translate("mainWindow", "X"))
    self.lblPosX.setText(_translate("mainWindow", "+00000.000"))
    self.label_4.setText(_translate("mainWindow", "Y"))
    self.lblPosY.setText(_translate("mainWindow", "+00000.000"))
    self.label_5.setText(_translate("mainWindow", "Z"))
    self.lblPosZ.setText(_translate("mainWindow", "+00000.000"))
    self.label_6.setText(_translate("mainWindow", "A"))
    self.lblPosA.setText(_translate("mainWindow", "+00000.000"))
    self.label_7.setText(_translate("mainWindow", "B"))
    self.lblPosB.setText(_translate("mainWindow", "+00000.000"))
    self.label_26.setText(_translate("mainWindow", "C"))
    self.lblPosC.setText(_translate("mainWindow", "+00000.000"))
    self.label_27.setText(_translate("mainWindow", "Etat Grbl : "))
    self.lblEtat.setText(_translate("mainWindow", "Idle"))
    self.label_12.setText(_translate("mainWindow", "Plan : "))
    self.lblPlan.setText(_translate("mainWindow", "G17"))
    self.label_17.setText(_translate("mainWindow", "Broche :"))
    self.lblBroche.setText(_translate("mainWindow", "M5"))
    self.label_14.setText(_translate("mainWindow", "Unités :"))
    self.lblUnites.setText(_translate("mainWindow", "G21"))
    self.label_18.setText(_translate("mainWindow", "Arrosage :"))
    self.lblArrosage.setText(_translate("mainWindow", "M9"))
    self.label_15.setText(_translate("mainWindow", "Coordonnées :"))
    self.lblCoord.setText(_translate("mainWindow", "G90"))
    self.label_19.setText(_translate("mainWindow", "Outil :"))
    self.lblOutil.setText(_translate("mainWindow", "T0"))
    self.label_13.setText(_translate("mainWindow", "Déplacements :"))
    self.lblDeplacements.setText(_translate("mainWindow", "G0"))
    self.label_21.setText(_translate("mainWindow", "Rotation broche :"))
    self.lblRotation.setText(_translate("mainWindow", "S00000"))
    self.label_16.setText(_translate("mainWindow", "Mode vitesse :"))
    self.lblVitesse.setText(_translate("mainWindow", "G94"))
    self.label_20.setText(_translate("mainWindow", "Avance :"))
    self.lblAvance.setText(_translate("mainWindow", "F00000"))
    self.lblG5xMode.setText(_translate("mainWindow", "Mode actif :"))
    self.lblOffsetActif.setText(_translate("mainWindow", "Offset G54 :"))
    self.lblOffsetG92.setText(_translate("mainWindow", "Offset G92 :"))
    self.lblOffsetWco.setToolTip(_translate("mainWindow", "Working Coordinate Offset"))
    self.lblOffsetWco.setText(_translate("mainWindow", "WCO :"))
    self.lblG54.setText(_translate("mainWindow", "G54"))
    self.lblG55.setText(_translate("mainWindow", "G55"))
    self.lblG56.setText(_translate("mainWindow", "G56"))
    self.lblG57.setText(_translate("mainWindow", "G57"))
    self.lblG58.setText(_translate("mainWindow", "G58"))
    self.lblG59.setText(_translate("mainWindow", "G59"))
    self.lblG5xX.setText(_translate("mainWindow", "+0.000"))
    self.lblG5xY.setText(_translate("mainWindow", "+0.000"))
    self.lblG5xZ.setText(_translate("mainWindow", "+0.000"))
    self.lblG5xA.setText(_translate("mainWindow", "+0.000"))
    self.lblG5xB.setText(_translate("mainWindow", "+0.000"))
    self.lblG5xC.setText(_translate("mainWindow", "+0.000"))
    self.lblG92X.setText(_translate("mainWindow", "+0.000"))
    self.lblG92Y.setText(_translate("mainWindow", "+0.000"))
    self.lblG92Z.setText(_translate("mainWindow", "+0.000"))
    self.lblG92A.setText(_translate("mainWindow", "+0.000"))
    self.lblG92B.setText(_translate("mainWindow", "+0.000"))
    self.lblG92C.setText(_translate("mainWindow", "+0.000"))
    self.lblWcoX.setText(_translate("mainWindow", "+0.000"))
    self.lblWcoY.setText(_translate("mainWindow", "+0.000"))
    self.lblWcoZ.setText(_translate("mainWindow", "+0.000"))
    self.lblWcoA.setText(_translate("mainWindow", "+0.000"))
    self.lblWcoB.setText(_translate("mainWindow", "+0.000"))
    self.lblWcoC.setText(_translate("mainWindow", "+0.000"))
    self.grpConsole.setTabText(self.grpConsole.indexOf(self.tabConsole1), _translate("mainWindow", "Grbl output"))
    self.grpConsole.setTabText(self.grpConsole.indexOf(self.tabConsole2), _translate("mainWindow", "Console output"))
    self.btnStartTimer.setText(_translate("mainWindow", "Start timer"))
    self.btnStopTimer.setText(_translate("mainWindow", "Stop timer"))
    self.btnClearDebug.setText(_translate("mainWindow", "Clear debug"))
    self.grpConsole.setTabText(self.grpConsole.indexOf(self.tabConsole3), _translate("mainWindow", "Debug"))
    self.label_8.setText(_translate("mainWindow", "GCode :"))
    self.btnSend.setText(_translate("mainWindow", "Envoyer"))
    self.mnuApplication.setTitle(_translate("mainWindow", "&Application"))
    self.menuOptions.setTitle(_translate("mainWindow", "Options"))
    self.mnuAppOuvrir.setText(_translate("mainWindow", "&Ouvrir un fichier GCode..."))
    self.mnuAppQuitter.setText(_translate("mainWindow", "&Quitter"))
    self.mnuDebug_mode.setText(_translate("mainWindow", "Debug mode"))
    self.mnu_MPos.setText(_translate("mainWindow", "Visualiser positions machine (MPos)"))
    self.mnu_WPos.setText(_translate("mainWindow", "Visualiser position de travail (WPos)"))

from cnQPushButton import cnQPushButton
from gcodeQLineEdit import gcodeQLineEdit
import cn5X_rc
