# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
  def setupUi(self, mainWindow):
    mainWindow.setObjectName("mainWindow")
    mainWindow.resize(1052, 624)
    icon = QtGui.QIcon()
    icon.addPixmap(QtGui.QPixmap("images/XYZAB-48.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    mainWindow.setWindowIcon(icon)
    self.centralwidget = QtWidgets.QWidget(mainWindow)
    self.centralwidget.setObjectName("centralwidget")
    self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
    self.verticalLayout.setObjectName("verticalLayout")
    self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
    self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
    self.tabWidget.setObjectName("tabWidget")
    self.tab = QtWidgets.QWidget()
    self.tab.setObjectName("tab")
    self.grpConnexion = QtWidgets.QGroupBox(self.tab)
    self.grpConnexion.setGeometry(QtCore.QRect(10, 0, 284, 113))
    self.grpConnexion.setObjectName("grpConnexion")
    self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.grpConnexion)
    self.verticalLayout_2.setContentsMargins(6, 6, 6, 6)
    self.verticalLayout_2.setSpacing(4)
    self.verticalLayout_2.setObjectName("verticalLayout_2")
    self.frame = QtWidgets.QFrame(self.grpConnexion)
    self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
    self.frame.setLineWidth(1)
    self.frame.setObjectName("frame")
    self.gridLayout = QtWidgets.QGridLayout(self.frame)
    self.gridLayout.setContentsMargins(0, 0, 0, 0)
    self.gridLayout.setSpacing(4)
    self.gridLayout.setObjectName("gridLayout")
    self.label = QtWidgets.QLabel(self.frame)
    self.label.setObjectName("label")
    self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
    self.cmbPort = QtWidgets.QComboBox(self.frame)
    self.cmbPort.setMinimumSize(QtCore.QSize(158, 23))
    self.cmbPort.setEditable(True)
    self.cmbPort.setObjectName("cmbPort")
    self.gridLayout.addWidget(self.cmbPort, 0, 1, 1, 1)
    self.label_2 = QtWidgets.QLabel(self.frame)
    self.label_2.setObjectName("label_2")
    self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
    self.cmbBauds = QtWidgets.QComboBox(self.frame)
    self.cmbBauds.setMinimumSize(QtCore.QSize(158, 23))
    self.cmbBauds.setObjectName("cmbBauds")
    self.gridLayout.addWidget(self.cmbBauds, 1, 1, 1, 1)
    self.verticalLayout_2.addWidget(self.frame)
    self.frame_2 = QtWidgets.QFrame(self.grpConnexion)
    self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
    self.frame_2.setObjectName("frame_2")
    self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
    self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
    self.horizontalLayout.setObjectName("horizontalLayout")
    self.lblConnectStatus = QtWidgets.QLabel(self.frame_2)
    self.lblConnectStatus.setMinimumSize(QtCore.QSize(160, 0))
    self.lblConnectStatus.setObjectName("lblConnectStatus")
    self.horizontalLayout.addWidget(self.lblConnectStatus)
    self.btnConnect = QtWidgets.QPushButton(self.frame_2)
    self.btnConnect.setMinimumSize(QtCore.QSize(100, 23))
    self.btnConnect.setObjectName("btnConnect")
    self.horizontalLayout.addWidget(self.btnConnect)
    self.verticalLayout_2.addWidget(self.frame_2)
    self.groupBox = QtWidgets.QGroupBox(self.tab)
    self.groupBox.setGeometry(QtCore.QRect(300, 0, 701, 361))
    self.groupBox.setObjectName("groupBox")
    self.frame_3 = QtWidgets.QFrame(self.groupBox)
    self.frame_3.setGeometry(QtCore.QRect(0, 20, 281, 191))
    self.frame_3.setStyleSheet("background-color: rgb(224, 224, 168);")
    self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
    self.frame_3.setObjectName("frame_3")
    self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
    self.gridLayout_2.setContentsMargins(6, 6, 6, 6)
    self.gridLayout_2.setSpacing(4)
    self.gridLayout_2.setObjectName("gridLayout_2")
    self.label_6 = QtWidgets.QLabel(self.frame_3)
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(20)
    self.label_6.setFont(font)
    self.label_6.setObjectName("label_6")
    self.gridLayout_2.addWidget(self.label_6, 5, 0, 1, 1)
    self.lblPosX = QtWidgets.QLabel(self.frame_3)
    self.lblPosX.setMinimumSize(QtCore.QSize(170, 0))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(20)
    self.lblPosX.setFont(font)
    self.lblPosX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lblPosX.setObjectName("lblPosX")
    self.gridLayout_2.addWidget(self.lblPosX, 0, 1, 1, 1)
    self.label_3 = QtWidgets.QLabel(self.frame_3)
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(20)
    self.label_3.setFont(font)
    self.label_3.setObjectName("label_3")
    self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
    self.label_4 = QtWidgets.QLabel(self.frame_3)
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(20)
    self.label_4.setFont(font)
    self.label_4.setObjectName("label_4")
    self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
    self.lblPosY = QtWidgets.QLabel(self.frame_3)
    self.lblPosY.setMinimumSize(QtCore.QSize(170, 0))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(20)
    self.lblPosY.setFont(font)
    self.lblPosY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lblPosY.setObjectName("lblPosY")
    self.gridLayout_2.addWidget(self.lblPosY, 1, 1, 1, 1)
    self.label_5 = QtWidgets.QLabel(self.frame_3)
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(20)
    self.label_5.setFont(font)
    self.label_5.setObjectName("label_5")
    self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
    self.lblPosZ = QtWidgets.QLabel(self.frame_3)
    self.lblPosZ.setMinimumSize(QtCore.QSize(170, 0))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(20)
    self.lblPosZ.setFont(font)
    self.lblPosZ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lblPosZ.setObjectName("lblPosZ")
    self.gridLayout_2.addWidget(self.lblPosZ, 2, 1, 2, 1)
    self.lblPosA = QtWidgets.QLabel(self.frame_3)
    self.lblPosA.setMinimumSize(QtCore.QSize(170, 0))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(20)
    self.lblPosA.setFont(font)
    self.lblPosA.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lblPosA.setObjectName("lblPosA")
    self.gridLayout_2.addWidget(self.lblPosA, 4, 1, 4, 1)
    self.lblPosB = QtWidgets.QLabel(self.frame_3)
    self.lblPosB.setMinimumSize(QtCore.QSize(170, 0))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(20)
    self.lblPosB.setFont(font)
    self.lblPosB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.lblPosB.setObjectName("lblPosB")
    self.gridLayout_2.addWidget(self.lblPosB, 8, 1, 1, 1)
    self.label_7 = QtWidgets.QLabel(self.frame_3)
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(20)
    self.label_7.setFont(font)
    self.label_7.setObjectName("label_7")
    self.gridLayout_2.addWidget(self.label_7, 8, 0, 1, 1)
    self.frame_4 = QtWidgets.QFrame(self.groupBox)
    self.frame_4.setGeometry(QtCore.QRect(0, 220, 671, 101))
    self.frame_4.setStyleSheet("background-color: rgb(224, 224, 168);")
    self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
    self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
    self.frame_4.setObjectName("frame_4")
    self.lblG54 = QtWidgets.QLabel(self.frame_4)
    self.lblG54.setGeometry(QtCore.QRect(10, 10, 105, 23))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(16)
    font.setBold(True)
    font.setWeight(75)
    self.lblG54.setFont(font)
    self.lblG54.setFrameShape(QtWidgets.QFrame.WinPanel)
    self.lblG54.setFrameShadow(QtWidgets.QFrame.Sunken)
    self.lblG54.setAlignment(QtCore.Qt.AlignCenter)
    self.lblG54.setObjectName("lblG54")
    self.lblG55 = QtWidgets.QLabel(self.frame_4)
    self.lblG55.setGeometry(QtCore.QRect(120, 10, 105, 23))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(16)
    self.lblG55.setFont(font)
    self.lblG55.setFrameShape(QtWidgets.QFrame.WinPanel)
    self.lblG55.setFrameShadow(QtWidgets.QFrame.Raised)
    self.lblG55.setAlignment(QtCore.Qt.AlignCenter)
    self.lblG55.setObjectName("lblG55")
    self.lblG56 = QtWidgets.QLabel(self.frame_4)
    self.lblG56.setGeometry(QtCore.QRect(230, 10, 105, 23))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(16)
    self.lblG56.setFont(font)
    self.lblG56.setFrameShape(QtWidgets.QFrame.WinPanel)
    self.lblG56.setFrameShadow(QtWidgets.QFrame.Raised)
    self.lblG56.setAlignment(QtCore.Qt.AlignCenter)
    self.lblG56.setObjectName("lblG56")
    self.lblG57 = QtWidgets.QLabel(self.frame_4)
    self.lblG57.setGeometry(QtCore.QRect(340, 10, 105, 23))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(16)
    self.lblG57.setFont(font)
    self.lblG57.setFrameShape(QtWidgets.QFrame.WinPanel)
    self.lblG57.setFrameShadow(QtWidgets.QFrame.Raised)
    self.lblG57.setAlignment(QtCore.Qt.AlignCenter)
    self.lblG57.setObjectName("lblG57")
    self.lblG58 = QtWidgets.QLabel(self.frame_4)
    self.lblG58.setGeometry(QtCore.QRect(450, 10, 105, 23))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(16)
    self.lblG58.setFont(font)
    self.lblG58.setFrameShape(QtWidgets.QFrame.WinPanel)
    self.lblG58.setFrameShadow(QtWidgets.QFrame.Raised)
    self.lblG58.setLineWidth(1)
    self.lblG58.setAlignment(QtCore.Qt.AlignCenter)
    self.lblG58.setObjectName("lblG58")
    self.lblG59 = QtWidgets.QLabel(self.frame_4)
    self.lblG59.setGeometry(QtCore.QRect(560, 10, 105, 23))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(16)
    self.lblG59.setFont(font)
    self.lblG59.setFrameShape(QtWidgets.QFrame.WinPanel)
    self.lblG59.setFrameShadow(QtWidgets.QFrame.Raised)
    self.lblG59.setAlignment(QtCore.Qt.AlignCenter)
    self.lblG59.setObjectName("lblG59")
    self.lblG5xX = QtWidgets.QLabel(self.frame_4)
    self.lblG5xX.setGeometry(QtCore.QRect(20, 40, 120, 21))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(12)
    self.lblG5xX.setFont(font)
    self.lblG5xX.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.lblG5xX.setFrameShadow(QtWidgets.QFrame.Sunken)
    self.lblG5xX.setAlignment(QtCore.Qt.AlignCenter)
    self.lblG5xX.setObjectName("lblG5xX")
    self.lblG5xY = QtWidgets.QLabel(self.frame_4)
    self.lblG5xY.setGeometry(QtCore.QRect(140, 40, 120, 21))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(12)
    self.lblG5xY.setFont(font)
    self.lblG5xY.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.lblG5xY.setFrameShadow(QtWidgets.QFrame.Sunken)
    self.lblG5xY.setAlignment(QtCore.Qt.AlignCenter)
    self.lblG5xY.setObjectName("lblG5xY")
    self.lblG5xZ = QtWidgets.QLabel(self.frame_4)
    self.lblG5xZ.setGeometry(QtCore.QRect(260, 40, 120, 21))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(12)
    self.lblG5xZ.setFont(font)
    self.lblG5xZ.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.lblG5xZ.setFrameShadow(QtWidgets.QFrame.Sunken)
    self.lblG5xZ.setAlignment(QtCore.Qt.AlignCenter)
    self.lblG5xZ.setObjectName("lblG5xZ")
    self.lblG5xA = QtWidgets.QLabel(self.frame_4)
    self.lblG5xA.setGeometry(QtCore.QRect(390, 40, 120, 21))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(12)
    self.lblG5xA.setFont(font)
    self.lblG5xA.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.lblG5xA.setFrameShadow(QtWidgets.QFrame.Sunken)
    self.lblG5xA.setAlignment(QtCore.Qt.AlignCenter)
    self.lblG5xA.setObjectName("lblG5xA")
    self.lblG5xB = QtWidgets.QLabel(self.frame_4)
    self.lblG5xB.setGeometry(QtCore.QRect(510, 40, 120, 21))
    font = QtGui.QFont()
    font.setFamily("LED Calculator")
    font.setPointSize(12)
    self.lblG5xB.setFont(font)
    self.lblG5xB.setFrameShape(QtWidgets.QFrame.NoFrame)
    self.lblG5xB.setFrameShadow(QtWidgets.QFrame.Sunken)
    self.lblG5xB.setAlignment(QtCore.Qt.AlignCenter)
    self.lblG5xB.setObjectName("lblG5xB")
    self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
    self.groupBox_2.setGeometry(QtCore.QRect(10, 120, 281, 211))
    self.groupBox_2.setObjectName("groupBox_2")
    self.btnStart = QtWidgets.QPushButton(self.groupBox_2)
    self.btnStart.setEnabled(False)
    self.btnStart.setGeometry(QtCore.QRect(10, 150, 50, 50))
    self.btnStart.setMinimumSize(QtCore.QSize(50, 50))
    self.btnStart.setMaximumSize(QtCore.QSize(50, 50))
    self.btnStart.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.btnStart.setStyleSheet("border-radius: 25;")
    self.btnStart.setText("")
    icon1 = QtGui.QIcon()
    icon1.addPixmap(QtGui.QPixmap("images/btnStart.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.btnStart.setIcon(icon1)
    self.btnStart.setIconSize(QtCore.QSize(50, 50))
    self.btnStart.setObjectName("btnStart")
    self.btnStop = QtWidgets.QPushButton(self.groupBox_2)
    self.btnStop.setEnabled(False)
    self.btnStop.setGeometry(QtCore.QRect(80, 150, 50, 50))
    self.btnStop.setMinimumSize(QtCore.QSize(50, 50))
    self.btnStop.setMaximumSize(QtCore.QSize(50, 50))
    self.btnStop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    self.btnStop.setStyleSheet("border-radius: 25;")
    self.btnStop.setText("")
    icon2 = QtGui.QIcon()
    icon2.addPixmap(QtGui.QPixmap("images/btnStop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.btnStop.setIcon(icon2)
    self.btnStop.setIconSize(QtCore.QSize(50, 50))
    self.btnStop.setObjectName("btnStop")
    self.btnUrgence = QtWidgets.QPushButton(self.groupBox_2)
    self.btnUrgence.setGeometry(QtCore.QRect(20, 30, 100, 100))
    self.btnUrgence.setMinimumSize(QtCore.QSize(100, 100))
    self.btnUrgence.setMaximumSize(QtCore.QSize(100, 100))
    self.btnUrgence.setStyleSheet("border-radius: 25;")
    self.btnUrgence.setText("")
    icon3 = QtGui.QIcon()
    icon3.addPixmap(QtGui.QPixmap("images/btnUrgenceOff.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
    self.btnUrgence.setIcon(icon3)
    self.btnUrgence.setIconSize(QtCore.QSize(100, 100))
    self.btnUrgence.setCheckable(True)
    self.btnUrgence.setChecked(True)
    self.btnUrgence.setObjectName("btnUrgence")
    self.ptxtDebug = QtWidgets.QPlainTextEdit(self.tab)
    self.ptxtDebug.setGeometry(QtCore.QRect(0, 410, 681, 121))
    self.ptxtDebug.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
    self.ptxtDebug.setReadOnly(True)
    self.ptxtDebug.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
    self.ptxtDebug.setObjectName("ptxtDebug")
    self.txtGCode = QtWidgets.QLineEdit(self.tab)
    self.txtGCode.setGeometry(QtCore.QRect(70, 370, 531, 31))
    self.txtGCode.setClearButtonEnabled(True)
    self.txtGCode.setObjectName("txtGCode")
    self.btnSend = QtWidgets.QPushButton(self.tab)
    self.btnSend.setGeometry(QtCore.QRect(610, 370, 80, 31))
    self.btnSend.setObjectName("btnSend")
    self.label_8 = QtWidgets.QLabel(self.tab)
    self.label_8.setGeometry(QtCore.QRect(10, 370, 61, 31))
    self.label_8.setObjectName("label_8")
    self.tabWidget.addTab(self.tab, "")
    self.tab_2 = QtWidgets.QWidget()
    self.tab_2.setObjectName("tab_2")
    self.tabWidget.addTab(self.tab_2, "")
    self.verticalLayout.addWidget(self.tabWidget)
    mainWindow.setCentralWidget(self.centralwidget)
    self.mnuBar = QtWidgets.QMenuBar(mainWindow)
    self.mnuBar.setGeometry(QtCore.QRect(0, 0, 1052, 22))
    self.mnuBar.setObjectName("mnuBar")
    self.mnuApplication = QtWidgets.QMenu(self.mnuBar)
    self.mnuApplication.setObjectName("mnuApplication")
    mainWindow.setMenuBar(self.mnuBar)
    self.statusBar = QtWidgets.QStatusBar(mainWindow)
    self.statusBar.setObjectName("statusBar")
    mainWindow.setStatusBar(self.statusBar)
    self.mnuAppOuvrir = QtWidgets.QAction(mainWindow)
    self.mnuAppOuvrir.setObjectName("mnuAppOuvrir")
    self.mnuAppQuitter = QtWidgets.QAction(mainWindow)
    self.mnuAppQuitter.setObjectName("mnuAppQuitter")
    self.mnuApplication.addAction(self.mnuAppOuvrir)
    self.mnuApplication.addSeparator()
    self.mnuApplication.addAction(self.mnuAppQuitter)
    self.mnuBar.addAction(self.mnuApplication.menuAction())

    self.retranslateUi(mainWindow)
    self.tabWidget.setCurrentIndex(0)
    QtCore.QMetaObject.connectSlotsByName(mainWindow)

  def retranslateUi(self, mainWindow):
    _translate = QtCore.QCoreApplication.translate
    mainWindow.setWindowTitle(_translate("mainWindow", "cn5X"))
    self.grpConnexion.setTitle(_translate("mainWindow", "Connexion"))
    self.label.setText(_translate("mainWindow", "Port :"))
    self.cmbPort.setToolTip(_translate("mainWindow", "Selectionnez le port de la machine grbl."))
    self.label_2.setText(_translate("mainWindow", "Bauds :"))
    self.lblConnectStatus.setText(_translate("mainWindow", "<Non Connecté>"))
    self.btnConnect.setText(_translate("mainWindow", "(Dé)Connecter"))
    self.groupBox.setTitle(_translate("mainWindow", "Machine status"))
    self.label_6.setText(_translate("mainWindow", "A"))
    self.lblPosX.setText(_translate("mainWindow", "+00000.000"))
    self.label_3.setText(_translate("mainWindow", "X"))
    self.label_4.setText(_translate("mainWindow", "Y"))
    self.lblPosY.setText(_translate("mainWindow", "+00000.000"))
    self.label_5.setText(_translate("mainWindow", "Z"))
    self.lblPosZ.setText(_translate("mainWindow", "+00000.000"))
    self.lblPosA.setText(_translate("mainWindow", "+00000.000"))
    self.lblPosB.setText(_translate("mainWindow", "+00000.000"))
    self.label_7.setText(_translate("mainWindow", "B"))
    self.lblG54.setText(_translate("mainWindow", "G54"))
    self.lblG55.setText(_translate("mainWindow", "G55"))
    self.lblG56.setText(_translate("mainWindow", "G56"))
    self.lblG57.setText(_translate("mainWindow", "G57"))
    self.lblG58.setText(_translate("mainWindow", "G58"))
    self.lblG59.setText(_translate("mainWindow", "G59"))
    self.lblG5xX.setText(_translate("mainWindow", "+00000.000"))
    self.lblG5xY.setText(_translate("mainWindow", "+00000.000"))
    self.lblG5xZ.setText(_translate("mainWindow", "+00000.000"))
    self.lblG5xA.setText(_translate("mainWindow", "+00000.000"))
    self.lblG5xB.setText(_translate("mainWindow", "+00000.000"))
    self.groupBox_2.setTitle(_translate("mainWindow", "GroupBox"))
    self.btnUrgence.setToolTip(_translate("mainWindow", "Double clic pour\n"
"dévérouiller l\'arrêt d\'urgence"))
    self.btnSend.setText(_translate("mainWindow", "Envoyer"))
    self.label_8.setText(_translate("mainWindow", "GCode :"))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainWindow", "Tab 1"))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("mainWindow", "Tab 2"))
    self.mnuApplication.setTitle(_translate("mainWindow", "&Application"))
    self.mnuAppOuvrir.setText(_translate("mainWindow", "&Ouvrir un fichier GCode..."))
    self.mnuAppQuitter.setText(_translate("mainWindow", "&Quitter"))

